---
title: "2023 HTS: Walk, Bike, Micromobility"
author: "Grant Gibson"
format: html
editor: visual
---

# Travel Mode: Walk, Bike, & Micromobility

## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(data.table)
library(stringr)
library(travelSurveyTools)
library(psrcelmer)
library(dplyr)
library(psrcplot)
library(tidyverse)
source("C:/Users/GGibson/GitHub/PSRC/travel-studies/2023/summary/survey-23-preprocess.R")
```

## Read in codebook

```{r codebook}
cb_path = str_glue("J:/Projects/Surveys/HHTravel/Survey2023/Data/data_published/PSRC_Codebook_2023_v1.xlsx")

variable_list = readxl::read_xlsx(cb_path, sheet = 'variable_list')
value_labels = readxl::read_xlsx(cb_path, sheet = 'value_labels')

setDT(variable_list)
setDT(value_labels)
```

## Read in data from Elmer

```{r elmer_data}
hh <- get_query(sql = "SELECT household_id as hh_id, num_trips AS h_num_trips, hhsize, vehicle_count, hhincome_broad,
                       home_rgcname, home_county, survey_year, hh_weight
                       FROM HHSurvey.v_households_labels;")

person <- get_query(sql = "SELECT person_id, household_id as hh_id, num_trips AS p_num_trips, age, gender, race_category,
                           employment, workplace, commute_freq, commute_mode, survey_year, person_weight
                           FROM HHSurvey.v_persons_labels;")

trip <- get_query(sql = "SELECT trip_id, household_id as hh_id, person_id, origin_x_coord, origin_y_coord, origin_county, origin_rgcname,
                         dest_x_coord, dest_y_coord, dest_county, dest_rgcname, distance_miles, duration_minutes,
                         origin_purpose_cat, origin_purpose, dest_purpose_cat, dest_purpose,
                         mode_type, mode_1, mode_characterization, mode_simple, travelers_total, travelers_hh,
                         survey_year, trip_weight 
                         FROM HHSurvey.v_trips_labels
                         WHERE travel_dow NOT IN ('Friday', 'Saturday', 'Sunday');")

setDT(hh)
setDT(person)
setDT(trip)
```

## Set IDs as character type

```{r set_ids}
hh[, hh_id := as.character(hh_id)]

person[, hh_id := as.character(hh_id)]
person[, person_id := as.character(person_id)]

trip[, hh_id := as.character(hh_id)]
trip[, person_id := as.character(person_id)]
trip[, trip_id := as.character(trip_id)]

hh[, survey_year := as.character(survey_year)]
person[, survey_year := as.character(survey_year)]
trip[, survey_year := as.character(survey_year)]
```

## Get unique modes from trips

```{r trip_modes}
trip_modes <- unique(trip[, c("mode_1", "mode_type", "mode_characterization", "mode_simple")])

# add mode_simple to variables list
variable_list <- add_variable(variable_list, "mode_simple", "trip")
group_labels <- get_grouped_labels(group_id = "group_1", group_name = "mode_simple")
value_labels <- add_values_code(group_name = "mode_simple")
```

Based on the modes in the trip data, will need to filter on `mode_characterization` to remove "Airplane"

## Filter trips to walk, bike, micromobility

```{r walk_bike filter}
trip <- filter(trip, mode_characterization != "Airplane")
```

## Initial summaries

```{r summary}
hts_data <- list(hh = hh,
                 person = person,
                 trip = trip)
ids <- c("hh_id", "person_id", "trip_id")
wts <- c("hh_weight", "person_weight", "trip_weight")

summary_trips <- summarize_weighted(hts_data = hts_data,
                                    summarize_var = "mode_simple",
                                    summarize_by = "survey_year",
                                    id_cols = ids,
                                    wt_cols = wts,
                                    wtname = "trip_weight"
                                    )

mode_summary <- summary_trips$summary$wtd %>% 
  mutate(moe = prop_se * 1.645)
```

## Initial charts

```{r walk_chart_est, echo=FALSE}
static_column_chart(filter(mode_summary, mode_simple == "Walk"),
                    x = "survey_year", y = "est", fill = "mode_simple",
                    ylabel = "# of Trips", xlabel = "Survey Year", title = "Walk Trips - Estimate",
                    moe = "est_se") + theme(
                      axis.text.x = element_text(size = 14),
                      axis.text.y = element_text(size = 14),
                      axis.title.y = element_text(size = 20),
                      axis.title.x = element_text(size = 20),
                      plot.title = element_text(size = 24)
                      )
```

```{r walk_chart_share, echo=FALSE}
# need to reconfigure full trip table to determine accurate share of trips by mode
static_column_chart(filter(mode_summary, mode_simple == "Walk"),
                    x = "survey_year", y = "prop", fill = "mode_simple",
                    ylabel = "% of Trips", xlabel = "Survey Year", title = "Walk Trips - Share",
                    moe = "moe") + theme(
                      axis.text.x = element_text(size = 14),
                      axis.text.y = element_text(size = 14),
                      axis.title.y = element_text(size = 20),
                      axis.title.x = element_text(size = 20),
                      plot.title = element_text(size = 24)
                      )
```

```{r bike_chart_est, echo=FALSE}
static_column_chart(filter(mode_summary, mode_simple == "Bike"),
                    x = "survey_year", y = "est", fill = "mode_simple",
                    ylabel = "# of Trips", xlabel = "Survey Year",
                    title = "Bike Trips - Estimate", source = "'Bike' includes standard bicycle or e-bike, privately owned or bike share",
                    moe = "est_se") + theme(
                      axis.text.x = element_text(size = 14),
                      axis.text.y = element_text(size = 14),
                      axis.title.y = element_text(size = 20),
                      axis.title.x = element_text(size = 20),
                      plot.title = element_text(size = 24),
                      plot.caption = element_text(size = 14)
                      )
```

```{r bike_trips_share, echo=FALSE}
static_column_chart(filter(mode_summary, mode_simple == "Bike"),
                    x = "survey_year", y = "prop", fill = "mode_simple",
                    ylabel = "% of Trips", xlabel = "Survey Year",
                    title = "Bike Trips - Share", source = "'Bike' includes standard bicycle or e-bike, privately owned or bike share",
                    moe = "moe") + theme(
                      axis.text.x = element_text(size = 14),
                      axis.text.y = element_text(size = 14),
                      axis.title.y = element_text(size = 20),
                      axis.title.x = element_text(size = 20),
                      plot.title = element_text(size = 24),
                      plot.caption = element_text(size = 14)
                      )
```
