---
title: "Detailed Household Income by Trip Path Distance "
author: "Christy"
date: '2022-06-07'
output: html_document
---

## Detailed Household Income by Trip Path Distance 

```{r income process, eval=FALSE}
t_vars <- c('mode_1', 'trip_path_distance')
inc_dist_2019 <- get_hhts(dyear = 2019,
         level = 't',
         vars = t_vars)

t <- inc_dist_2019 %>% 
  filter(trip_path_distance > 200)

t2 <- inc_dist_2019 %>% 
  filter(mode_1 == "Airplane or helicopter")

```

```{r income, eval=TRUE}
# hhincome_detailed # abs_hh_weight
# trip_path_distance # Bing-estimated trip distance (miles), combined_adult_trip_weight

stat <- 'median'
tpd <- 100

i_vars <- c('mode_1', 'hhincome_detailed', 'trip_path_distance')
inc_levels <- c("Under $10,000" ,"$10,000-$24,999","$25,000-$34,999","$35,000-$49,999",
                "$50,000-$74,999", "$75,000-$99,999", "$100,000-$149,999", "$150,000-$199,999",
                "$200,000-$249,999", "$250,000 or more", "Prefer not to answer", "Total")

inc_dist_2019 <- get_hhts(survey = survey_a$survey,
         level = 't',
         vars = i_vars) %>% 
  filter(mode_1 != 'Airplane or helicopter') %>% 
  filter(trip_path_distance < tpd)

inc_dist_sum_2019 <- hhts_median(inc_dist_2019,
                                stat_var = 'trip_path_distance', # numeric variable (distance)
                                spec_wgt = 'trip_weight_2017_2019_v2021_adult',
                                group_vars = c('hhincome_detailed')) # category (income, race, gender)

id_19 <- inc_dist_sum_2019 %>% 
  rename(m = ends_with(stat), moe = ends_with('moe')) %>% 
  mutate(hhincome_detailed = factor(hhincome_detailed, levels = inc_levels),
         lower = m - moe,
         upper = m + moe,
         year = survey_a$label)

inc_dist_2021 <- get_hhts(survey = survey_b$survey,
         level = 't',
         vars = i_vars) %>% 
  filter(mode_1 != 'Airplane or helicopter') %>% 
  filter(trip_path_distance < tpd)

inc_dist_sum_2021 <- hhts_median(inc_dist_2021,
                                stat_var = 'trip_path_distance',
                                spec_wgt = 'trip_weight_2021_ABS_Panel_adult',
                                group_vars = c('hhincome_detailed'))

id_21 <- inc_dist_sum_2021 %>% 
  rename(m = ends_with(stat), moe = ends_with('moe')) %>% 
  mutate(hhincome_detailed = factor(hhincome_detailed, levels = inc_levels),
         lower = m - moe,
         upper = m + moe,
         year = survey_b$label)

## plot ----

plot.title.itpd <- paste('Detailed Household Income by', str_to_title(stat), 'Trip Path Distance')
plot.subtitle.itpd <- paste('Trips less than', tpd, 'miles')

id_1921 <- bind_rows(id_19, id_21) %>% 
  mutate(year = as.factor(year))



i <- ggplot(id_1921, aes(x = hhincome_detailed, 
                         y = m, 
                         fill = year,
                         tooltip = paste0(year, ": ", round(m, 1), ' miles'))) +
  geom_col_interactive(position = position_dodge(width=.9)) +
  geom_linerange(aes(ymin = lower,
                    ymax = upper),
                 position = position_dodge(width=.9)) +
  scale_fill_brewer(palette = "Paired") +
  scale_y_continuous(labels = scales::label_comma()) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.title = element_blank(),
        legend.position = 'bottom',
        panel.background = element_rect(fill = background.color),
        panel.grid.major.y = element_line(color = gridline.color),
        panel.grid.minor.y = element_line(color = gridline.color),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.caption = element_text(size=5)) +
  labs(x = NULL,
       y = 'Miles',
       fill = NULL,
       title = plot.title.itpd,
       caption = plot.source,
       subtitle = plot.subtitle.itpd)

girafe(ggobj = i)

```

- Lower Household earnings ($34k and less) had trips with higher distances in 2021.
- Households with earnings between $35k and $150k or $200k+ saw a decrease in median trip distance.
