---
title: "telecommute_where_travelbehavior"
author: "suzanne"
date: "2024-07-16"
output: html_document
---

telecommute amount by work location

run telecommute_july23.Rmd first
```{r}
library(sf)
```

`

```{r}
variable_list<-add_variable(variable_list, 'workrgc','person')

value<- c(0,1)
label=c('workRGC', 'workNotRGC')
workgeo_val_labels<-data.frame(value, label)
workgeo_val_labels<-workgeo_val_labels%>%mutate(variable='workrgc')%>%
    mutate(group_1_title = NA, group_1_value = NA,
           group_2_title = NA, group_2_value= NA,
           group_3_title = NA, group_3_value = NA)

all_value_labels<-value_labels%>%select(variable, value, label, group_1_title, group_1_value,
                                      group_2_title, group_2_value, group_3_title, group_3_value)
new_value_labels<-rbind(all_value_labels, workgeo_val_labels)
new_value_labels[, val_order := seq_len(nrow(new_value_labels))]
value_labels<-new_value_labels  


```

```{r}
workers_hh<-merge(workers, hh, by='hh_id')
workers_hh<-workers_hh%>%mutate(workrgc=
                            case_when(
                          (telecommute_status=='Fully At Home' & (is.na(home_rgcname)|
                                                                   home_rgcname=='Not RGC'))~ 'workNotRGC',
                          telecommute_status=='Fully At Home' & !is.na(home_rgcname)~ 'workRGC',
                          is.na(work_rgcname)|work_rgcname =='Not RGC' ~ 'workNotRGC',
                          !is.na(work_rgcname) ~ 'workRGC'))
workers_hh<-workers_hh%>%mutate(survey_year=survey_year.x)
```



```{r}

worker_list<-list( person=workers_hh)

```

```{r}
#some how a duplicate snuck into the variable list not sure how
variable_list<-variable_list%>%distinct(variable, .keep_all=TRUE)
```

```{r}

telecommute_workgeo<- summarize_weighted(hts_data= worker_list,
                               summarize_var = 'telecommute_status',
                               summarize_by = c('survey_year', 'workrgc'),
                               id_cols=c('person_id'),
                               wt_cols=c('person_weight'),
                               wtname= 'person_weight'
                               )

```


```{r}

telecommute_workgeo<-telecommute_workgeo$summary$wtd%>%filter(survey_year=='2023')%>%mutate(moe=prop_se*1.645)%>%mutate(telecommute_status=factor(telecommute_status, levels=c('Fully In Person', 'Hybrid', 'Fully At Home')))%>%mutate(workrgc_name=case_when(
  workrgc == 'workRGC' ~ 'In a Regional Growth Center',
  workrgc =='workNotRGC' ~ 'Outside a Regional Growth Center')
  
)
                                                                                                                                                                                                    
                                                                                                   
static<-static_column_chart(telecommute_workgeo, y='prop', x='workrgc_name', fill='telecommute_status') + theme(axis.text.x=element_text(size=16), axis.text.y=element_text(size=16),legend.text = element_text(size=16), axis.title.y=element_text(size=20), axis.title.x=element_text(size=20))+
   scale_y_continuous(labels = scales::percent_format(scale = 100), limits=c(0,1))

static

write.csv(telecommute_workgeo,'telecommute_summary_workgeog.csv')

```

```

