---
title: "centers analysis"
author: "suzanne"
date: "2022-08-11"
output: html_document
---

```{r }
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(ggplot2)
library(psrcplot)
library(forcats)
library(odbc)
library(DBI)
library(tidyr)
install_psrc_fonts()
```

Mode Split Overall Centers vs Not

2017/2019
2021

```{r Elmer variable metadata}
# connect to Elmer
db.connect <- function(adatabase) {
  elmer_connection <- dbConnect(odbc(),
                                driver = "SQL Server",
                                server = "AWS-PROD-SQL\\SOCKEYE",
                                database = adatabase,
                                trusted_connection = "yes"
  )
}

# read table
read.dt <- function(adatabase, atable) {
  elmer_connection <- db.connect(adatabase)
  dtelm <- dbReadTable(elmer_connection, SQL(atable))
  dbDisconnect(elmer_connection)
  return(dtelm)
}

# read-in variable metadata table for levels
vars_meta <- read.dt('Elmer', 'HHSurvey.variable_metadata')
```

```{r}
all_vars<-c('mode_1', 'mode_simple', 'travelers_total', 'origin_purpose', 'dest_purpose', 'o_rgcname', 'd_rgcname', 'trip_path_distance', 'driver', 'final_home_rgcnum', 'final_home_is_rgc')
```


Mode Split for Work Trips Centers vs Not

2017/2019
2021






```{r}
trip_data_17_19<- get_hhts("2017_2019", "t", vars=all_vars)%>% mutate(year=ifelse(survey=='2017_2019', '2017/2019', '2021'))
```


```{r}
trip_data_21<- get_hhts("2021", "t", vars=all_vars)%>% mutate(year=ifelse(survey=='2017_2019', '2017/2019', '2021'))

```

```{r}
trip_data_17_19<- trip_data_17_19%>%mutate(mode_with_hov = ifelse(mode_simple=='Drive' & travelers_total>1, 'HOV', mode_simple))%>% mutate(mode_with_hov=ifelse(mode_with_hov=='Drive', 'SOV', mode_with_hov))%>%mutate(RGC_End=ifelse((!is.na(o_rgcname)|!is.na(d_rgcname)), 'RGC Trip End', 'Not RGC Trip End'))


trip_data_21<- trip_data_21%>%mutate(mode_with_hov = ifelse(mode_simple=='Drive' & travelers_total>1, 'HOV', mode_simple))%>%mutate (mode_with_hov=ifelse(mode_with_hov=='Drive', 'SOV', mode_with_hov))%>%mutate(RGC_End=ifelse((!is.na(o_rgcname)|!is.na(d_rgcname)), 'RGC Trip End', 'Not RGC Trip End'))


```

```{r}
work_trips_17_19<-trip_data_17_19%>%filter(origin_purpose=='Went to primary workplace' | dest_purpose=='Went to primary workplace')%>%drop_na(mode_with_hov)
  

work_trips_by_mode_17_19<-hhts_count(work_trips_17_19, group_vars=c('RGC_End','mode_with_hov'), spec_wgt='trip_weight_2017_2019_v2021_adult')%>%filter(mode_with_hov!='Total')%>%filter(RGC_End!='Total')
  
  
work_trips_21<-trip_data_21%>%filter(origin_purpose=='Went to primary workplace' | dest_purpose=='Went to primary workplace')%>%drop_na(mode_with_hov)
  

work_trips_by_mode_21<-hhts_count(work_trips_21, group_vars=c('RGC_End','mode_with_hov'),spec_wgt='trip_weight_2021_ABS_Panel_adult')%>%filter(mode_with_hov!='Total')%>%filter(RGC_End!='Total')
  

work_trips_by_mode_17_19_21<-merge(work_trips_by_mode_17_19, work_trips_by_mode_21, by=c('mode_with_hov', 'RGC_End'), suffixes=c('17_19', '21'))
work_trips_by_mode<-rbind(work_trips_by_mode_17_19, work_trips_by_mode_21)%>% mutate(year=ifelse(survey=='2017_2019', '2017/2019', '2021'))
                                           


```

```{r}
p<-create_facet_bar_chart(t=work_trips_by_mode, w.x='mode_with_hov', w.y='share', f='year', g='RGC_End', w.moe='share_moe', est.type='percent', w.color = 'psrc_light')+
  xlab(as.character('Work Trip Mode')) + ylab('Share of All Work Trips')+theme(axis.text.x = element_text(size=14,color="#4C4C4C"))+ theme(axis.title.x = element_text(size=20,color="#4C4C4C"))+theme(axis.title.y = element_text(size=20,color="#4C4C4C"))+coord_flip()
  

print(p)
```


All Trip 

```{r}
trips_17_19<-trip_data_17_19%>%drop_na(mode_with_hov)
  

trips_by_mode_17_19<-hhts_count(trips_17_19, group_vars=c('RGC_End','mode_with_hov'), spec_wgt='trip_weight_2017_2019_v2021_adult')%>%filter(mode_with_hov!='Total')%>%filter(RGC_End!='Total')
  
  
trips_21<-trip_data_21%>%drop_na(mode_with_hov)
  

trips_by_mode_21<-hhts_count(trips_21, group_vars=c('RGC_End','mode_with_hov'),spec_wgt='trip_weight_2021_ABS_Panel_adult')%>%filter(mode_with_hov!='Total')%>%filter(RGC_End!='Total')
  

trips_by_mode_17_19_21<-merge(trips_by_mode_17_19, trips_by_mode_21, by=c('mode_with_hov', 'RGC_End'), suffixes=c('17_19', '21'))
trips_by_mode<-rbind(trips_by_mode_17_19, trips_by_mode_21)%>% mutate(year=ifelse(survey=='2017_2019', '2017/2019', '2021'))
                                           


```

```{r}
p<-create_facet_bar_chart(t=trips_by_mode, w.x='mode_with_hov', w.y='share', f='year', g='RGC_End', w.moe='share_moe', est.type='percent', w.color = 'psrc_light')+
  xlab(as.character('Trip Mode')) + ylab('Share of All  Trips')+theme(axis.text.x = element_text(size=14,color="#4C4C4C"))+ theme(axis.title.x = element_text(size=20,color="#4C4C4C"))+theme(axis.title.y = element_text(size=20,color="#4C4C4C"))+coord_flip()
  

print(p)
```


2017/2019
2021

living in centers all trips


```{r}
trips_17_19<-trip_data_17_19%>%drop_na(mode_with_hov)
  

trips_by_mode_17_19<-hhts_count(trips_17_19, group_vars=c('final_home_is_rgc','mode_with_hov'), spec_wgt='trip_weight_2017_2019_v2021_adult')%>%filter(mode_with_hov!='Total')%>%filter(final_home_is_rgc!='Total')
  
  
trips_21<-trip_data_21%>%drop_na(mode_with_hov)
  

trips_by_mode_21<-hhts_count(trips_21, group_vars=c('final_home_is_rgc','mode_with_hov'),spec_wgt='trip_weight_2021_ABS_Panel_adult')%>%filter(mode_with_hov!='Total')%>%filter(final_home_is_rgc!='Total')
  

trips_by_mode_17_19_21<-merge(trips_by_mode_17_19, trips_by_mode_21, by=c('mode_with_hov','final_home_is_rgc'), suffixes=c('17_19', '21'))
trips_by_mode<-rbind(trips_by_mode_17_19, trips_by_mode_21)%>% mutate(year=ifelse(survey=='2017_2019', '2017/2019', '2021'))
                                           


```

```{r}
p<-create_facet_bar_chart(t=trips_by_mode, w.x='mode_with_hov', w.y='share', f='year', g='final_home_is_rgc', w.moe='share_moe', est.type='percent', w.color = 'psrc_light')+
  xlab(as.character('Share of All  Trips')) + ylab(' Trip Mode')+theme(axis.text.x = element_text(size=14,color="#4C4C4C"))+ theme(axis.title.x = element_text(size=20,color="#4C4C4C"))+theme(axis.title.y = element_text(size=20,color="#4C4C4C"))+coord_flip()
  

print(p)
```


Individual Center analysis

Mode split over all for these centers



