

```{r setup, include=FALSE}
# Required Packages ============================================================

library(data.table) # general data manipulation
library(srvyr)      # survey statistics
library(dplyr)      # helpers for srvyr (mutate, group_by, and %>% pipe), 
                    # plus function near(), used in qa/qc checks 
library(stringr)    # string helper functions
library(flextable)  # formatted tables
library(ggplot2)    # plotting
library(scales)     # ggplot2 helpers
library(plotly)     # interactive plots
library(rstudioapi) # for setting working directory
library(psrcelmer)
library(tidyr)
library(psrc.travelsurvey)
library(psrcplot)
install_psrc_fonts()
#
# Read Data  ===================================================================

# get data on workers
person<- get_hhts(survey="2021", level="p", vars=c('employment'))
workers<-person%>%filter(employment %in% c("Employed full time (35+ hours/week, paid)", "Self-employed","Employed part time (fewer than 35 hours/week, paid)"))%>%mutate(person_id=as.character(person_id))

# get day info

dsurvey <- get_hhts(survey = '2021', 
                       level = "d", 
                       vars = c("dayofweek", "pernum", "telework_time"))

dsurvey<-dsurvey[,!duplicated(colnames(dsurvey))]%>%mutate(person_id=as.character(person_id), daynum=as.character(daynum))
 
 
  
                                                           
trip<- get_hhts(survey="2021", level="t", vars=c('dest_purpose_cat', 'daynum', 'dest_purpose'))

trip<-trip[,!duplicated(colnames(trip))]%>%
                  mutate(trip_wt_1_day=trip_adult_weight_2021)%>%mutate(person_id=as.character(person_id), daynum=as.character(daynum))
 
```


merge, because we only selected one day the person ids are one to one
```{r}
workers_day<-left_join(workers, dsurvey, by='person_id')%>% drop_na(telework_time)
workers_trips<-left_join(workers_day, trip, by = 'person_id')%>%
  filter(dest_purpose %in% c("Went to primary workplace" ))

```

summarize the number of workers in each telework time bin, weighted, and unweighted
```{r}
workers_telework_time<-workers_day%>%
  group_by(telework_time)%>%
  summarize(raw_count=n(), weighted_count=sum(person_adult_weight_2021.x))%>%
  mutate(unweighted_share=raw_count/sum(raw_count), weighted_share=weighted_count/sum(weighted_count))%>%
  mutate(telework_time=factor(telework_time, levels= c('0 hours', 'Less than 1 hour', '1-6 hours', 'More than 6 hours' )))
  

```

```{r}
static_column_chart(workers_telework_time, x='telework_time', y='raw_count', fill='telework_time', title='Telework Time for workers on weekdays', xlabel='Telework Hours', ylabel='Total Observed (unweighted) Workers')
```
```{r}
static_column_chart(workers_telework_time, x='telework_time', y='weighted_share', fill='telework_time', title='Telework Time for workers on weekdays', xlabel='Telework Hours', ylabel='Share of Weighted Workers')
```

label workers with telework time group, number of trips
```{r}

workers_day_trips<-workers_trips%>%
  group_by(person_id,telework_time)%>%
  summarize(count_trips=n())%>%
  right_join(workers_day, by=c('person_id'))%>%  ## get all days whether or not they have work trips
  mutate(count_trips=replace_na(count_trips,0), weighted_people=replace_na(person_adult_weight_2021.y, 0))%>%
   #fill in the days for people that have no work 
  mutate(trip_ct_grp=ifelse(count_trips>0, 'has work trips', 'no work trips'))
 
  
 



```
aggregate
```{r}
work_trips_summary<-workers_day_trips%>%
  group_by(telework_time.y, trip_ct_grp)%>%
  summarise(raw_count=n(), weighted_count=sum(weighted_people))%>%
  mutate(perc_with_work_trip= raw_count/sum(raw_count), perc_with_work_trip_weighted=weighted_count/sum(weighted_count))%>%filter(trip_ct_grp=='has work trips')%>%
  mutate(telework_time=factor(telework_time.y, levels= c('0 hours', 'Less than 1 hour', '1-6 hours', 'More than 6 hours' )))



```


```{r}
static_column_chart(work_trips_summary, x='telework_time', y='perc_with_work_trip_weighted', fill='telework_time', title='Telework Time vs Presence of 1 or more work trips, for workers on weekdays (weighted)', xlabel='Telework Hours', ylabel='Percent of Workers Having One or More Work Trips')
```
```{r }
workers_day_trips_1<-workers_trips%>%
  group_by(person_id,telework_time)%>%
  summarize(count_trips=n(), sum_trip_weights=sum(trip_adult_weight_2021))%>%
  right_join(workers_day, by=c('person_id'))%>%  ## get all days whether or not they have work trips
  mutate(count_trips=replace_na(count_trips,0), weighted_trips=replace_na(sum_trip_weights, 0))
```

```{r}
workers_day_trips_mean<-workers_day_trips_1%>%group_by(telework_time.y)%>%
  summarize(sum_weighted_trips=sum(weighted_trips), sum_weighted_people=sum(person_adult_weight_2021.x))%>%
  mutate(mean_weighted_trips=sum_weighted_trips/sum_weighted_people)%>%
  mutate(telework_time=factor(telework_time.y, levels= c('0 hours', 'Less than 1 hour', '1-6 hours', 'More than 6 hours' )))
```


```{r}

static_column_chart(workers_day_trips_mean, x='telework_time', y='mean_weighted_trips', fill='telework_time', title='Mean Number of Work Trips vs Telework Time for workers on weekdays (weighted)', xlabel='Telework Hours', ylabel='Mean Number of Work Trips', est='number', dec=2)

```
