---
title: "R Notebook"
output: html_notebook
---

1. get hhts data
2. get acs tract data
3. get rgs census tracts (or block groups?)

```{r rmarkdown setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, 
                      warning=FALSE, 
                      message=FALSE,
                      fig.align = "center"
                      # out.width = '50%'
                      ) # formatting
setwd("C:/Joanne_PSRC/data_science/travel-studies/2021/analysis_in_progress/rgcs_vehicle_ownership")

# connect to script with functions
source("rgcs_functions.R")

# psrc packages
library(psrc.travelsurvey)
library(psrccensus)
library(psrcplot)
library(psrctrends)
library(tidycensus)

library(tidyverse)
library(stringr)
library(rlang)
library(chron)
library(scales)
library(gridExtra)
library(odbc)
library(DBI)
# library(tidycensus)
# library(htmlwidgets)

install_psrc_fonts()

Sys.setenv(CENSUS_API_KEY = '3fc20d0d6664692c0becc323b82c752408d843d9')
Sys.getenv("CENSUS_API_KEY")
```

# get rgcs tracts and block groups

```{r}
rgc_tracts <- function(cen_year) {
    
    sqlite_connection <- dbConnect(RSQLite::SQLite(), './ctpp_explorer.db')
    tracts_sql<- paste0("select geoid, min([name]) as name from [dbo.v_rgc_tracts] where census_year = ", cen_year, " group by geoid")
    tracts_df <-  dbGetQuery(sqlite_connection, SQL(tracts_sql))
    tracts_df 
}

tracts_2010 <- rgc_tracts(2010) %>%
  mutate(name = case_when(name == "Bellevue" ~ "Bellevue Downtown",
                          name == "Redmond-Overlake" ~ "Redmond Overlake",
                          TRUE~ name))
tracts_2020 <- rgc_tracts(2020) %>%
  mutate(name = case_when(name == "Bellevue" ~ "Bellevue Downtown",
                          name == "Redmond-Overlake" ~ "Redmond Overlake",
                          TRUE~ name))
```
* ISSUE!!!! RGC names not matching!!!
  + "Bellevue" in Elmer, "Bellevue Downtown" in HHTS
  + "Redmond-Overlake" in Elmer, "Redmond Overlake" in HHTS


# Variables we might want to summarize

```{r Variable, echo=TRUE}
hh_vars=c("survey_year",
          "hhid", "sample_county", "final_home_rgcnum", "final_home_is_rgc",
          "final_home_tract10", "final_home_tract20",
          "hhsize", "vehicle_count", "hhincome_broad", "hhincome_detailed", 
          "numadults", "numchildren", "numworkers", "lifecycle",
          "res_dur", "res_type", "res_months",
          "broadband", "offpark", "offpark_cost", "streetpark")

# list of all urban and metro RGCs
urban_metro <- read_csv("urban_metro.csv") %>% select(3,13) %>%
  mutate(name = case_when(name == "Bellevue" ~ "Bellevue Downtown",
                          name == "Redmond-Overlake" ~ "Redmond Overlake",
                          TRUE~ name))
```




Get the data from Elmer.
```{r trip + household data, include=FALSE}
hh_data_17_19<- get_hhts("2017_2019", "h", vars=hh_vars) %>% hh_group_data()
hh_data_17<-    get_hhts("2017", "h", vars=hh_vars) %>%      hh_group_data()
hh_data_19<-    get_hhts("2019", "h", vars=hh_vars) %>%      hh_group_data()
hh_data_21<-    get_hhts("2021", "h", vars=hh_vars) %>%      hh_group_data()

rgcs_tracts_list <- tracts_2010 %>%
  left_join(hh_data_17 %>%distinct(urban_metro, final_home_rgcnum), 
             by = c("name"="final_home_rgcnum"))

hhts_rgc_list <- hh_data_17 %>%distinct(urban_metro, final_home_rgcnum)
```


```{r}
get_acs <- function(year){
  
  if(year<2020){
    rgcs_tracts_list = tracts_2010
  }
  else{
    rgcs_tracts_list = tracts_2020
  }
  
  test_rgc <- get_acs_recs(geography = 'tract',
               table.names = 'B08201',
               years = year,
               acs.type = 'acs1') %>%
    filter(label %in% c(#"Estimate!!Total:",
                        "Estimate!!Total:!!No vehicle available",
                        "Estimate!!Total:!!1 vehicle available",
                        "Estimate!!Total:!!2 vehicles available",
                        "Estimate!!Total:!!3 vehicles available",
                        "Estimate!!Total:!!4 or more vehicles available")) %>%
    mutate(RGC = case_when(GEOID %in% rgcs_tracts_list$geoid~"RGC",
                           !GEOID %in% rgcs_tracts_list$geoid~"Not RGC"),
           urban_metro = case_when(GEOID %in% rgcs_tracts_list[rgcs_tracts_list$urban_metro=="Metro",]$geoid~"Metro",
                                   GEOID %in% rgcs_tracts_list[rgcs_tracts_list$urban_metro=="Urban",]$geoid~"Urban",
                           !GEOID %in% rgcs_tracts_list$geoid~"Not RGC"),
           label2 = case_when(label %in% c("Estimate!!Total:!!1 vehicle available",
                                           "Estimate!!Total:!!2 vehicles available",
                                           "Estimate!!Total:!!3 vehicles available",
                                           "Estimate!!Total:!!4 or more vehicles available")~"1 or more vehicle(s)",
                              label=="Estimate!!Total:!!No vehicle available"~"No vehicle"))
  test_rgc$urban_metro <- factor(test_rgc$urban_metro, levels=c("Metro","Urban","Not RGC")) 
  return(test_rgc)
}

rgc_acs_2017 <- get_acs(2017)
rgc_acs_2019 <- get_acs(2019)
rgc_acs_2021 <- get_acs(2021)

```

