---
title: "telecommute_where_travelbehavior"
author: "suzanne"
date: "2024-07-16"
output: html_document
---

telecommute amount by work location

run telecommute_preprocess first
These are summaries by location
```{r}
library(sf)
```


```{r}
variable_list<-add_variable(variable_list, 'homegeog','person')

value<- c(0,1,2,3,4,5)
label=c('Kitsap', 'Pierce', 'Seattle Outside Downtown', 'Seattle Downtown','Snohomish-King Suburban', 'Bellevue' )
workgeo_val_labels<-data.frame(value, label)
workgeo_val_labels<-workgeo_val_labels%>%mutate(variable='homegeog')%>%
    mutate(group_1_title = NA, group_1_value = NA,
           group_2_title = NA, group_2_value= NA,
           group_3_title = NA, group_3_value = NA)

all_value_labels<-value_labels%>%select(variable, value, label, group_1_title, group_1_value,
                                      group_2_title, group_2_value, group_3_title, group_3_value)
new_value_labels<-rbind(all_value_labels, workgeo_val_labels)
new_value_labels[, val_order := seq_len(nrow(new_value_labels))]
value_labels<-new_value_labels  


```

```{r}
variable_list<-add_variable(variable_list, 'workgeog','person')

value<- c(0,1,2,3,4,5)
label=c('Kitsap', 'Pierce', 'Seattle Outside Downtown', 'Bellevue', 'Seattle Downtown', 'Snohomish-King Suburban' )
workgeo_val_labels<-data.frame(value, label)
workgeo_val_labels<-workgeo_val_labels%>%mutate(variable='workgeog')%>%
    mutate(group_1_title = NA, group_1_value = NA,
           group_2_title = NA, group_2_value= NA,
           group_3_title = NA, group_3_value = NA)

all_value_labels<-value_labels%>%select(variable, value, label, group_1_title, group_1_value,
                                      group_2_title, group_2_value, group_3_title, group_3_value)
new_value_labels<-rbind(all_value_labels, workgeo_val_labels)
new_value_labels[, val_order := seq_len(nrow(new_value_labels))]
value_labels<-new_value_labels  


```
```{r}
variable_list<-add_variable(variable_list, 'work_county','person')

value<- c(0,1,2,3)
label=c('Kitsap', 'Pierce', 'Snohomish', 'King')
workgeo_val_labels<-data.frame(value, label)
workgeo_val_labels<-workgeo_val_labels%>%mutate(variable='work_county')%>%
    mutate(group_1_title = NA, group_1_value = NA,
           group_2_title = NA, group_2_value= NA,
           group_3_title = NA, group_3_value = NA)

all_value_labels<-value_labels%>%select(variable, value, label, group_1_title, group_1_value,
                                      group_2_title, group_2_value, group_3_title, group_3_value)
new_value_labels<-rbind(all_value_labels, workgeo_val_labels)
new_value_labels[, val_order := seq_len(nrow(new_value_labels))]
value_labels<-new_value_labels  


```

```{r}
variable_list<-add_variable(variable_list, 'home_county','hh')

value<- c(0,1,2,3)
label=c('Kitsap', 'Pierce', 'Snohomish', 'King')
workgeo_val_labels<-data.frame(value, label)
workgeo_val_labels<-workgeo_val_labels%>%mutate(variable='home_county')%>%
    mutate(group_1_title = NA, group_1_value = NA,
           group_2_title = NA, group_2_value= NA,
           group_3_title = NA, group_3_value = NA)

all_value_labels<-value_labels%>%select(variable, value, label, group_1_title, group_1_value,
                                      group_2_title, group_2_value, group_3_title, group_3_value)
new_value_labels<-rbind(all_value_labels, workgeo_val_labels)
new_value_labels[, val_order := seq_len(nrow(new_value_labels))]
value_labels<-new_value_labels  


```


```{r}

workers<-workers%>%mutate(workgeog=case_when(
  work_rgcname=='Seattle Downtown' ~ 'Seattle Downtown',
  (work_rgcname!='Seattle Downtown' &work_jurisdiction=='Seattle') ~ 'Seattle Outside Downtown',
  work_jurisdiction=='Bellevue' ~ 'Bellevue',
  ((work_county=='King' &!work_jurisdiction %in% c('Seattle', 'Bellevue'))|work_county=='Snohomish')~'Snohomish-King Suburban',
  .default=work_county
))
```

```{r}


hh<-hh%>%mutate(homegeog=case_when(
  home_rgcname=='Seattle Downtown'~ 'Seattle Downtown',
  (home_rgcname!='Seattle Downtown' & home_jurisdiction=='Seattle') ~ 'Seattle Outside Downtown',
   home_jurisdiction=='Bellevue' ~ 'Bellevue',
  ((home_county=='King' &!home_jurisdiction %in% c('Seattle', 'Bellevue'))|home_county=='Snohomish')~'Snohomish-King Suburban',
  .default=home_county
))
```


```{r}

workers_hh<-merge(workers, hh, by='hh_id')
workers_hh<-workers_hh%>%mutate(workgeog=
                          if_else(telecommute_status=='Fully At Home' , homegeog,workgeog))%>%
  filter(workgeog %in%c('Bellevue Downtown','Kitsap', 'Pierce', 'Seattle Outside Downtown', 'Seattle Downtown', 'Snohomish-King Suburban', 'Bellevue'))%>%mutate(workrgc_name=
                          if_else(telecommute_status=='Fully At Home' , home_rgcname,work_rgcname))%>%
  mutate(work_county=if_else(telecommute_status=='Fully At Home', home_county, work_county ))

workers_hh<-workers_hh%>%mutate(survey_year=survey_year.x)
```


```{r}

worker_list<-list( person=workers_hh)

```

```{r}
#some how a duplicate snuck into the variable list not sure how
variable_list<-variable_list%>%distinct(variable, .keep_all=TRUE)
```





```{r}

telecommute_workgeo_all<- summarize_weighted(hts_data= worker_list,
                               summarize_var = 'telecommute_status',
                               summarize_by = c('survey_year', 'workgeog'),
                               id_cols=c('person_id'),
                               wt_cols=c('person_weight'),
                               wtname= 'person_weight'
                               )

```


```{r}

telecommute_workgeo_all<-telecommute_workgeo_all$summary$wtd%>%filter(survey_year=='2023')%>%mutate(moe=prop_se*1.645)%>%mutate(telecommute_status=factor(telecommute_status, levels=c('Fully In Person', 'Hybrid', 'Fully At Home')))%>%
  mutate(workgeog=factor(workgeog, levels=c('Kitsap', 'Pierce','Snohomish-King Suburban', 'Seattle Outside Downtown', 'Bellevue','Seattle Downtown')))
  

```
                                                                                                                                                                                                    
```{r}                                                                                               
static<-static_bar_chart(telecommute_workgeo_all, x='prop', y='workgeog', fill='telecommute_status', pos='stack') + theme(axis.text.x=element_text(size=16), axis.text.y=element_text(size=16),legend.text = element_text(size=16), axis.title.y=element_text(size=20), axis.title.x=element_text(size=20))+
   scale_y_continuous(labels = scales::percent_format(scale = 100), limits=c(0,1))

static

write.csv(telecommute_workgeo_all,'telecommute_summary_workgeog.csv')

```
```{r}                                                                                               
static<-static_bar_chart(telecommute_workgeo_all, x='prop', y='workgeog', fill='telecommute_status', moe='moe') + theme(axis.text.x=element_text(size=16), axis.text.y=element_text(size=16),legend.text = element_text(size=16), axis.title.y=element_text(size=20), axis.title.x=element_text(size=20))+
   scale_y_continuous(labels = scales::percent_format(scale = 100), limits=c(0,1))

static

write.csv(telecommute_workgeo_all,'telecommute_summary_workgeog.csv')

```


```{r}

telecommute_workgeo_all<- summarize_weighted(hts_data= worker_list,
                               summarize_var = 'telecommute_status',
                               summarize_by = c('survey_year', 'work_county'),
                               id_cols=c('person_id'),
                               wt_cols=c('person_weight'),
                               wtname= 'person_weight'
                               )

```


```{r}

telecommute_workcounty_all<-telecommute_workgeo_all$summary$wtd%>%filter(survey_year=='2023')%>%mutate(moe=prop_se*1.645)%>%mutate(telecommute_status=factor(telecommute_status, levels=c('Fully In Person', 'Hybrid', 'Fully At Home')))%>%
  mutate(work_county=factor(work_county, levels=c('Kitsap', 'Pierce','Snohomish', 'King')))

```
                                                                                                                                                                                                    
```{r}                                                                                               
static<-static_bar_chart(telecommute_workcounty_all, x='prop', y='work_county', fill='telecommute_status', pos='stack') + theme(axis.text.x=element_text(size=16), axis.text.y=element_text(size=16),legend.text = element_text(size=16), axis.title.y=element_text(size=20), axis.title.x=element_text(size=20))+
   scale_y_continuous(labels = scales::percent_format(scale = 100), limits=c(0,1))

static

write.csv(telecommute_workcounty_all,'telecommute_summary_workcounty.csv')

```

```{r}

telecommute_homegeo_all<- summarize_weighted(hts_data= worker_list,
                               summarize_var = 'telecommute_status',
                               summarize_by = c('survey_year', 'homegeog'),
                               id_cols=c('person_id'),
                               wt_cols=c('person_weight'),
                               wtname= 'person_weight'
                               )

```
```{r}

telecommute__homegeo_all<-telecommute_homegeo_all$summary$wtd%>%filter(survey_year=='2023')%>%mutate(moe=prop_se*1.645)%>%mutate(telecommute_status=factor(telecommute_status, levels=c('Fully In Person', 'Hybrid', 'Fully At Home')))%>%
  mutate(homegeog=factor(homegeog, levels=c('Kitsap', 'Pierce','Snohomish-King Suburban', 'Seattle Outside Downtown', 'Bellevue', 'Seattle Downtown')))%>%drop_na()
  

```
                                                                                                                                                                                                    
```{r}                                                                                               
static<-static_bar_chart(telecommute__homegeo_all, x='prop', y='homegeog', fill='telecommute_status', pos='stack') + theme(axis.text.x=element_text(size=16), axis.text.y=element_text(size=16),legend.text = element_text(size=16), axis.title.y=element_text(size=20), axis.title.x=element_text(size=20))+
   scale_y_continuous(labels = scales::percent_format(scale = 100), limits=c(0,1))

static

write.csv(telecommute__homegeo_all,'telecommute_summary_homegeog.csv')

```

