---
title: "telecommute_workdistrict"
author: "suzanne"
date: "2024-07-18"
output: html_document
---
```{r setup, include=FALSE}
library(data.table)
library(stringr)
library(travelSurveyTools)
library(psrcelmer)
library(dplyr)
library(psrcplot)
library(tidyverse)
library(sf)
source('../survey-23-preprocess.R')
```

run telecommute_july23.Rmd First
```{r}
workers_hh<-merge(workers, hh, by ='hh_id')
workers_hh_nawork<-workers_hh%>%filter(survey_year.x=='2023')%>%mutate(work_lng=if_else(telecommute_status=='Fully At Home', home_lng, work_lng))%>%
  mutate(na_work=if_else(is.na(work_lng), 'NAWorkLng', 'HasWorkLng'))

count_nas<-workers_hh_nawork%>%group_by(na_work)%>%summarize(count=n(), workers=sum(person_weight))

                                                            
count_nas                                                            
                                                             

```


```{r}
worker_geo<-workers_hh%>%mutate(work_lng=if_else(telecommute_status=='Fully At Home', home_lng, work_lng))%>%
  mutate(work_lat=if_else(telecommute_status=='Fully At Home', home_lat, work_lat))%>%
  filter(!is.na(work_lng))%>%
  st_as_sf(coords=c('work_lng','work_lat'), crs=4326)
```


```{r}
sf_use_s2(FALSE)


districts.lyr <- st_read_elmergeo('soundcast_districts')

worker_district<-st_join( worker_geo,districts.lyr, join=st_intersects, left=TRUE)%>%mutate(workdistrict=district)
```
```{r}
variable_list<-add_variable(variable_list, 'workdistrict','person')
```

```{r}

value<- c(1,2,3,4,5,6,7,8,9,10,11)
label=c('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11')
tele_val_labels<-data.frame(value, label)
tele_val_labels<-tele_val_labels%>%mutate(variable='workdistrict')%>%
    mutate(group_1_title = NA, group_1_value = NA,
           group_2_title = NA, group_2_value= NA,
           group_3_title = NA, group_3_value = NA)

all_value_labels<-value_labels%>%select(variable, value, label, group_1_title, group_1_value,
                                      group_2_title, group_2_value, group_3_title, group_3_value)
new_value_labels<-rbind(all_value_labels, tele_val_labels)
new_value_labels[, val_order := seq_len(nrow(new_value_labels))]
value_labels<-new_value_labels  

```


```{r}
variable_list<-add_variable(variable_list, 'homedistrict','person')
```

```{r}

value<- c(1,2,3,4,5,6,7,8,9,10,11)
label=c('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11')
tele_val_labels<-data.frame(value, label)
tele_val_labels<-tele_val_labels%>%mutate(variable='homedistrict')%>%
    mutate(group_1_title = NA, group_1_value = NA,
           group_2_title = NA, group_2_value= NA,
           group_3_title = NA, group_3_value = NA)

all_value_labels<-value_labels%>%select(variable, value, label, group_1_title, group_1_value,
                                      group_2_title, group_2_value, group_3_title, group_3_value)
new_value_labels<-rbind(all_value_labels, tele_val_labels)
new_value_labels[, val_order := seq_len(nrow(new_value_labels))]
value_labels<-new_value_labels  

```

```{r pressure, echo=FALSE}
worker_district<-data.table(worker_district)
worker_district<-worker_district%>%mutate(workdistrict=as.character(district))%>%mutate(survey_year=survey_year.x)%>%select(-c(survey_year.x, survey_year.y))

```

```{r}
workers_hh<-merge(worker_district, hh, by ='hh_id')

worker_geo<-workers_hh%>%
  filter(!is.na(home_lng.x))%>%
  st_as_sf(coords=c('home_lng.x','home_lat.x'), crs=4326)
```


redo analysis at the home level


```{r}
worker_district<-st_join( worker_geo,districts.lyr, join=st_intersects, left=TRUE)%>%mutate(homedistrict=district.y)
```



```{r pressure, echo=FALSE}
worker_districthomework<-data.table(worker_district)
worker_districthomework<-worker_district%>%mutate(homedistrict=as.character(homedistrict))%>%mutate(survey_year=survey_year.x)
worker_districthomework<-data.table(worker_districthomework)
worker_list<-list(person=worker_districthomework)
```


```{r}
#some how a duplicate snuck into the variable list not sure how
variable_list<-variable_list%>%distinct(variable, .keep_all=TRUE)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
telecommute_district<- summarize_weighted(hts_data= worker_list,
                               summarize_var = 'telecommute_status',
                               summarize_by = c('homedistrict', 'workdistrict', 'survey_year'),
                               id_cols=c('person_id'),
                               wt_cols=c('person_weight'),
                               wtname= 'person_weight'
                               )

```
```{r}
psrc_colors$eleven=c(psrc_colors$pgnobgy_10,  "#4a0048")

telecommute_district<-telecommute_district$summary$wtd%>%filter(survey_year=='2023')
                                                                                                   
static<-static_facet_column_chart(telecommute_district, y='prop', x='telecommute_status', fill='homedistrict', facet='workdistrict', color="psrc_colors$eleven") + theme(axis.text.x=element_text(size=16), axis.text.y=element_text(size=16),legend.text = element_text(size=16), axis.title.y=element_text(size=20), axis.title.x=element_text(size=20))

static

write.csv(telecommute_district, 'telecommute_summary_homedistrictworkdistrict.csv')

```



