---
title: "Seattle mode share analysis for pedestrian plan
author: "suzanne"
date: '2022-09-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
request- pedestrian data for Seattle safety plan

## read in shape file with geographies

```{r }
library(sf)
library(dplyr)
library(psrc.travelsurvey)
library(leaflet)
library(tidyr)
library(ggplot2)
library(raster)
library(ggspatial)
library(RColorBrewer)
library(lubridate)
library(scales)
```


Read in the travel survey data and do some work to clean up modes and times of day.
```{r}
mode_geo_df_17_19<-get_hhts('2017_2019', "t", vars= c('trip_id','main_mode', 'mode_simple','d_puma10'))%>%filter(d_puma10 %in% c(11601, 11602, 11603, 11604, 11605))

mode_geo_df_21<-get_hhts('2021', "t", vars= c('trip_id','main_mode', 'mode_simple','d_puma10'))%>%filter(d_puma10 %in% c(11601, 11602, 11603, 11604, 11605))

```

```{r}
seattle_dest_trips_by_mode_17_19<-hhts_count(mode_geo_df_17_19, group_vars=c('mode_simple'),spec_wgt='trip_weight_2017_2019_v2021')


seattle_dest_trips_by_mode_17_19_adult<-hhts_count(mode_geo_df_17_19, group_vars=c('mode_simple'),spec_wgt='trip_weight_2017_2019_v2021_adult')


seattle_dest_trips_by_mode_21<-hhts_count(mode_geo_df_21, group_vars=c('mode_simple'),spec_wgt='trip_weight_2021_ABS_Panel_adult')

write.csv(seattle_dest_trips_by_mode_17_19, 'seattle_all_trips_mode.csv')
write.csv(seattle_dest_trips_by_mode_17_19_adult, 'seattle_all_trips_mode_adult.csv')
write.csv(seattle_dest_trips_by_mode_21, 'seattle_all_trips_mode_21.csv')

```

