---
title: "prep for shiny trends app"
author: "suzanne"
date: "2024-03-27"
output: html_document
---



```{r setup, include=FALSE}
library(data.table)
library(stringr)
library(travelSurveyTools)
library(psrcelmer)
library(dplyr)
library(psrcplot)
library(tidyverse)
source('..\survey-23-preprocess.R')
```



```{r }
hh<- get_query(sql= "select  *
                from HHSurvey.v_households_labels")


person<- get_query(sql= "select *
                from HHSurvey.v_persons_labels")
                

trip<- get_query(sql= "select *
                from HHSurvey.v_trips_labels")
setDT(hh)
setDT(person)
setDT(trip)
```

## Read in Codebook
```{r pressure, echo=FALSE}
cb_path = str_glue("C:/GitHub/travel-studies/2023/summary/shiny/PSRC_Codebook_2023_for_shiny")

variable_list = readxl::read_xlsx(cb_path, sheet = 'variable_list')
value_labels = readxl::read_xlsx(cb_path, sheet = 'value_labels')

setDT(variable_list)
setDT(value_labels)
```

## Set IDs as characters
TO DO: functionalize convert all ids to characters, or store as characters upfront
```{r}

hh[, hh_id:=as.character(hh_id)]
person[, hh_id:=as.character(hh_id)]
day[, hh_id:=as.character(hh_id)]
trip[, hh_id := as.character(hh_id)]

person[, person_id := as.character(person_id)]
day[, person_id := as.character(person_id)]
trip[, person_id := as.character(person_id)]

day[, day_id := as.character(day_id)]
trip[, day_id := as.character(day_id)]

trip[, trip_id := as.character(trip_id)]
hh <- hh%>%mutate(survey_year=as.character(survey_year))
person <- person%>%mutate(survey_year=as.character(survey_year))
day <- day%>%mutate(survey_year=as.character(survey_year))
trip <- trip%>%mutate(survey_year=as.character(survey_year))
```


```{r}
hts_data = list(hh = hh,
                person = person,
                day = day,
                trip = trip)



ids = c('hh_id', 'person_id', 'day_id', 'trip_id')

wts = c('hh_weight', 'person_weight', 'day_weight', 'trip_weight')
```

# tab 1 content, one variable by survey year

loop over every variable in the variable_list
```{r}
make summary_out_df
for every variable in the variables_list{}
new_summary <- summarize_weighted(hts_data= hts_data,
                               summarize_var = %variable%,
                               summarize_by = 'survey_year',
                               id_cols= ids,
                               wt_cols=wts,
                               wtname='trip_weight'
                               )

summary_out_df<-rbind(summary)
```

```{r}
write out summaries to csv summary_trend
```

# tab 2 content, cross tabs for 2023

```{r}
filter data to 2023
```


loop over every variable in the variable_list
```{r}
make summary_out_df
for every variable i in the variables list
    for every variable i in the variables_list{}
new_summary <- summarize_weighted(hts_data= hts_data,
                               summarize_var = variable i,
                               summarize_by = variable j,
                               id_cols= ids,
                               wt_cols=wts,
                               wtname='trip_weight'
                               )

summary_out_df<-rbind(summary)
```

```{r}
write out summaries to csv summary_crosstab
```

