---
title: "residential displacement'
author: "suzanne"
date: "2024-09-27"
output: html_document
---
reading in libraries I usually need
```{r , include=FALSE}
library(psrc.travelsurvey)
library(travelSurveyTools)
library(data.table)
library(dplyr)
library(psrcplot)
library(stringr)
library(sf)
library(psrcelmer)
library(forcats)
```

looking at residential displacement trend

```{r}
demo_summary_vars<-c('age', 'disability_person', 'education', 'employment','gender', 'industry',
               'hhincome_broad', 'home_county','home_lat', 'home_lng','hh_race_category','home_rgcname',
               'numadults', 'numchildren', 'numworkers','res_type', 'rent_own','sexuality', 'hh_race_category_2',
               'student', 'vehicle_count')
prev_res_factors<-c('res_dur', 'prev_res_factors_housing_cost', 'prev_res_factors_income_change', 'prev_res_factors_forced','prev_res_factors_community_change', 'prev_home_wa' )


all_vars<-c(demo_summary_vars, prev_res_factors)
               

```

```{r}
hts_data <- get_psrc_hts(survey_vars = all_vars)

```

```{r}
hh<-hts_data$hh
hh_geo<-hh%>%
  st_as_sf(coords=c('home_lng','home_lat'), crs=4326)
```

#redo analysis with regional geographies
```{r}
regional.geogs<-st_read_elmergeo('REGIONAL_GEOGRAPHIES_evw')
```



```{r}
sf_use_s2(FALSE)
hh_reg_geog<-st_join(regional.geogs, hh_geo, join=st_intersects)%>%filter(!is.na(hh_id))

hh<-left_join(hh, hh_reg_geog, by='hh_id', suffix=c('','_geog'))%>%
  mutate(class_desc=if_else(is.na(class_desc), "Outside Urban Growth Area", class_desc))%>%
  mutate(home_loc= case_when(class_desc=='CitiesTowns' ~ 'Cities and Towns',
                             class_desc=='HCT' ~ 'High Capacity Transit',
                             class_desc=='UU' ~ 'Urban Unincorporated',
                             TRUE ~ class_desc
    
  ))%>%mutate(home_loc=factor(home_loc))
  
```
```{r}
# variable_list<variable_list<-mutate(is_checkbox = 0)
#          shared_name = variable),
#          day = ifelse(variable %in% c("hhincome_broad", "home_county","numchildren", "numworkers", "numadults", "hhsize_simple"),1,day)

```


```{r}
hts_data$hh<-hh
```


```{r}
res_dur<-psrc_hts_stat(hts_data, "hh", c('survey_year','res_dur'), incl_na=TRUE)
```

2023: 306 Missing Response
no missing previous years???
```{r}
res_dur_hh_check<-res_dur%>%group_by(survey_year)%>%summarize(tot_hh=sum(est))
res_dur_hh_check
```

```{r}
static<-static_line_chart(res_dur, y='prop', x='survey_year', fill='res_dur')
static
```
```{r}
hts_data$hh<-hts_data$hh%>%mutate(res_dur5 =
                                    case_when(
                                      ((is.na(res_dur)) |(res_dur=='Missing Response')) ~ "Missing",
                                      res_dur %in% c('Less than a year', 'Between 1 and 2 years', 'Between 2 and 3 years', 'Between 3 and 5 years') ~ '5 years or less',
                                      .default = 'More than 5 years')
                                      )
```

```{r}
prev_home_wa_res_dur<-psrc_hts_stat(hts_data, "hh", c('survey_year','prev_home_wa','res_dur5'), incl_na=TRUE)
```

filter to hhs who answered the question
```{r}
hts_data$hh<-hts_data$hh%>%filter(res_dur5=='5 years or less' & prev_home_wa=='Yes, previous home was in Washington')

```

```{r}
housing_cost<-psrc_hts_stat(hts_data, "hh", c('survey_year','prev_res_factors_housing_cost'), incl_na=TRUE)
```

```{r}
hts_data$hh<-hts_data$hh%>%mutate(displaced=if_else((prev_res_factors_community_change=='Selected'|prev_res_factors_housing_cost=='Selected'|prev_res_factors_income_change=='Selected'|prev_res_factors_forced=='Selected'), 'displaced', 'not displaced'))
```

```{r}
hts_data$hh <- mutate(hts_data$hh,
                      hh_race_category_2= case_when(hh_race_category=="AANHPI non-Hispanic"|
                                                      hh_race_category=="Black or African American non-Hispanic"|
                                                      hh_race_category=="Hispanic"|
                                                      hh_race_category=="Some Other Races non-Hispanic" ~ "POC",
                                                    TRUE~hh_race_category))
```

```{r}
displacement_summary<-psrc_hts_stat(hts_data, "hh", c('survey_year','displaced'), incl_na=TRUE)
```

```{r}
forced_summary_race<-psrc_hts_stat(hts_data, "hh", c('survey_year','hh_race_category_2', 'res_dur', 'prev_res_factors_forced'), incl_na=TRUE)
```


```{r}
forced_summary_race1<-psrc_hts_stat(hts_data, "hh", c('survey_year','hh_race_category', 'res_dur', 'prev_res_factors_forced'), incl_na=TRUE)
```
