---
title: "test-new-package"
author: "suzanne"
date: "2024-09-27"
output: html_document
---
reading in libraries I usually need
```{r , include=FALSE}
library(psrc.travelsurvey)
library(travelSurveyTools)
library(data.table)
library(dplyr)
library(psrcplot)
library(stringr)
```


I'm going to analyze sexuality and travel behavior data as a test case-won't be able to do a multi-year comparision though. So after that I'll do a summary of transit access modes.

```{r}
demo_summary_vars<-c('age', 'disability_person', 'education', 'employment','gender', 'industry',
               'hhincome_broad', 'home_county','home_lat', 'home_lng','hh_race_category','home_rgcname',
               'numadults', 'numchildren', 'numworkers','res_type', 'rent_own','sexuality',
               'student', 'vehicle_count')
travel_summary_vars<-c('bike_freq', 'benefits_3', 'dest_purpose', 'commute_freq', 'commute_mode',
                       'mode_characterization', 'mode_acc', 'transit_freq', 'tnc_freq','telecommute_freq','walk_freq','workplace')

all_vars<-c(demo_summary_vars, travel_summary_vars)
               

```

```{r}
hts_data <- get_psrc_hts(survey_vars = all_vars)

```

```{r}
```


```{r}
hts_data<-hts_data%>%hts_bin_sexuality()%>%hts_bin_age()
```

I realized I need a different categorization, recode the prefer not to answer to NA, so that we don't summarize them
```{r}
hts_data$person<-hts_data$person%>%
  mutate(sexuality_bin4=case_when(sexuality=='Prefer not to answer' ~ NA,
                                  str_detect(sexuality_bin3, 'gay') ~'Gay/Don\'t Know/and Other',
                                 .default=sexuality_bin3))

```

```{r}
sexuality_age<-psrc_hts_stat(hts_data, "person", c('age_bin5','sexuality_bin4'), incl_na=FALSE)%>%
  filter(survey_year=='2023')%>% # only started asking in 2023%>%
filter(age_bin5!='Under 18 Years')

    
   
```

```{r}
static<-static_column_chart(sexuality_age, y='prop', x='age_bin5', fill='sexuality_bin4')
static
```

```{r}
sexuality_mode<-psrc_hts_stat(hts_data, "trip", c('sexuality_bin4','mode_characterization'), incl_na=FALSE)%>%
  filter(survey_year=='2023')%>%# only started asking in 2023%>%
mutate()

    
   
```

```{r}
static<-static_column_chart(sexuality_mode, y='prop', x='mode_characterization', fill='sexuality_bin4', moe='prop_moe')
static
```

