---
title: "Mode and Income"
editor: visual
format: 
  html:
    mainfont: Poppins
    toc: true
    warning: false
    echo: false
    fig-width: 4.5
    fig-asp: .618
---

```{r setup}
library(tidyverse)
library(psrc.travelsurvey)
library(psrcplot)
library(scales)
library(gt)
install_psrc_fonts()
```

```{r}

files <- c("data.R", "functions.R")

invisible(
lapply(files, function(f) {
  source(f)
  # source(here::here("Analysis", "care-giving", f))
})
)

```

::: panel-tabset
## \$50,000

```{r}
mode_share_income(income = "income_50", geog = "Region") |> 
  gt() |>
  tab_spanner_delim(delim = ".") |>
  cols_hide(c(dest_loc, care_purpose_cat)) |>
  cols_align(align = "left",
             columns = c(3)
  )
```

## \$75,000

```{r}
mode_share_income("income_75", geog = "Region")|> 
  gt() |>
  tab_spanner_delim(delim = ".") |>
  cols_hide(c(dest_loc, care_purpose_cat)) |>
  cols_align(align = "left",
             columns = c(3)
  )
```

## \$100,000

```{r}
mode_share_income("income_100", geog = "Region")|> 
  gt() |>
  tab_spanner_delim(delim = ".") |>
  cols_hide(c(dest_loc, care_purpose_cat)) |>
  cols_align(align = "left",
             columns = c(3)
  )
```
:::

## Under \$50k, \$50k-\$100k, \$100k or more

Driving is the predominant mode of transportation for care trips. Those who earn under \$50,000 are using transit more than those who earn over \$50,000 across survey years.

```{r}
msi_df <- mode_share_income_set_b(geog = "Region")$long  |> 
  mutate(income_comp = factor(income_comp, levels = c("Under $50,000", "$50,000-$99,999", "$100,000 or more")))

```

```{r}
#| out-width: "100%"
#| fig-align: "center"

msi_df |> 
  ggplot() +
  geom_col(aes(x = as.character(survey_year), y = prop, fill = mode_class_5)) +
  facet_wrap(~income_comp, strip.position = "bottom") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = psrc_colors$pognbgy_5) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        panel.spacing = unit(0, "cm"),
        legend.position = "bottom",
        strip.text = element_text(face = "bold")) +
  labs(x = NULL,
       y = NULL)

```

```{r}

mode_share_income_set_b(geog = "Region")$wide|>
  gt() |>
  tab_spanner_delim(delim = ".") |>
  cols_hide(c(dest_loc, care_purpose_cat)) |>
  cols_align(align = "left",
             columns = c(3)
)
```

## Under \$50k and \$50k or More

```{r}
msi50bin_df <- mode_share_income_set_c(geog = "Region")$long |> 
  mutate(income_50 = factor(income_50, levels = c("Under $50,000", "$50,000 or more")))
```

```{r}
#| out-width: "100%"
#| fig-align: "center"

msi50bin_df |> 
  ggplot() +
  geom_col(aes(x = as.character(survey_year), y = prop, fill = mode_class_5)) +
  facet_wrap(~income_50, strip.position = "bottom") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = psrc_colors$pognbgy_5) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        panel.spacing = unit(0, "cm"),
        legend.position = "bottom",
        strip.text = element_text(face = "bold")) +
  labs(x = NULL,
       y = NULL)

```

```{r}

mode_share_income_set_c(geog = "Region")$wide|>
  gt() |>
  tab_spanner_delim(delim = ".") |>
  cols_hide(c(dest_loc, care_purpose_cat)) |>
  cols_align(align = "left",
             columns = c(3)
)
```

