---
title: "model shopping trips"
output:
  html_document:
    df_print: paged
---



```{r }
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(ggplot2)
library(psrcplot)
library(forcats)
library(odbc)
library(DBI)
library(tidyr)
library(tidycensus)
library(psrcslides)
library(officer)
library(DBI)
library(foreign)
library(ggplot2)
library(MASS)
library(Hmisc)
library(reshape2)
install_psrc_fonts()
```

```{r}
 elmer_connect<-DBI::dbConnect(odbc::odbc(),
                 driver = "ODBC Driver 17 for SQL Server",
                 server = "AWS-PROD-SQL\\Sockeye",
                 database = "Elmer",
                 trusted_connection = "yes",
                 port = 1433)
  


```


```{r}
trip_vars<-c('mode_1', 'mode_simple','dest_purpose_cat', 'origin_purpose_cat', 'trip_path_distance', 'household_id', 'age_category', 'daynum', 'sample_source', 'hhgroup' )
household_vars<-c('vehicle_count',  "hhincome_broad",  'hhincome_detailed', 'final_home_is_rgc', 'hhsize', 'household_id', 'lifecycle', 'sample_source', 'hhgroup', 'final_home_tract10', 'hh_race_apoc', 'numworkers', 'numchildren', 'numadults')

```


```{r}
trip_data_17<- get_hhts("2017", "t", vars=trip_vars)%>%filter(age_category!='Under 18 years' & hhgroup=='rSurvey')%>%dplyr::select(-trip_weight_2017)
trip_data_19<- get_hhts("2019", "t", vars=trip_vars)%>%filter(age_category!='Under 18 years' & hhgroup=='rSurvey')%>%dplyr::select(-trip_weight_2019)
trip_data_21<- get_hhts("2021", "t", vars=trip_vars)%>%filter(age_category!='Under 18 years' & sample_source=='ABS')%>%dplyr::select(-c(trip_adult_weight_2021, trip_respondent_weight_2021))
trip_data_17_19_21<-rbind(trip_data_17, trip_data_19, trip_data_21)

household_data_17<- get_hhts("2017", "h", vars=household_vars)%>%filter( hhgroup=='rSurvey')%>%dplyr::select(-hh_weight_2017)
household_data_19<- get_hhts("2019", "h", vars=household_vars)%>%filter( hhgroup=='rSurvey')%>%dplyr::select(-hh_weight_2019)
household_data_21<- get_hhts("2021", "h", vars=household_vars)%>%filter(sample_source=='ABS')%>%dplyr::select(-hh_weight_2021)
household_data_17_19_21<-rbind(household_data_17, household_data_19, household_data_21)
```

```{r}
trip_grouping <-function(trip_data){

trip_data<-trip_data%>%
  mutate(simple_purpose=ifelse(dest_purpose_cat=='Home', origin_purpose_cat, dest_purpose_cat))%>%
  mutate(simple_purpose=case_when(simple_purpose=='Work'~ 'Work/School',
                                  simple_purpose=='School'~ 'Work/School',
                                  simple_purpose=='Work-related'~ 'Work/School',
                                  simple_purpose=='Shop'~ 'Shop',
                                  simple_purpose=='Escort'~ 'Errands',
                                  simple_purpose=='Errand/Other'~ 'Errands',
                                  simple_purpose=='Change mode'~ 'Errands',
                                  simple_purpose=='Social/Recreation' ~ 'Social/Recreation',
                                  simple_purpose=='Meal' ~ 'Meal',
                                  simple_purpose=='Home' ~ 'Errands',
                                  is.na(simple_purpose) ~ 'Errands',
                                  TRUE ~ simple_purpose))

trip_data<-trip_data%>%filter(simple_purpose=='Shop')

trip_data_hhid<-trip_data%>% group_by(household_id,daynum)%>%tally()

}

```


```{r}
shop_trips_per_hh_day<-trip_grouping(trip_data_17_19_21)

```

#calculate shopping trips per household id,daynum



```{r}

household_grouping<-function(household_data){
household_data<-household_data%>%mutate(NoVehicles=ifelse(vehicle_count=='0 (no vehicles)', 'No Vehicles', "Has Vehicles")) %>%mutate(hhincome_100= case_when(
    hhincome_broad=="Under $25,000" ~ "Under $75,000",
    hhincome_broad=="$25,000-$49,999" ~ "Under $75,000",
    hhincome_broad=="$50,000-$74,999" ~ "Under $75,000",
    hhincome_broad=='$75,000-$99,999' ~ '$75,000 or more',
    hhincome_broad=='$100,000 or more' ~ '$75,000 or more',
                                 hhincome_broad=='$200,000 or more' ~ '$75,000 or more',
                                 TRUE~hhincome_broad))%>%mutate(hhsize= case_when(hhsize == "1 person" ~ '1 person', 
                                  hhsize == "2 people"  ~ '2 people', 
                                   hhsize == "3 people" ~ '3 people',
                                   hhsize == "4 people" | 
                                  hhsize == "5 people" | 
                                  hhsize == "6 people" | 
                                  hhsize == "7 people" |
                                  hhsize == "8 people" | 
                                  hhsize == "12 people" ~ "4+ people"))%>%
     mutate(lifecycle2= case_when(lifecycle == "Household size > 1, Householder age 65+" | 
                                  lifecycle == "Household size = 1, Householder age 65+"  
                                 ~ '65 years or older', 
                                   lifecycle == "Household size > 1, Householder age 35 - 64" |
                                   lifecycle == "Household size = 1, Householder age 35 - 64"  
                                 ~ '35-64, no kids',
                                   lifecycle == "Household size > 1, Householder under age 35" | 
                                   lifecycle == "Household size = 1, Householder under age 35" 
                                   ~ 'Under 35 years, no kids',
                                   lifecycle == "Household includes children age 5-17" | 
                                   lifecycle == "Household includes children under 5" ~ 'Household has kids'))

household_data$hhincome_100_f=factor(household_data$hhincome_100,levels=c("Under $75,000","$75,000 or more"))

household_data$lifecycle2 =factor(household_data$lifecycle2, levels= c('Household has kids', 'Under 35 years, no kids', '35-64', '65 years or older' ))
household_data
                                  
}
```

```{r}
household_data_17_19_21<-household_grouping(household_data_17_19_21)

```

```{r}

```


```{r}
household_data_17_19_21_shop<-full_join(household_data_17_19_21, shop_trips_per_hh_day, by='household_id')%>%mutate_all(~replace(., is.na(.), 0)) 

household_data_17_19_21_shop%>%group_by(survey)%>%summarise(mean=mean(n,na.rm=TRUE))
```
```{r}
household_data_17_19_21_shop<- household_data_17_19_21_shop%>%mutate(shop_trips=ifelse(n<4, n, 4))%>%mutate(shop_trips=factor(shop_trips,levels=c(0,1, 2, 3,4)))
```

```{r}
ggplot(household_data_17_19_21_shop, aes(x=shop_trips, fill=survey))+geom_histogram(stat='count')


```

```

```




```{r}


survey_a <- list(survey = '2017_2019', label = '2017/2019')
survey_b <- list(survey = '2021', label = '2021')
survey_c <- list(survey = '2017', label = '2017')
survey_d <- list(survey = '2019', label = '2019')

# look at variable names and which years they were collected/documented

# hhts_varsearch("delivery")
# hhts_varsearch("traveldate")
# hhts_varsearch("race")
# hhts_varsearch('income')
# hhts_varsearch('age')
# hhts_varsearch('county')
# hhts_varsearch('home')
# hhts_varsearch('race')



# create variables that would like to group by for analysis of deliveries by household

delivery_type <- c("household_id", "delivery_food_freq", "delivery_grocery_freq", "delivery_pkgs_freq","delivery_work_freq", "deliver_package", 'deliver_work', 'deliver_grocery', 'deliver_food')
days <- c("dayofweek", "typical_day", "daynum", "pernum")


```



```{r, getting survey data with pre-identified variables for households}

# -- How frequently is someone having a delivery made?? 
# -- 2017, 2019, 2017/2019, 2021

# pull datasets from two separate dataframes per year

dsurvey_17 <- get_hhts(survey = survey_c$survey, 
                        level = "d", 
                        vars = c(delivery_type, days)) 



dsurvey_19 <- get_hhts(survey = survey_d$survey, 
                       level = "d", 
                       vars = c(delivery_type, days)) 



dsurvey_1719 <- get_hhts(survey = survey_a$survey, 
                       level = "d", 
                       vars = c(delivery_type, days)) 



dsurvey_21 <- get_hhts(survey = survey_b$survey, 
                       level = "d", 
                       vars = c(delivery_type, days)) 



```



```{r, visualization functions}

# function combining the delivery and household functions into one and ordering income by levels

smp_delivery_combo <- function(data, year) {
  ## rewriting labels of responses to be more concise
  temp_table <- data %>%
    mutate(delivery_food_all= case_when((pernum==1 & is.na(delivery_food_freq) & is.na(deliver_food)) ~ 'No HH Response',
                                        # pernum == 1 removes households where multiple members answered the question
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        delivery_food_freq == "0 (none)"  ~ 'No Delivery',
                                        deliver_food=='No' ~ 'No Delivery',
                                        
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_pkgs_all= case_when((pernum==1 & is.na(delivery_pkgs_freq) & is.na(deliver_package)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        deliver_package=='No' ~ 'No Delivery',
                                        delivery_pkgs_freq == "0 (none)"  ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_grocery_all=case_when((pernum==1 & is.na(delivery_grocery_freq) & is.na(deliver_grocery)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        delivery_grocery_freq == "0 (none)"  ~ 'No Delivery',
                                        deliver_grocery=='No' ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_work_all= case_when((pernum==1 & is.na(delivery_work_freq) & is.na(deliver_work)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        deliver_work =='No' ~ 'No Delivery',
                                        delivery_work_freq == "0 (none)"  ~ 'No Delivery',
                                         TRUE ~ 'Delivery Received'))
  temp_table<-temp_table%>%filter(pernum==1)%>% dplyr::select(survey,household_id,daynum, delivery_pkgs_all, delivery_grocery_all, delivery_food_all )
  temp_table
}
```

```{r, generate datasets}


delivery_17 <- smp_delivery_combo(dsurvey_17, '2017')


delivery_19 <- smp_delivery_combo(dsurvey_19, '2019')




delivery_21 <- smp_delivery_combo(dsurvey_21, '2021')
```

```{r}


delivery_17_19_21<- rbind(delivery_17, delivery_19, delivery_21)
```



```{r}
household_data_17_19_21_shop<- household_data_17_19_21_shop %>%mutate(daynum=ifelse(daynum==0,1,daynum))
```


```{r}
household_data_17_19_21_shop_del<-merge(household_data_17_19_21_shop, delivery_17_19_21, by=c('household_id', 'daynum'))
```


```{r}
shop_model<-polr(formula= delivery_pkgs_all~hhincome_detailed+lifecycle+numworkers+shop_trips, data=household_data_17_19_21_shop_del)
summary(shop_model)
```


```{r}
shop_model<-polr(formula= shop_trips~hhincome_detailed+lifecycle+survey.x+NoVehicles+final_home_is_rgc+delivery_pkgs_all, data=household_data_17_19_21_shop_del)
summary(shop_model)
```

```{r}
library(jtools)
plot_summs(shop_model, scale=TRUE)
```



```{r}
displ_index_data<- 'C:/GitHub/travel-studies/2019/analysis/zero_veh_hh/displacement_risk_estimation.csv'
tract_data<-read.csv(displ_index_data)

```

```{r}
household_data_17_19_21_shop_del$final_home_tract10<-as.character(household_data_17_19_21_shop_del$final_home_tract10)
```


```{r}
hh_shop_tract<-merge(household_data_17_19_21_shop_del, tract_data,by.x='final_home_tract10', by.y='GEOID', all.x=TRUE)
```

```{r}
shop_model<-polr(formula= shop_trips~hhincome_detailed+lifecycle+survey.x+ln_jobs_auto_30+numworkers++delivery_pkgs_all+dist_super, data=hh_shop_tract)
summary(shop_model)
```

```{r}

plot_summs(shop_model, scale=TRUE)
```

```{r}
stargazer(shop_model, type="text")
```


