---
title: "playing around with modeling commute distance"
author: "suzanne"
date: "May 2022"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r global, warning=FALSE, message=FALSE}
library(psrc.travelsurvey)
library(tidyverse)
library(stats)
library(ggplot2)
library(MASS)

```


```{r}


commute_vars <- c('commute_auto_distance', 'commute_auto_time')
demo_vars <-
  c(
    'industry',
    'telecommute_freq',
    'age',
    'gender',
    'jobs_count',
    'employment',
    'worker',
    'workplace',
    'vehicle_count',
    'commute_mode',
    'commute_freq',
    'race_eth_broad',
    'work_lat',
    'work_lng',
    'res_factors_hwy',
    'student',
    'sample_county',
    'commute_dur',
    'work_county',
    'numworkers',
    'numchildren',
    'res_factors_transit',
    'final_home_puma10',
    'hhsize',
    'lifecycle',
    'hhincome_broad',
    'car_share',
    'rent_own',
    'res_dur',
    'res_type',
    'broadband' ,
    'prev_res_factors_more_space',
    'workplace_pre_covid',
    'commute_freq_pre_covid',
    'commute_mode_pre_covid',
    'employment_change_employer',
    'employment_change_location'
  )


all_vars <- get_hhts(
  survey = '2021',
  level = 'p',
  vars = c(commute_vars, demo_vars)
)

```


```{r}
# Who answered the question, who has values filled in?
# how many workers are missing lats ad longs

people_with_work_lats<- all_vars %>% drop_na(work_lat)
# couldn't tag distances if work lats were missing
count(people_with_work_lats)

```
```{r}
people_with_work_dist<- all_vars %>% drop_na(commute_auto_distance)
count(people_with_work_lats)-count(people_with_work_dist)
```
Only 18 missing, seems okay to ignore to get started.
```{r}
ggplot(people_with_work_dist, aes(x=commute_auto_distance))+geom_histogram(binwidth=2)+xlim(0.001, 100)
```

```{r glm, eval=TRUE}
#looks like i should take the log to make it linear
ggplot(people_with_work_dist, aes(x=log(1+commute_auto_distance)))+geom_histogram(binwidth=.2)+xlim(0.001, 15)

```

it looks kind of gaussian now with a long tail, good enough for me
```{r}

# filter out some outliers
people_with_work_dist <- people_with_work_dist%>% filter(commute_auto_distance>0 & commute_auto_distance<200)
```


```{r}
commute_dist_model<-glm(log(1+commute_auto_distance) ~ age + gender+industry+telecommute_freq+jobs_count+vehicle_count+race_eth_broad+
                          student+sample_county+commute_dur+work_county+rent_own+workplace_pre_covid+hhsize+numworkers+commute_freq_pre_covid+commute_mode+ commute_mode_pre_covid+employment_change_employer,data=people_with_work_dist)

step <- stepAIC(commute_dist_model, direction="both")
step$anova # display results 
```
`
```{r}
recommended_commute_dist_model<-glm(log(1+commute_auto_distance) ~ telecommute_freq + vehicle_count + 
    sample_county + commute_dur + work_county + commute_freq_pre_covid + 
    commute_mode,data=people_with_work_dist)

summary(recommended_commute_dist_model)

```
```{r}

recommended_commute_dist_model_industry_race<-glm(log(1+commute_auto_distance) ~ telecommute_freq + vehicle_count + 
    sample_county + commute_dur + work_county + commute_freq_pre_covid + industry+ race_eth_broad+gender+numworkers+
    commute_mode,data=people_with_work_dist)

summ<-summary(recommended_commute_dist_model_industry_race)
summ

```
```
