---
title: "trends in going for walk"
author: "suzanne"
date: "3/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## How frequently do people go for a walk
How has the frequency over going for a walk changed from 2019 to 2021? Did more people go for walks during COVID than before?

The name of the field is mode_freq_3. It's on the persons table. It was asked of all adults.

Question wording:
In the past 30 days, how often have <you/Name> traveled gone for a walk (15 minutes or more)?


```{r get_started}
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(data.table)
library(tidyr)
library(ggplot2)


#get data items and weights, put into srvyr format
#filter for people who do not answer the question, children, non-respondent
walk_2019<-get_hhts(dyear=2019, level="p", vars=c("mode_freq_3","age"))%>% 
filter(age !='Under 5 years old' &
age !='5-11 years' &
age != '12-15 years' &
age !='16-17 years'
)

#look at totals and counts that include nonresponse
   
walk_2019_counts<- hhts_count(df=walk_2019, group_vars="mode_freq_3")
#recalculate shares after removing non-response


#get data items and filter out people who didn't answer the question, children, nonresponse
walk_2021<-get_hhts(dyear=2021, level="p", vars="mode_freq_3")
walk_2021_counts<- hhts_count(df=walk_2021, group_vars="mode_freq_3")

walk_2019_2021_counts<-merge(walk_2019_counts, walk_2021_counts, by='mode_freq_3', suffixes =c('2019', '2021'))





write.table(walk_2019_2021_counts, "clipboard", sep="\t", row.names=FALSE)
walk_2019_2021_counts
```


```{r plot_data}


walk_2019_counts$survey_year=2019
walk_2021_counts$survey_year=2021
walk_2019_2021_counts_long<-rbind(walk_2019_counts,walk_2021_counts)%>%filter(mode_freq_3!='Total')

p<-ggplot(walk_2019_2021_counts_long, aes(x=as.factor(survey_year), y=share, fill=as.factor(mode_freq_3))) +
  geom_bar(stat="identity", position="stack")+coord_flip()
p
```
