---
title: "trends in going for walk, 2019 and 2021"
author: "suzanne"
date: "3/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## How frequently do people go for a walk
How has the frequency over going for a walk changed from 2019 to 2021? Did more people go for walks during COVID than before?

The name of the field is mode_freq_3. It's on the persons table. It was asked of all adults.

Question wording:
In the past 30 days, how often have <you/Name> traveled gone for a walk (15 minutes or more)?

The codebook is saved to:https://github.com/psrc/travel-studies/blob/master/2021/Combined_Codebook_2021_With_Weights.xlsx


```{r get_started}

library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(data.table)
library(tidyr)
library(ggplot2)



commute_mode_2017_2019<-get_hhts(survey='2017_2019', level="p", vars=c("race_eth_broad","commute_mode"))%>%drop_na(c("race_eth_broad","commute_mode"))

   
commute_mode_2017_2019_counts<- hhts_count(df=commute_mode_2017_2019, group_vars=c(  "race_eth_broad", "commute_mode"))



commute_mode_2021<-get_hhts(survey='2021', level="p", vars=c("race_eth_broad","commute_mode"))

   
commute_mode_2021_counts<- hhts_count(df=commute_mode_2021, group_vars=c("race_eth_broad","commute_mode"))


mode_2017_2019_2021_counts<-merge(mode_2017_2019_counts, mode_2021_counts, c("race_eth_broad","commute_mode"),suffixes =c('_2017_2019', '_2021'))



write.table(mode_2017_2019_2021_counts, "clipboard", sep="\t", row.names=FALSE)
mode_2017_2019_2021_counts
```


```{r}
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(data.table)
library(tidyr)
library(ggplot2)



mode_2017_2019<-get_hhts(survey='2017_2019', level="t", vars=c("race_eth_broad", "mode_simple"))

   
mode_2017_2019_counts<- hhts_count(df=mode_2017_2019, group_vars=c("race_eth_broad", "mode_simple"))



mode_2021<-get_hhts(survey='2021', level="t", vars=c("race_eth_broad","mode_simple"))

   
mode_2021_counts<- hhts_count(df=mode_2021, group_vars=c("race_eth_broad","mode_simple"))



mode_2017_2019_2021_counts<-merge(mode_2017_2019_counts, mode_2021_counts, c("race_eth_broad","mode_simple"),suffixes =c('_2017_2019', '_2021'))




write.table(mode_2017_2019_2021_counts, "clipboard", sep="\t", row.names=FALSE)
mode_2017_2019_2021_counts
```


```{r plot_data}


walk_2019_counts$survey_year=2019
walk_2021_counts$survey_year=2021
walk_2019_2021_counts_long<-rbind(walk_2019_counts,walk_2021_counts)%>%filter(mode_freq_3!='Total')

p<-ggplot(walk_2019_2021_counts_long, aes(x=as.factor(survey_year), y=share, fill=as.factor(mode_freq_3))) +
  geom_bar(stat="identity", position="stack")+coord_flip()
p
```
