---
title: "Workplace Location"
author: "Christy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This RMarkdown re-creates the [Workplace Locations Before and During COVID-19](https://www.psrc.org/household-travel-survey-program) graph by Grant using [`psrc.travelsurvey`](https://psrc.github.io/psrc.travelsurvey/) and [`ggiraph`](https://davidgohel.github.io/ggiraph/index.html).

```{r, message=FALSE, warning=FALSE}
library(psrc.travelsurvey)
library(tidyverse)
library(ggiraph)
```

```{r, eval=FALSE, include=FALSE}
library(odbc)
library(DBI)

elmer_conn <- dbConnect(odbc::odbc(),
                        driver = "SQL Server",
                        server = "AWS-PROD-SQL\\Sockeye",
                        database = "Elmer",
                        trusted_connection = "yes"
                        )

db.connect <- function() {
  elmer_connection <- dbConnect(odbc(),
                                Driver = "SQL Server",
                                Server = "AWS-PROD-SQL\\SOCKEYE",
                                Database = "Elmer",
                                # Trusted_Connection = "yes"
                                UID = Sys.getenv("userid"),
                                PWD = Sys.getenv("pwd")
  )
}

read.dt <- function(astring, type = c('table_name', 'sql_query')) {
  elmer_connection <- db.connect()
  if (type == 'table_name') {
    dtelm <- dbReadTable(elmer_connection, SQL(astring))
  } else {
    dtelm <- dbGetQuery(elmer_connection, SQL(astring))
  }
  dbDisconnect(elmer_connection)
  setDT(dtelm)
}

dbtable.person <- "HHSurvey.v_persons"
persons <- read.dt(dbtable.person, 'table_name')
```

```{r}
wgt1 <- "person_weight_2021_ABS_Panel_adult" #combined_adult_weight
wgt2 <- "person_weight_2021_ABS_Panel_respondent" #combined_respondent_weight

wrkr <- get_hhts(dyear = 2021, level = 'p', vars = c('workplace_pre_covid', 'workplace', 'age_category', 'worker')) %>% 
  filter(age_category != 'Under 18 years') %>%
  filter(worker != 'No jobs')

w_cur <- hhts_count(wrkr, spec_wgt = wgt1, group_vars = 'workplace')
w_pre <- hhts_count(wrkr, spec_wgt = wgt2, group_vars = 'workplace_pre_covid')

# custom ordering
w_cur_sel <- w_cur %>% 
  select(workplace, share) %>% 
  mutate(key = c(5, 3, 4, 6, 1, 2, 7),
         period = 'Spring 2021')

w_pre_sel <- w_pre %>% 
  select(workplace_pre_covid, share) %>% 
  mutate(key = c(1, 2, 5, 3, 4, 6, 7),
         period = 'Before March 2020')

# labeling & sort
lookup <- w_cur_sel %>% 
  select(key, locations = workplace) %>% 
  arrange(key) %>% 
  mutate(locations = factor(locations, levels = locations))

# final dataframe
df <- bind_rows(w_cur_sel, w_pre_sel) %>% 
  left_join(lookup, by = 'key') %>% 
  select(-workplace, -workplace_pre_covid) %>% 
  filter(!(key %in% c(6,7)))


```

```{r}
gridline.color <- '#ededed'
background.color <- 'white'
plot.title <- 'Workplace Locations Before and During COVID-19'
plot.caption <- 'Source: 2021 Household Travel Survey'

g <- ggplot(df) +
  geom_col_interactive(aes(locations, 
                           share, 
                           fill = period, 
                           tooltip = paste0(period, ': ', round(share*100, 0), '%')), 
                       position = 'dodge') +
  scale_fill_brewer(palette = "Paired") +
  scale_y_continuous(labels = scales::label_percent()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20)) +
  theme(axis.text.x = element_text(# hjust = 1,
                                   size = 6),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = 'bottom',
        legend.title = element_blank(),
        panel.background = element_rect(fill = background.color),
        panel.grid.major.y = element_line(color = gridline.color),
        panel.grid.minor.y = element_line(color = gridline.color),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.caption = element_text(size=5)
        ) +
  labs(x = NULL,
       y = NULL,
       title = plot.title,
       caption = plot.caption)

girafe(ggobj = g)
```



