---
title: "Walking & Bike/Micromobility"
author: "Grant Gibson"
---

## Trips in the Region

- The total number of trips made on an average weekday has increased since 2023.
- The share of trips made by walking has decreased since 2021, while the share of trips made by bicycle or micromobility devices has increased since 2021.

:::{.panel-tabset}

### Total Trips
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-total-trips >}}

### All Modes
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-all-modes >}}

### Walking
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-walk-total >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-walk-total >}}
:::

### Bike/Micromobility
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-bike-total >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-bike-total >}}
:::

:::


## Walking and Bike/Micromobility Trends

### Household Income

- The share of trips made by walking for households with incomes of $50,000-$99,999 and $100,000-$149,999 has decreased since 2021.
- The share of trips made by walking for households with incomes of $150,000 or greater is similar to 2021.
- The share of trips made by bicycle or micromobility devices for households with incomes less than $100,000 has increased in 2025, especially for households with incomes below $50,000.

:::{.panel-tabset}

#### Walking
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-walk-income >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-walk-income >}}
:::

#### Bike/Micromobility
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-bike-income >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-bike-income >}}
:::

:::

### Age

- The share of trips made by walking for children under 18 has increased since 2023, but has decreased for all other age groups in the same period.
- The share of trips made by bicycle or micromobility devices for people 18-34 years old has increased significantly since 2021.

:::{.panel-tabset}

#### Walking
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-walk-age >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-walk-age >}}
:::

#### Bike/Micromobility
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-bike-age >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-bike-age >}}
:::

:::

### Gender

- The share of trips made by walking for men has decreased since 2023, but for women has increased in the same period.
- The share of trips made by walking and by bicycle or micromobility devices for non-binary/other gender people appears to be much higher than for men and women, but the small sample sizes for that group make it hard to say definitively.

:::{.panel-tabset}

#### Walking
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-walk-gender >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-walk-gender >}}
:::

#### Bike/Micromobility
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-bike-gender >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-bike-gender >}}
:::

:::

### Race/Ethnicity

Due to low sample sizes for race/ethnicity groups other than non-Hispanic white, conclusions about walking and biking are difficult to make. Similar to the region as a whole, shares of trips made by walking for both white people and people of color appear to have decreased in 2025.

### Regional Growth Centers

- The shares of trips made by walking and biking for people who live in RGCs is much higher than for people who live outside of them, although the number of trips made by people living in RGCs is much lower than people living outside of them.
- The share of trips made by walking for people living in RGCs has remained elevated after 2021 while the share for people living outside of RGCs has decreased since 2021.
- The share of trips made by bicycle or micromobility devices for people living in RGCs hs increased significantly since 2021.

:::{.panel-tabset}

#### Walking
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-walk-rgc >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-walk-rgc >}}
:::

#### Bike/Micromobility
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-bike-rgc >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-bike-rgc >}}
:::

:::

### Counties

- The shares of trips made by walking for people living in Kitsap, Pierce, and Snohomish counties has decreased in 2025.

:::{.panel-tabset}

#### Walking
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-walk-county >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-walk-county >}}
:::

#### Bike/Micromobility
:::{layout= "[[4, 6]]"}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#fig-bike-county >}}
{{< embed /Analysis/walk-bike/walk_bike_summary.qmd#tbl-bike-county >}}
:::

:::
