---
title: "hh-race-category"
author: "suzanne"
date: "2024-08-28"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(stringr)
library(travelSurveyTools)
library(psrcelmer)
library(dplyr)
library(psrcplot)
library(tidyverse)
library(psrc.travelsurvey)
source('survey-23-preprocess.R')
```



```{r }
hh<- get_query(sql= "select  household_id as hh_id, hhincome_broad,home_jurisdiction, home_county, hh_weight,vehicle_count, home_rgcname, home_lat, home_lng, survey_year, hh_race_category
                from HHSurvey.v_households_labels")


person<- get_query(sql= "select household_id as hh_id,race_category,
person_id, workplace, telecommute_freq, survey_year, person_weight, gender, age, sexuality, industry,office_available, commute_freq, education, work_lat, work_lng , work_rgcname, work_jurisdiction, work_county
                from HHSurvey.v_persons_labels")
                
day<- get_query(sql= "select person_id, day_id, household_id as hh_id, telework_time, day_weight , survey_year from HHSurvey.v_days_labels")

trip<- get_query(sql= "select trip_id, household_id as hh_id, day_id,
person_id, mode_1, dest_purpose, survey_year, trip_weight, distance_miles, mode_characterization, travelers_total 
                from HHSurvey.v_trips_labels")
setDT(hh)
setDT(person)
setDT(day)
setDT(trip)
```

```{r pressure, echo=FALSE}
cb_path = str_glue("J:/Projects/Surveys/HHTravel/Survey2023/Data/data_published/PSRC_Codebook_2023_v1.xlsx")

variable_list = readxl::read_xlsx(cb_path, sheet = 'variable_list')
value_labels = readxl::read_xlsx(cb_path, sheet = 'value_labels')

setDT(variable_list)
setDT(value_labels)
```

## Set IDs as characters
TO DO: functionalize convert all ids to characters, or store as characters upfront
```{r}

hh[, hh_id:=as.character(hh_id)]
person[, hh_id:=as.character(hh_id)]
day[, hh_id:=as.character(hh_id)]
trip[, hh_id := as.character(hh_id)]

person[, person_id := as.character(person_id)]
day[, person_id := as.character(person_id)]
trip[, person_id := as.character(person_id)]

day[, day_id := as.character(day_id)]
trip[, day_id := as.character(day_id)]

trip[, trip_id := as.character(trip_id)]
hh <- hh%>%mutate(survey_year=as.character(survey_year))
person <- person%>%mutate(survey_year=as.character(survey_year))
day <- day%>%mutate(survey_year=as.character(survey_year))
trip <- trip%>%mutate(survey_year=as.character(survey_year))
```

```{r}
hts_data=list(hh=hh)
hh_race<- summarize_weighted(hts_data= hts_data,
                               summarize_var = 'hh_race_category',
                               summarize_by = 'survey_year',
                               id_cols=c('hh_id'),
                               wt_cols=c('hh_weight'),
                               wtname= 'hh_weight'
                               )

```


```{r, echo=FALSE}
hh_race$summary$wtd

hh_race$summary$unwtd
```

```{r, echo=FALSE}

hh_race_psrc<- psrc_hts_stat(hts_data, analysis_unit='household',c('hh_race_category', 'survey_year'))

hh_race_psrc
```
