---
title: "2024 HTS delivery analysis"
format: 
  html:
    fig-width: 4
    fig-height: 3
    df-print: kable
  

echo: FALSE
warning: FALSE
---


```{r}
library(tidyverse)
library(psrc.travelsurvey)
library(psrcelmer)
library(travelSurveyTools)
library(data.table)
library(psrcplot)
library(sf)
install_psrc_fonts()

source("survey-23-preprocess_JLin.R")
cb_path <- "J:/Projects/Surveys/HHTravel/Survey2023/Data/data_published/PSRC_Codebook_2023_v1.xlsx"
variable_list <- readxl::read_xlsx(cb_path, sheet = 'variable_list')
value_labels = readxl::read_xlsx(cb_path, sheet = 'value_labels')

setDT(variable_list)
setDT(value_labels)
delivery_vars <- c("deliver_food", "deliver_grocery", "deliver_package", "deliver_work", "deliver_other",
                   "deliver_none", "deliver_elsewhere", "deliver_office")

# get data
hh_day_delivery <- readRDS("hh_day_delivery.rds")%>%
  mutate(day_id = paste0(as.character(hh_id),as.character(daynum))) %>% 
  mutate_at(vars(hh_id,day_id,survey_year), ~as.character(.)) %>% 
  mutate_at(vars(deliver_elsewhere:deliver_home_any), ~ifelse(is.na(.),"No",.))
setDT(hh_day_delivery)

hh <- get_query(sql= "select  household_id as hh_id, hhsize, hhincome_broad,home_jurisdiction, home_county, hh_weight,vehicle_count, home_rgcname, home_lat, home_lng, survey_year, hh_race_category
                from HHSurvey.v_households_labels") %>% 
  mutate_at(vars(hh_id,survey_year), ~as.character(.)) %>%
  mutate(hhincome = case_when(hhincome_broad %in% c("Under $25,000","$25,000-$49,999")~'Under $50,000',
                              hhincome_broad %in% c("$50,000-$74,999",
                                                    "$75,000-$99,999")~"$50,000-$100,000",
                              hhincome_broad %in% c("$100,000 or more","$100,000-$199,000",
                                                    "$200,000 or more")~"$100,000+",
                              TRUE~hhincome_broad),
         hhincome2 = case_when(
           hhincome_broad %in% c("Under $25,000","$25,000-$49,999","$50,000-$74,999","$75,000-$99,999")~"Under $100,000",
hhincome_broad %in% c("$100,000 or more","$100,000-$199,000","$200,000 or more")~"$100,000+",
                               TRUE~hhincome_broad),
         hhincome3 = case_when(hhincome_broad %in% c("Under $25,000","$25,000-$49,999")~"Under $50,000",
                               hhincome_broad %in% c("$50,000-$74,999","$75,000-$99,999")~"$50,000-$99,999",
                               hhincome_broad %in% c("$100,000 or more","$100,000-$199,000","$200,000 or more")~"$100,000+",
                               TRUE~hhincome_broad),
         hhincome4 = case_when(hhincome_broad %in% c("$100,000 or more","$100,000-$199,000","$200,000 or more")~"$100,000+",
                               TRUE~hhincome_broad),
         hhincome5 = case_when(hhincome_broad %in% c("Under $25,000","$25,000-$49,999")~"Under $50,000",
                               hhincome_broad %in% c("$50,000-$74,999","$75,000-$99,999")~"$50,000-$99,999",
                               TRUE~hhincome_broad))

setDT(hh)
```
```{r}
#hh_geo<-hh%>%
#  st_as_sf(coords=c('home_lng','home_lat'), crs=4326)
```





```{r}


hh<-hh%>%mutate(homegeog=case_when(
  home_rgcname=='Seattle Downtown'~ 'Seattle Downtown',
  (home_rgcname!='Seattle Downtown' & home_jurisdiction=='Seattle') ~ 'Seattle Outside Downtown',
   home_jurisdiction=='Bellevue' ~ 'Bellevue',
  ((home_county=='King' &!home_jurisdiction %in% c('Seattle', 'Bellevue'))|home_county=='Snohomish')~'Snohomish-King Suburban',
  .default=home_county
))
```


```{r}
variable_list<-add_variable(variable_list, 'hhsize_simple','day')
group_labels<-get_grouped_labels(group_id='group_1', group_name='hhsize_simple')
value_labels<-add_values_code(group_name='hhsize_simple')
hh<-grp_to_tbl(tbl=hh, ungrouped_name='hhsize', grouped_name='hhsize_simple')
```




```{r}
# reading in codebook


my_variable_list <- new_add_variable(variables_dt = variable_list, 
                                     variable_names = c("deliver_home_any","hhincome","hhincome2","hhincome3","hhincome4","hhincome5","hh_day_weight",
                                                        "homegeog", 'rgc_cat_home','hh_telecommute_any'), 
                                     table_name = "day") %>%
  mutate(is_checkbox = ifelse(variable %in% delivery_vars, 0, is_checkbox),
         shared_name = ifelse(variable %in% delivery_vars, variable, shared_name),
         day = ifelse(variable %in% c("hhincome_broad", "home_county", "hhsize_simple"),1,day),
         data_type = ifelse(variable == "hh_day_weight", "numeric", data_type))
hh_variable_list <- new_add_variable(variables_dt = variable_list, 
                                     variable_names = c("hhincome","hhincome2","hhincome3","hhincome4","hhincome5"), 
                                     table_name = "hh")
```

```{r}
person<- get_query(sql= "select household_id as hh_id,race_category,
person_id, workplace, telecommute_freq, survey_year, person_weight, gender, age, sexuality, industry,office_available, commute_freq, education, work_lat, work_lng , work_rgcname, work_jurisdiction, work_county
                from HHSurvey.v_persons_labels")

```


```{r}
variable_list<-add_variable(variable_list, 'telecommute_freq_cond','person')
group_labels<-get_grouped_labels(group_id='group_2', group_name='telecommute_freq_cond')
value_labels<-add_values_code(group_name='telecommute_freq_cond')
person<-grp_to_tbl(tbl=person, ungrouped_name='telecommute_freq', grouped_name='telecommute_freq_cond')
```

define a variable for if any hh member is working at home
```{r}
person<-person%>%mutate(telecommute_status=
        case_when(workplace %in%c('Missing: Skip logic', "Missing: Skip Logic") 
                  ~ 'Not Worker',
                  (is.na(workplace)) ~ 'Not Worker',
                  (workplace=='At home (telecommute or self-employed with home office)' )
                  ~ 'Fully At Home',
                  (telecommute_freq_cond == '1+ days per week')
                  ~'Hybrid',
                  .default = 'Fully In Person'
        )
)
```


```{r}
hh_has_at_home<-person %>%
  group_by(survey_year, hh_id)%>%
  mutate(hh_telecommute=
                 case_when(
                   any(telecommute_status=='Fully At Home',na.rm=TRUE)~"Has Worker At Home",
                   any(telecommute_status=='Hybrid',na.rm=TRUE)~"Has Worker At Home",
                   any(telecommute_status=='Fully In Person',na.rm=TRUE)~"All Workers in Person",
                           TRUE ~ "No Household Workers"
                           ))%>%
  summarize(hh_telecommute_any=first(hh_telecommute))%>%
  mutate(hh_id=as.character(hh_id), survey_year=as.character(survey_year))
```

```{r}
hh<- hh%>%left_join(hh_has_at_home, by =c('hh_id', 'survey_year'))
```


```{r}

hts_hh <- list("hh" = hh)
hts_hh_day <- list("day" = hh_day_delivery %>% left_join(hh, by=c("hh_id","survey_year")))
```



```{r}
delivery_summ_demo_year <- function(delivery_varname,demoname, survey_year='survey_year'){
  # get table
  
    test<- summarize_weighted(hts_data= hts_hh_day,
                               summarize_var = delivery_varname,
                               summarize_by =  c(demoname, survey_year),
                               id_cols=c('day_id'),
                               wt_cols=c('hh_day_weight'),
                               wtname= 'hh_day_weight'
                               )
  
  
   summary<-test$summary$wtd
   summary
}
```

```{r}
variable_list<-my_variable_list
summary<-delivery_summ_demo_year('deliver_package', 'hh_telecommute_any' )%>%filter(deliver_package=='Yes')%>%mutate(hh_telecommute_any=factor(hh_telecommute_any, levels=c('No Household Workers', 'All Workers in Person', 'Has Worker At Home')))

static<-static_column_chart(summary, x='survey_year', fill='hh_telecommute_any', y='prop', dec=0, color='pgnobgy_10')+
  theme(axis.text.x=element_text(size=16), axis.text.y=element_text(size=16),legend.text = element_text(size=16), axis.title.y=element_text(size=20), axis.title.x=element_text(size=20))
static
write.csv(summary, 'deliver_package_telecommute_pkg_year_agg.csv')

```

