---
title: "vmt_model"
author: "suzanne"
date: "2023-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(ggplot2)
library(psrcplot)
library(forcats)
library(odbc)
library(DBI)
library(tidyr)
library(tidycensus)
library(psrcslides)
library(officer)
library(DBI)
library(stargazer)
library(MASS)
library(stats)
library(psrcelmer)
install_psrc_fonts()
```

```{r}
persons_vmt_17_19_21<-read.csv('persons_vmt_17_19_21.csv')
```



```{r}
vmt_model_best_fit_21<-lm(ln_vmt_day ~ employment  + vehicle_count_simple + 
   + numworkers + numchildren + numadults + hhsize+
     grad_school + 
    +workplace  + student + license + telework_time_grp
  +final_home_is_rgc+final_cnty+
    transit_ben + flextime_ben + age+hhsize+flextime_ben+commute_dur+commute_freq+ + rent_own + final_cnty+delivery_pkgs_all+transit_qt_mile+
     log(1 + transit_jobs45/10000) + log(1+jobs_1_mile_walk/10000)+log(1 + jobs_3_mile_bike/10000)+
      log(1+auto_jobs_30min/10000)+ log(1 + dist_park) +log(1+dist_school)+ survey_year+industry, data = persons_vmt_17_19_21)

output<-stargazer(vmt_model_best_fit_21, type='text', out='vmt_model_best_21.txt')

```


```{r}
library(broom)
tidy_vmt<-tidy(vmt_model_best_fit_21)
write.csv(tidy_vmt, 'vmt_model.csv')

```

```{r}
library(jtools)
plot_coeff<-plot_summs(vmt_model_best_fit_21)
```

```{r}
vmt_model_telework_fit_21<-lm(ln_vmt_day ~ telework_time_grp+
     final_cnty + survey_year_factor  , data = persons_vmt_17_19_21)

output<-stargazer(vmt_model_telework_fit_21, type='text', out='vmt_model_best_21.txt')

```


```{r}
library(jtools)
plot_coeff<-plot_summs(vmt_model_best_fit_21)
plot_coeff
```
