---
title: "vmt summary"
output:
  html_document:
    df_print: paged
---




```{r }
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(ggplot2)
library(psrcplot)
library(forcats)
library(odbc)
library(DBI)
library(tidyr)
library(tidycensus)
library(psrcslides)
library(officer)
library(DBI)
library(stargazer)
library(MASS)
library(stats)
install_psrc_fonts()
```


```{r}
mode_vars<-c('mode_1', 'mode_simple')
other_vars<-c('sample_county',  'dest_purpose_cat', 'origin_purpose_cat', 'trip_path_distance', 'household_id',  'travelers_total', 'person_id', 'trip_adjustment_17_19','trip_adjustment_21')

all_vars<-c(mode_vars, other_vars)
household_vars=c('hhid', 'final_home_tract_10', 'hhgroup' )
```


## read in 2017 and 2019 data

```{r}
trip_data_17_19<- get_hhts(survey="2017_2019", level="t", vars=all_vars)
```

```{r}
trip_data_17_19<-trip_data_17_19[,!duplicated(colnames(trip_data_17_19))]
```
# to do - join back to the person data to get people who don't have any driving
```{r}

driving_data<-trip_data_17_19 %>% dplyr::filter(mode_simple=='Drive') %>%
  mutate(trip_path_distance=replace_na(trip_path_distance,0))%>%
  mutate(travelers_total=ifelse(travelers_total>10, 1, travelers_total))%>%
  mutate(travelers_total=ifelse(travelers_total<1, 1, travelers_total))%>%
  mutate(trip_adult_weight_2017_2019=replace_na(trip_adult_weight_2017_2019,0))%>%
  mutate(travelers_total=replace_na(travelers_total,1))%>%
              mutate(vmt= trip_path_distance*trip_adjustment_17_19/travelers_total, trip_weighted_vmt=((trip_path_distance*trip_adult_weight_2017_2019)/travelers_total))
```

```{r}
sum(driving_data$trip_weighted_vmt)
```

```{r}
vmt_per<- driving_data%>%group_by(person_id,daynum)%>%
          summarise(vmt_day=sum(vmt), weighted_vmt_day=sum(trip_weighted_vmt))
sum(vmt_per$weighted_vmt_day)
```

```{r}

persons_list<- get_hhts(survey="2017_2019", level="p", vars=c('person_id', 'numadults', 'employment', 'final_cnty', 'vehicle_count',  "hhincome_broad",  'hhincome_detailed', 'final_home_is_rgc','hhsize', 'lifecycle', 'age_category', 'survey_year', 'rent_own', 'res_dur', 'numworkers', 'numchildren', 'gender_grp', 'jobs_count', 'student', 'education', 'industry', 'license', 'commute_freq', 'commute_dur', 'telecommute_freq', 'work_county', 'benefits_1', 'benefits_2', 'benefits_3', 'benefits_4', 'rent_own', 'commute_auto_distance', 'res_dur','age', 'car_share', 'telecommute_freq_simple'))
persons_list<-persons_list[,!duplicated(colnames(persons_list))]

```

```{r}
persons_vmt<-vmt_per%>%
  mutate(vmt_day=replace_na(vmt_day,0))%>%
  mutate(weighted_vmt_day=replace_na(weighted_vmt_day,0))%>%
  mutate(ln_vmt_day=log(1+vmt_day))%>%
  filter(vmt_day<300)

persons_vmt_detail<-left_join(persons_list,persons_vmt, by='person_id')%>%
  mutate(vmt_day=replace_na(vmt_day,0))%>%
  mutate(weighted_vmt_day=replace_na(weighted_vmt_day,0))%>%
  mutate(ln_vmt_day=log(1+vmt_day))%>%
  filter(vmt_day<200)

```

```{r}
summary(persons_vmt_detail$vmt_day)
summary(persons_vmt_detail$weighted_vmt_day)
ggplot(persons_vmt_detail, aes(ln_vmt_day))+
geom_histogram()+
xlim(0, 10)

ggplot(persons_vmt_detail, aes(vmt_day))+
geom_histogram()
sum(persons_vmt_detail$weighted_vmt_day)
```


```{r}
persons_vmt_new<-persons_vmt_detail%>%
  mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1 day a week", "2 days a week") ~ "1-2 days", 
                                          telecommute_freq %in% c("3 days a week", "4 days a week") ~ "3-4 days", 
                                          telecommute_freq %in% c("5 days a week", "6-7 days a week") ~ "5+ days",
                                          telecommute_freq %in% c("Never", "Not applicable") ~ "Never / None",
                                          !is.na(telecommute_freq) ~ telecommute_freq))%>%
           mutate(transit_ben = ifelse(benefits_3 %in% c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(compressed_ben = ifelse(benefits_2 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(grad_school=ifelse(education=='Graduate/post-graduate degree', 'Graduate degree', 'No graduate degree'))%>%
           mutate(flextime_ben = ifelse(benefits_1 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(oth_ben = ifelse(benefits_4 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(survey_year_factor=as.factor(survey_year))

           

```

```{r}
persons_list<-persons_list%>%mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1 day a week", "2 days a week") ~ "1-2 days", 
                                          telecommute_freq %in% c("3 days a week", "4 days a week") ~ "3-4 days", 
                                          telecommute_freq %in% c("5 days a week", "6-7 days a week") ~ "5+ days",
                                          telecommute_freq %in% c("Never", "Not applicable") ~ "Never / None",
                                          !is.na(telecommute_freq) ~ telecommute_freq))
```


```{r}
vmt_telecommute<-persons_vmt_new%>%group_by(telecommute_freq_new)%>%summarize(total_vmt=sum(weighted_vmt_day))

persons_telecommute<-persons_list%>%group_by(telecommute_freq_new)%>%summarize(total_workers=sum(hh_weight_2017_2019_adult))

vmt_persons_telecommute<- merge(vmt_telecommute, persons_telecommute, by='telecommute_freq_new')

vmt_average<- vmt_persons_telecommute%>%mutate(ave_vmt_per_day=total_vmt/total_workers)
vmt_average
```

```{r}
vmt_commute<-persons_vmt_new%>%group_by(commute_freq)%>%summarize(total_vmt=sum(weighted_vmt_day))

persons_commute<-persons_list%>%group_by(commute_freq)%>%summarize(total_workers=sum(hh_weight_2017_2019_adult))

vmt_persons_commute<- merge(vmt_commute, persons_commute, by='commute_freq')

vmt_average_commute<- vmt_persons_commute%>%mutate(ave_vmt_per_day=total_vmt/total_workers)
vmt_average_commute
```



## read in 2021

```{r}
trip_data_21<- get_hhts(survey="2021", level="t", vars=all_vars)
```

```{r}
trip_data_21<-trip_data_21[,!duplicated(colnames(trip_data_21))]
```
# to do - join back to the person data to get people who don't have any driving
```{r}

driving_data_21<-trip_data_21 %>% dplyr::filter(mode_simple=='Drive') %>%
  mutate(trip_path_distance=replace_na(trip_path_distance,0))%>%
  mutate(travelers_total=ifelse(travelers_total>10, 1, travelers_total))%>%
  mutate(travelers_total=ifelse(travelers_total>10, 1, travelers_total))%>%
  mutate(travelers_total=ifelse(travelers_total<1, 1, travelers_total))%>%
  mutate(trip_adult_weight_2021=replace_na(trip_adult_weight_2021, 0))%>%
  mutate(travelers_total=replace_na(travelers_total,1))%>%
              mutate(vmt= trip_path_distance/travelers_total, trip_weighted_vmt=((trip_path_distance*trip_adult_weight_2021/travelers_total)))
```

```{r}
sum(driving_data_21$trip_weighted_vmt)
```

```{r}
vmt_per_21<- driving_data_21%>%group_by(person_id,daynum)%>%
          summarise(vmt_day=sum(vmt), weighted_vmt_day=sum(trip_weighted_vmt))
sum(vmt_per_21$weighted_vmt_day)
```

```{r}

persons_list_21<- get_hhts(survey="2021", level="p", vars=c('person_id', 'numadults', 'employment', 'final_cnty', 'vehicle_count',  "hhincome_broad",  'hhincome_detailed', 'final_home_is_rgc','hhsize', 'lifecycle', 'age_category', 'survey_year', 'rent_own', 'res_dur', 'numworkers', 'numchildren', 'gender_grp', 'jobs_count', 'student', 'education', 'industry', 'license', 'commute_freq', 'commute_dur', 'telecommute_freq', 'work_county', 'benefits_1', 'benefits_2', 'benefits_3', 'benefits_4', 'rent_own', 'commute_auto_distance', 'res_dur','age', 'car_share', 'telecommute_freq_simple'))
persons_list_21<-persons_list_21[,!duplicated(colnames(persons_list_21))]

```

```{r}
persons_list_21<-persons_list_21%>%mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1 day a week", "2 days a week") ~ "1-2 days", 
                                          telecommute_freq %in% c("3 days a week", "4 days a week") ~ "3-4 days", 
                                          telecommute_freq %in% c("5 days a week", "6-7 days a week") ~ "5+ days",
                                          telecommute_freq %in% c("Never", "Not applicable") ~ "Never / None",
                                          !is.na(telecommute_freq) ~ telecommute_freq))
```

```{r}


persons_vmt_detail_21<-left_join(persons_list_21,vmt_per_21, by='person_id')%>%
  mutate(vmt_day=replace_na(vmt_day,0))%>%
  mutate(weighted_vmt_day=replace_na(weighted_vmt_day,0))%>%
  mutate(ln_vmt_day=log(1+vmt_day))%>%
  filter(vmt_day<200)

```

```{r}
summary(persons_vmt_detail_21$vmt_day)
summary(persons_vmt_detail_21$weighted_vmt_day)
ggplot(persons_vmt_detail_21, aes(ln_vmt_day))+
geom_histogram()+
xlim(0, 10)

ggplot(persons_vmt_detail_21, aes(vmt_day))+
geom_histogram()
sum(persons_vmt_detail_21$weighted_vmt_day)
```


```{r}
persons_vmt_new_21<-persons_vmt_detail_21%>%
  mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1 day a week", "2 days a week") ~ "1-2 days", 
                                          telecommute_freq %in% c("3 days a week", "4 days a week") ~ "3-4 days", 
                                          telecommute_freq %in% c("5 days a week", "6-7 days a week") ~ "5+ days",
                                          telecommute_freq %in% c("Never", "Not applicable") ~ "Never / None",
                                          !is.na(telecommute_freq) ~ telecommute_freq))%>%
           mutate(transit_ben = ifelse(benefits_3 %in% c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(compressed_ben = ifelse(benefits_2 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(grad_school=ifelse(education=='Graduate/post-graduate degree', 'Graduate degree', 'No graduate degree'))%>%
           mutate(flextime_ben = ifelse(benefits_1 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(oth_ben = ifelse(benefits_4 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(survey_year_factor=as.factor(survey_year))

           

```




```{r}
vmt_telecommute_21<-persons_vmt_new_21%>%group_by(telecommute_freq_new)%>%summarize(total_vmt=sum(weighted_vmt_day))

persons_telecommute_21<-persons_list_21%>%group_by(telecommute_freq_new)%>%summarize(total_workers=sum(person_adult_weight_2021))

vmt_persons_telecommute_21<- merge(vmt_telecommute_21, persons_telecommute_21
                                   , by='telecommute_freq_new')

vmt_average_21<- vmt_persons_telecommute_21%>%mutate(ave_vmt_per_day=total_vmt/total_workers)

```

```{r}
vmt_commute_21<-persons_vmt_new_21%>%group_by(commute_freq)%>%summarize(total_vmt=sum(weighted_vmt_day))

persons_commute_21<-persons_list_21%>%group_by(commute_freq)%>%summarize(total_workers=sum(person_adult_weight_2021))

vmt_persons_commute_21<- merge(vmt_commute_21, persons_commute_21, by='commute_freq')

vmt_average_commute_21<- vmt_persons_commute_21%>%mutate(ave_vmt_per_day=total_vmt/total_workers)
vmt_average_commute_21
```

```{r}
vmt_average$survey_year='2017/2019'
vmt_average_21$survey_year='2021'

vmt_trend<-rbind(vmt_average, vmt_average_21)
vmt_trend<-vmt_trend%>%mutate(survey_year_factor=as.factor(survey_year))%>%drop_na()


```


```{r}
psrcplot::static_bar_chart(t=vmt_trend, y='telecommute_freq_new', x='ave_vmt_per_day', fill='survey_year_factor')
```


```{r}
vmt_average_commute$survey_year='2017/2019'
vmt_average_commute_21$survey_year='2021'

vmt_trend_commute<-rbind(vmt_average_commute, vmt_average_commute_21)
vmt_trend_commute<-vmt_trend_commute%>%mutate(survey_year_factor=as.factor(survey_year))%>%drop_na()


```


```{r}
psrcplot::static_bar_chart(t=vmt_trend_commute, y='commute_freq', x='ave_vmt_per_day', fill='survey_year_factor')
```

