---
title: "modeling vehicle miles traveled"
output:
  html_document:
    df_print: paged
---




```{r }
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(ggplot2)
library(psrcplot)
library(forcats)
library(odbc)
library(DBI)
library(tidyr)
library(tidycensus)
library(psrcslides)
library(officer)
library(DBI)
library(stargazer)
library(MASS)
library(stats)
library(psrcelmer)
install_psrc_fonts()
```

```{r}
persons_vmt<-read.csv('persons_vmt_17_19.csv')
```


```{r}
summary(persons_vmt$vmt_day)
summary(persons_vmt$ln_vmt_day)
ggplot(persons_vmt, aes(ln_vmt_day))+
geom_histogram()+
xlim(0, 10)

ggplot(persons_vmt, aes(vmt_day))+
geom_histogram()
```


```{r}
persons_vmt_new<-persons_vmt%>%mutate(inc100k=case_when(hhincome_broad=='$75,000-$99,999' ~ 'Under 100K',
                                                 hhincome_broad=='$100,000 or more' ~ 'Over 100K',
                                                 hhincome_broad=='Prefer not to answer' ~ 'No Answer',
                                                 hhincome_broad=='$25,000-$49,999' ~ 'Under 100K',
                                                 hhincome_broad=='$50,000-$74,999' ~ 'Under 100K'))%>%
  mutate(vehicle_count_simple= case_when(vehicle_count=substr(vehicle_count,1,1) %in% c("3","4", "5", "6", "7", "8") ~ '3 or more vehicles',
                                         .default = vehicle_count))%>%mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1 day a week", "2 days a week") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("3 days a week", "4 days a week") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("5 days a week", "6-7 days a week") ~ "5+ days",
                                           telecommute_freq %in% c("Never", "Not applicable", "Less than monthly", "A few times per month") ~ "Never or Less than Every Week",
                                          !is.na(telecommute_freq) ~ telecommute_freq))%>%
  mutate(Kitsap_home= ifelse(final_cnty=='Kitsap', 'Kitsap', 'Not Kitsap'))%>%
           mutate(transit_ben = ifelse(benefits_3 %in% c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(compressed_ben = ifelse(benefits_2 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(grad_school=ifelse(education=='Graduate/post-graduate degree', 'Graduate degree', 'No graduate degree'))%>%
           mutate(flextime_ben = ifelse(benefits_1 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(oth_ben = ifelse(benefits_4 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(survey_year_factor=as.factor(survey_year))

           

```

```{r}
smp_delivery_combo <- function(data, year) {
  ## rewriting labels of responses to be more concise
  temp_table <- data %>%
    mutate(delivery_food_all= case_when((pernum==1 & is.na(delivery_food_freq) & is.na(deliver_food)) ~ 'No HH Response',
                                        # pernum == 1 removes households where multiple members answered the question
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        delivery_food_freq == "0 (none)"  ~ 'No Delivery',
                                        deliver_food=='No' ~ 'No Delivery',
                                        
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_pkgs_all= case_when((pernum==1 & is.na(delivery_pkgs_freq) & is.na(deliver_package)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        deliver_package=='No' ~ 'No Delivery',
                                        delivery_pkgs_freq == "0 (none)"  ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_grocery_all=case_when((pernum==1 & is.na(delivery_grocery_freq) & is.na(deliver_grocery)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        delivery_grocery_freq == "0 (none)"  ~ 'No Delivery',
                                        deliver_grocery=='No' ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_work_all= case_when((pernum==1 & is.na(delivery_work_freq) & is.na(deliver_work)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        deliver_work =='No' ~ 'No Delivery',
                                        delivery_work_freq == "0 (none)"  ~ 'No Delivery',
                                         TRUE ~ 'Delivery Received'))
  temp_table
}

```

```{r}
day_vars <- c("dayofweek", "typical_day", "pernum", "telework_time")
delivery_type <- c("household_id", "delivery_food_freq", "delivery_grocery_freq", "delivery_pkgs_freq","delivery_work_freq", "deliver_package", 'deliver_work', 'deliver_grocery', 'deliver_food', 'day_weight_2017_2019')
dsurvey_1719 <- get_hhts(survey = '2017/2019', 
                       level = "d", 
                       vars = c(delivery_type, day_vars))

```

```{r}
dsurvey_1719<-dsurvey_1719[,!duplicated(colnames(dsurvey_1719))]
delivery_1719 <- smp_delivery_combo(dsurvey_1719, '2017/2019')%>%filter(delivery_food_all!='Not Person One, not the responder')%>%
  mutate(telework_time_grp = case_when(is.na(telework_time) ~ NA_character_,
   between(as.numeric(str_replace(telework_time, "^(\\d+) hours? (\\d+).*", "\\1.\\2")), 6.1, 24) ~ "More than 6 hours",
   between(as.numeric(str_replace(telework_time, "^(\\d+) hours? (\\d+).*", "\\1.\\2")), 1, 6) ~ "1-6 hours",
   TRUE ~ "0-1 hour"))%>%mutate(day_weight_2017_2019=replace_na(day_weight_2017_2019,0))
```

```{r}
persons_vmt_new<-left_join(persons_vmt_new, delivery_1719, by=c('household_id'= 'household_id', 'daynum'='daynum'))
```

```{r}
persons_vmt_21<-read.csv('persons_vmt_21.csv')
```


```{r}
summary(persons_vmt_21$vmt_day)
summary(persons_vmt_21$ln_vmt_day)
ggplot(persons_vmt_21, aes(ln_vmt_day))+
geom_histogram()+
xlim(0, 10)
```




```{r}
persons_vmt_new_21<-persons_vmt_21%>%mutate(inc100k=case_when(hhincome_broad=='$75,000-$99,999' ~ 'Under 100K',
                                                 hhincome_broad=='$100,000-$199,000' ~ 'Over 100K',
                                                 hhincome_broad=='$200,000 or more' ~ 'Over 100K',
                                                 hhincome_broad=='Prefer not to answer' ~ 'No Answer',
                                                 hhincome_broad=='$25,000-$49,999' ~ 'Under 100K',
                                                 hhincome_broad=='$50,000-$74,999' ~ 'Under 100K'))%>%
  mutate(vehicle_count_simple= case_when(vehicle_count=substr(vehicle_count,1,1) %in% c("3","4", "5", "6", "7", "8") ~ '3 or more vehicles',
                                         .default = vehicle_count))%>%
  mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1-2 days") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("3-4 days") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("5+ days") ~ "5+ days",
                                          telecommute_freq %in% c("Never / None")  ~ "Never or Less than Every Week",
                                          !is.na(telecommute_freq) ~ telecommute_freq))%>%
  mutate(Kitsap_home= ifelse(final_cnty=='Kitsap', 'Kitsap', 'Not Kitsap'))%>%
           mutate(transit_ben = ifelse(benefits_3 %in% c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(compressed_ben = ifelse(benefits_2 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(grad_school=ifelse(education=='Graduate/post-graduate degree', 'Graduate degree', 'No graduate degree'))%>%
           mutate(flextime_ben = ifelse(benefits_1 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(oth_ben = ifelse(benefits_4 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(survey_year_factor=as.factor(survey_year))


           

```

```{r}
day_vars <- c("dayofweek", "typical_day", "pernum", "telework_time")
delivery_type <- c("household_id", "delivery_food_freq", "delivery_grocery_freq", "delivery_pkgs_freq","delivery_work_freq", "deliver_package", 'deliver_work', 'deliver_grocery', 'deliver_food')
dsurvey_21 <- get_hhts(survey = '2021', 
                       level = "d", 
                       vars = c(delivery_type, day_vars))

```

```{r}
dsurvey_21<-dsurvey_21[,!duplicated(colnames(dsurvey_21))]
delivery_21 <- smp_delivery_combo(dsurvey_21, '2021')%>%filter(delivery_food_all!='Not Person One, not the responder')%>%mutate(telework_time_grp=
                                                                                                                                  case_when(telework_time=='0 hours' ~ '0-1 hour',                                                       telework_time =='Less than 1 hour' ~'0-1 hour',                                                         .default= telework_time))
                                                                                                            
```

```{r}
persons_vmt_new_21<-left_join(persons_vmt_new_21, delivery_21, by=c('household_id'= 'household_id'))

```





```{r}
common_cols <- intersect(colnames(persons_vmt_new), colnames(persons_vmt_new_21))
persons_vmt_17_19_21<-rbind(persons_vmt_new[, common_cols], persons_vmt_new_21[, common_cols])
```


```{r}
table(persons_vmt_17_19_21$survey_year)

persons_vmt_17_19_21%>%group_by(survey_year)%>%summarize(mean_vmt=mean(vmt_day))

```




# https://data.library.virginia.edu/interpreting-log-transformations-in-a-linear-model/




Summarize weighted VMT by weighted characteristic
```{r}
vmt_summary <- function(person_day_df_1, person_weight_name_1,survey_year_1, 
                           person_day_df_2, person_weight_name_2, survey_year_2,
                           group) {
  
  vmt_mean_group_1<-person_day_df_1%>%
    group_by(!!ensym(group))%>%
    summarize(sum_per_weights=sum(!!ensym(person_weight_name_1)), sum_weighted_vmt=sum(weighted_vmt))%>%
    mutate(vmt_mean=sum_weighted_vmt/sum_per_weights)%>%
    mutate(survey_year=survey_year_1)
  
    vmt_mean_group_2<-person_day_df_2%>%
    group_by(!!ensym(group))%>%
    summarize(sum_per_weights=sum(!!ensym(person_weight_name_2)), sum_weighted_vmt=sum(weighted_vmt))%>%
    mutate(vmt_mean=sum_weighted_vmt/sum_per_weights)%>%
    mutate(survey_year=survey_year_2)
    
    vmt_mean_group<-rbind(vmt_mean_group_1, vmt_mean_group_2)%>%
      drop_na()

  return(vmt_mean_group)
}

```

```{r}
person_summary <- function(person_day_df_1, person_weight_name_1,survey_year_1, 
                           person_day_df_2, person_weight_name_2, survey_year_2,
                           group) {
  
  shares_group_1<-person_day_df_1%>%
    group_by(!!ensym(group))%>%
    summarize(sum_per_weights=sum(!!ensym(person_weight_name_1)))%>%
    drop_na()%>%
    mutate(share= sum_per_weights/sum(sum_per_weights))%>%
    mutate(survey_year=survey_year_1)
  
    shares_group_2<-person_day_df_2%>%
    group_by(!!ensym(group))%>%
    summarize(sum_per_weights=sum(!!ensym(person_weight_name_2)))%>%
    drop_na()%>%
    mutate(share= sum_per_weights/sum(sum_per_weights))%>%
    mutate(survey_year=survey_year_2)
    
    shares_group<-rbind(shares_group_1, shares_group_2)
  return(shares_group)
}

```


```{r}
workers_list<-persons_list%>%
  mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1 day a week", "2 days a week") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("3 days a week", "4 days a week") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("5 days a week", "6-7 days a week") ~ "5+ days",
                                           telecommute_freq %in% c("Never", "Not applicable", "Less than monthly", "A few times per month") ~ "Never or Less than Every Week",
                                          !is.na(telecommute_freq) ~ telecommute_freq,
                                          is.na(telecommute_freq) ~ "Not Worker"))%>%filter(telecommute_freq_new!='Not Worker')
  
workers_list_21<-persons_list_21%>%
  mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1-2 days") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("3-4 days") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("5+ days") ~ "5+ days",
                                          telecommute_freq %in% c("Never / None")  ~ "Never or Less than Every Week",
                                          !is.na(telecommute_freq) ~ telecommute_freq,
                                          is.na(telecommute_freq) ~ 'Not Worker'))%>%filter(telecommute_freq_new!='Not Worker')
  

telework_share<-person_summary(workers_list,'hh_weight_2017_2019', '2017/2019',
                            workers_list_21,'person_adult_weight_2021', '2021',
                                  'telecommute_freq_new' )%>%
mutate(telecommute_freq_new=factor(telecommute_freq_new, levels=c("Never or Less than Every Week", "1-4 days per week" ,"5+ days")))%>%
         filter(telecommute_freq_new %in% c("Never or Less than Every Week", "1-4 days per week", "5+ days"))


```

```{r}
static_column_chart(t=telework_share, x='telecommute_freq_new', y='share', fill='survey_year', 
                    xlabel='Telecommute Frequency', ylabel='Share of Workers')+ theme(axis.text.x = element_text(size = 14),axis.text.y = element_text(size = 14)) + theme(axis.title = element_text(size=18))
```

```{r}
employment_vmt<-vmt_summary(persons_vmt_new,'hh_weight_2017_2019_adult', '2017/2019',
                            persons_vmt_new_21,'person_adult_weight_2021.x', '2021',
                                  'employment')%>%filter(employment!='Employed but not currently working (e.g., on leave, furloughed 100%)'
)
```

```{r}
static_column_chart(t=employment_vmt, x='employment', y='vmt_mean', fill='survey_year', 
                    xlabel='Employment Status', ylabel='Vehicle Miles Traveled (mean)')+ theme(axis.text.x = element_text(size = 12),axis.text.y = element_text(size = 12)) + theme(axis.title = element_text(size=12))
```


```{r}
hhgroup_vmt<-vmt_summary(persons_vmt_new,'hh_weight_2017_2019_adult', '2017/2019',
                            persons_vmt_new_21,'person_adult_weight_2021.x', '2021', 
                         'hhgroup')

```





```{r}
telework_time_vmt<-vmt_summary(persons_vmt_new,'hh_weight_2017_2019_adult', '2017/2019',
                            persons_vmt_new_21,'person_respondent_weight_2021.x', '2021',
                                  'telework_time_grp')
```

```{r}
static_column_chart(t=telework_time_vmt, x='telework_time_grp', y='vmt_mean', fill='survey_year', 
                    xlabel='Telework Time', ylabel='Vehicle Miles Traveled (mean)')+ theme(axis.text.x = element_text(size = 12),axis.text.y = element_text(size = 12)) + theme(axis.title = element_text(size=12))
```
this is still not working!!!!
```{r}
delivery_vmt<-vmt_summary(persons_vmt_new,'hh_weight_2017_2019_adult', '2017/2019',
                            persons_vmt_new_21,'person_respondent_weight_2021.x', '2021',
                                  'delivery_pkgs_all')
```

```{r}
static_column_chart(t=delivery_vmt, x='delivery_pkgs_all', y='vmt_mean', fill='survey_year', 
                    xlabel='Packages Delivered', ylabel='Vehicle Miles Traveled (mean)')+ theme(axis.text.x = element_text(size = 12),axis.text.y = element_text(size = 12)) + theme(axis.title = element_text(size=12))
```




```{r}
vehicle_count_vmt<-vmt_summary(persons_vmt_new,'hh_weight_2017_2019_adult', '2017/2019',
                            persons_vmt_new_21,'person_adult_weight_2021.x', '2021',
                                  'vehicle_count_simple')


```


```{r}
telework_vmt<-vmt_summary(persons_vmt_new,'hh_weight_2017_2019_adult', '2017/2019',
                            persons_vmt_new_21,'person_adult_weight_2021.x', '2021',
                                  'telecommute_freq_new')

```

```{r}
static_column_chart(t=vehicle_count_vmt, x='vehicle_count_simple', y='vmt_mean', fill='survey_year', 
                    xlabel='Household Vehicles', ylabel='vehicle miles traveled (mean)')

```


```{r}
telework_vmt<-vmt_summary(persons_vmt_new,'hh_weight_2017_2019_adult', '2017/2019',
                            persons_vmt_new_21,'person_adult_weight_2021.x', '2021',
                                  'telecommute_freq_new')

```

```{r}
static_column_chart(t=vehicle_count_vmt, x='vehicle_count_simple', y='vmt_mean', fill='survey_year', 
                    xlabel='Household Vehicles', ylabel='vehicle miles traveled (mean)')

```
```{r}
static_column_chart(t=telework_vmt, x='telecommute_freq_new', y='vmt_mean', fill='survey_year', 
                    xlabel='Telecommute Frequency', ylabel='Vehicle Miles Traveled (mean)')+ theme(axis.text.x = element_text(size = 14),axis.text.y = element_text(size = 14)) + theme(axis.title = element_text(size=18))
```
```{r}
transitben_vmt<-vmt_summary(persons_vmt_new,'hh_day_weight_revised', '2017/2019',
                            persons_vmt_new_21,'person_respondent_weight_2021', '2021',
                                  'benefits_3')

```

```{r}
static_column_chart(t=transitben_vmt, x='benefits_3', y='vmt_mean', fill='survey_year', 
                    xlabel='Transit Pass Work Benefit', ylabel='vehicle miles traveled (mean)')


```





```{r}
vmt_model_best_fit_21<-lm(ln_vmt_day ~ employment  + vehicle_count_simple + 
    gender_grp + numworkers + numchildren + numadults + grad_school + 
    student + license + telework_time_grp + Kitsap_home +
    transit_ben + flextime_ben + compressed_ben + rent_own + 
     log(1 + jobs_transit/10000) + log(1 + 
    pharmacy) + log(1 + park) +workplace + 
    log(1 + pharmacy)+ survey_year_factor  , data = persons_vmt_17_19_21)

output<-stargazer(vmt_model_best_fit_21, type='text', out='vmt_model_best_21.txt')

```


```{r}
library(broom)
tidy_vmt<-tidy(vmt_model_best_fit_21)
write.csv(tidy_vmt, 'vmt_model.csv')

```

```{r}
library(jtools)
plot_coeff<-plot_summs(vmt_model_best_fit_21)
```

```{r}
vmt_model_telework_fit_21<-lm(ln_vmt_day ~ telework_time_grp+
     final_cnty + survey_year_factor  , data = persons_vmt_17_19_21)

output<-stargazer(vmt_model_telework_fit_21, type='text', out='vmt_model_best_21.txt')

```


```{r}
library(jtools)
plot_coeff<-plot_summs(vmt_model_best_fit_21)
plot_coeff
```
