---
title: "modeling vehicle miles traveled"
output:
  html_document:
    df_print: paged
---




```{r }
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(ggplot2)
library(psrcplot)
library(forcats)
library(odbc)
library(DBI)
library(tidyr)
library(tidycensus)
library(psrcslides)
library(officer)
library(DBI)
library(stargazer)
library(MASS)
library(stats)
install_psrc_fonts()
```


```{r}
mode_vars<-c('mode_1', 'mode_simple')
other_vars<-c('sample_county',  'dest_purpose_cat', 'origin_purpose_cat', 'trip_path_distance', 'household_id',  'travelers_total', 'person_id')

all_vars<-c(mode_vars, other_vars)
household_vars=c('hhid', 'final_home_tract_10', 'hhgroup' )
```

## read in 2017 and 2019 data

```{r}
trip_data_17_19<- get_hhts(survey="2017_2019", level="t", vars=all_vars)
```

```{r}
trip_data_17_19<-trip_data_17_19[,!duplicated(colnames(trip_data_17_19))]
```
# calculate vmt, this is unweighted
```{r}

driving_data<-trip_data_17_19 %>% dplyr::filter(mode_simple=='Drive') %>%
  mutate(travelers_total=ifelse(travelers_total>10, 1, travelers_total))%>%
  mutate(travelers_total=ifelse(travelers_total<1, 1, travelers_total))%>%
              mutate(vmt= trip_path_distance/travelers_total)
```
# vmt per day, unweighted
```{r}
vmt_per<- driving_data%>%group_by(person_id, daynum)%>%
          summarize(vmt_day=sum(vmt))%>%
          filter(row_number()==1)
```
# get person demographics
```{r}

persons_list<- get_hhts(survey="2017_2019", level="p", vars=c('person_id', 'numadults', 'employment', 'final_cnty', 'vehicle_count',  "hhincome_broad",  'hhincome_detailed', 'final_home_is_rgc','hhsize', 'lifecycle', 'age_category', 'survey_year', 'rent_own', 'res_dur', 'numworkers', 'numchildren', 'gender_grp', 'jobs_count', 'student', 'education', 'industry', 'license', 'commute_freq', 'commute_dur', 'telecommute_freq', 'work_county', 'benefits_1', 'benefits_2', 'benefits_3', 'benefits_4', 'rent_own', 'commute_auto_distance', 'res_dur','age', 'car_share', 'telecommute_freq_simple', 'workplace', 'commute_freq'))
persons_list<-persons_list[,!duplicated(colnames(persons_list))]

```


```{r}
hh_tract<- get_hhts(survey='2017_2019', level = 'h', vars= c( 'final_home_tract10', 'hhgroup'))

persons_tract<-left_join(persons_list,hh_tract,by='household_id')%>%mutate(tract_char= as.character(final_home_tract10))

```

```{r}
t_access<- read.csv('transportation_accessibility.csv')%>%mutate(tract_char=as.character(geoid_nm))

persons_access<- left_join(persons_tract,t_access, by='tract_char')
```

```{r}
persons_vmt<-left_join(persons_access,vmt_per, by='person_id')%>%
  mutate(vmt_day=replace_na(vmt_day,0))%>%
  mutate(ln_vmt_day=log(1+vmt_day))%>%
  filter(vmt_day<300)

```

```{r}
summary(persons_vmt$vmt_day)
summary(persons_vmt$ln_vmt_day)
ggplot(persons_vmt, aes(ln_vmt_day))+
geom_histogram()+
xlim(0, 10)

ggplot(persons_vmt, aes(vmt_day))+
geom_histogram()
```


```{r}
persons_vmt_new<-persons_vmt%>%mutate(inc100k=case_when(hhincome_broad=='$75,000-$99,999' ~ 'Under 100K',
                                                 hhincome_broad=='	100,000 or more' ~ 'Over 100K',
                                                 hhincome_broad=='Prefer not to answer' ~ 'No Answer',
                                                 hhincome_broad=='$25,000-$49,999' ~ 'Under 100K',
                                                 hhincome_broad=='$50,000-$74,999' ~ 'Under 100K'))%>%
  mutate(vehicle_count_simple= case_when(vehicle_count=substr(vehicle_count,1,1) %in% c("3","4", "5", "6", "7", "8") ~ '3 or more vehicles',
                                         .default = vehicle_count))%>%
  mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1 day a week", "2 days a week") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("3 days a week", "4 days a week") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("5 days a week", "6-7 days a week") ~ "5+ days",
                                          telecommute_freq %in% c("Never", "Not applicable") ~ "Never / None",
                                          !is.na(telecommute_freq) ~ telecommute_freq))%>%
  mutate(Kitsap_home= ifelse(final_cnty=='Kitsap', 'Kitsap', 'Not Kitsap'))%>%
           mutate(transit_ben = ifelse(benefits_3 %in% c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(compressed_ben = ifelse(benefits_2 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(grad_school=ifelse(education=='Graduate/post-graduate degree', 'Graduate degree', 'No graduate degree'))%>%
           mutate(flextime_ben = ifelse(benefits_1 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(oth_ben = ifelse(benefits_4 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(survey_year_factor=as.factor(survey_year))

           

```

```{r}

survey_a <- list(survey = '2017_2019', label = '2017/2019')
survey_b <- list(survey = '2021', label = '2021')
delivery_type <- c("household_id", "delivery_food_freq", "delivery_grocery_freq", "delivery_pkgs_freq","delivery_work_freq", "deliver_package", 'deliver_work', 'deliver_grocery', 'deliver_food')
days <- c("dayofweek", "typical_day", "pernum")
hh_data <- c('hh_race_category')
```

```{r}
smp_delivery_combo <- function(data, year) {
  ## rewriting labels of responses to be more concise
  temp_table <- data %>%
    mutate(delivery_food_all= case_when((pernum==1 & is.na(delivery_food_freq) & is.na(deliver_food)) ~ 'No HH Response',
                                        # pernum == 1 removes households where multiple members answered the question
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        delivery_food_freq == "0 (none)"  ~ 'No Delivery',
                                        deliver_food=='No' ~ 'No Delivery',
                                        
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_pkgs_all= case_when((pernum==1 & is.na(delivery_pkgs_freq) & is.na(deliver_package)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        deliver_package=='No' ~ 'No Delivery',
                                        delivery_pkgs_freq == "0 (none)"  ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_grocery_all=case_when((pernum==1 & is.na(delivery_grocery_freq) & is.na(deliver_grocery)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        delivery_grocery_freq == "0 (none)"  ~ 'No Delivery',
                                        deliver_grocery=='No' ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_work_all= case_when((pernum==1 & is.na(delivery_work_freq) & is.na(deliver_work)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        deliver_work =='No' ~ 'No Delivery',
                                        delivery_work_freq == "0 (none)"  ~ 'No Delivery',
                                         TRUE ~ 'Delivery Received'))
  temp_table
}

```

```{r}
dsurvey_1719 <- get_hhts(survey = survey_a$survey, 
                       level = "d", 
                       vars = c(delivery_type, days, hh_data))
```




```{r}
dsurvey_1719<-dsurvey_1719[,!duplicated(colnames(dsurvey_1719))]
delivery_1719 <- smp_delivery_combo(dsurvey_1719, '2017/2019')%>%filter(delivery_food_all!='Not Person One, not the responder')
```

```{r}
persons_vmt_del1719<-left_join(persons_vmt_new, delivery_1719, by=c('household_id'= 'household_id', 'daynum'='daynum'))
```


## read in 2021 data

```{r}
trip_data__21<- get_hhts(survey="2021", level="t", vars=all_vars)
```

```{r}
trip_data__21<-trip_data__21[,!duplicated(colnames(trip_data__21))]
```
# to do - join back to the person data to get people who don't have any driving
```{r}

driving_data_21<-trip_data__21 %>% dplyr::filter(mode_simple=='Drive') %>%
  mutate(travelers_total=ifelse(travelers_total>10, 1, travelers_total))%>%
  mutate(travelers_total=ifelse(travelers_total<1, 1, travelers_total))%>%
              mutate(vmt= trip_path_distance/travelers_total)
```

```{r}
vmt_per_21<- driving_data_21%>%group_by(person_id, daynum)%>%
          summarize(vmt_day=sum(vmt))%>%
          filter(row_number()==1)
```

```{r}

persons_list_21<- get_hhts(survey="2021", level="p", vars=c('person_id', 'numadults', 'employment', 'final_cnty', 'vehicle_count',  "hhincome_broad",  'hhincome_detailed', 'final_home_is_rgc','hhsize', 'lifecycle', 'age_category', 'survey_year', 'rent_own', 'res_dur', 'numworkers', 'numchildren', 'gender_grp', 'jobs_count', 'student', 'education', 'industry', 'license', 'commute_freq', 'commute_dur', 'telecommute_freq', 'work_county', 'benefits_1', 'benefits_2', 'benefits_3', 'benefits_4', 'rent_own', 'commute_auto_distance', 'res_dur','age', 'car_share', 'telecommute_freq_simple', 'workplace'))


```
```{r}
persons_list_21<-persons_list_21[,!duplicated(colnames(persons_list_21))]
```

```{r}
hh_tract_21<- get_hhts(survey='2021', level = 'h', vars= c( 'final_home_tract10'))

persons_tract_21<-left_join(persons_list_21,hh_tract_21,by='household_id')%>%mutate(tract_char= as.character(final_home_tract10))

```

```{r}
t_access_21<- read.csv('transportation_accessibility.csv')%>%mutate(tract_char=as.character(geoid_nm))

persons_access_21<- left_join(persons_tract_21,t_access_21, by='tract_char')
```

```{r}
persons_vmt_21<-left_join(persons_access_21,vmt_per_21, by='person_id')%>%
  mutate(vmt_day=replace_na(vmt_day,0))%>%
  mutate(ln_vmt_day=log(1+vmt_day))%>%
  filter(vmt_day<300)

```

```{r}
summary(persons_vmt_21$vmt_day)
summary(persons_vmt_21$ln_vmt_day)
ggplot(persons_vmt_21, aes(ln_vmt_day))+
geom_histogram()+
xlim(0, 10)
```




```{r}
persons_vmt_new_21<-persons_vmt_21%>%mutate(inc100k=case_when(hhincome_broad=='$75,000-$99,999' ~ 'Under 100K',
                                                 hhincome_broad=='	100,000 or more' ~ 'Over 100K',
                                                 hhincome_broad=='Prefer not to answer' ~ 'No Answer',
                                                 hhincome_broad=='$25,000-$49,999' ~ 'Under 100K',
                                                 hhincome_broad=='$50,000-$74,999' ~ 'Under 100K'))%>%
  mutate(vehicle_count_simple= case_when(vehicle_count=substr(vehicle_count,1,1) %in% c("3","4", "5", "6", "7", "8") ~ '3 or more vehicles',
                                         .default = vehicle_count))%>%
  mutate(telecommute_freq_new = case_when(telecommute_freq %in% c("1 day a week", "2 days a week") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("3 days a week", "4 days a week") ~ "1-4 days per week", 
                                          telecommute_freq %in% c("5 days a week", "6-7 days a week") ~ "5+ days",
                                          telecommute_freq %in% c("Never", "Not applicable") ~ "Never / None",
                                          !is.na(telecommute_freq) ~ telecommute_freq))%>%
  mutate(Kitsap_home= ifelse(final_cnty=='Kitsap', 'Kitsap', 'Not Kitsap'))%>%
           mutate(transit_ben = ifelse(benefits_3 %in% c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(compressed_ben = ifelse(benefits_2 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(grad_school=ifelse(education=='Graduate/post-graduate degree', 'Graduate degree', 'No graduate degree'))%>%
           mutate(flextime_ben = ifelse(benefits_1 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
           mutate(oth_ben = ifelse(benefits_4 %in%  c('Offered, and I use', 'Offered and I don\'t use'), 'Offered', 'Not Offered or do not know'))%>%
  mutate(survey_year_factor=as.factor(survey_year))


           

```

```{r}
dsurvey_21 <- get_hhts(survey = survey_b$survey, 
                       level = "d", 
                       vars = c(delivery_type, days, hh_data))
```




```{r}
dsurvey_21<-dsurvey_21[,!duplicated(colnames(dsurvey_21))]
delivery_21 <- smp_delivery_combo(dsurvey_21, '2021')%>%filter(delivery_food_all!='Not Person One, not the responder')
```

```{r}
persons_vmt_del21<-left_join(persons_vmt_new_21, delivery_21, by=c('household_id'= 'household_id', 'daynum'='daynum'))
```




```{r}
common_cols <- intersect(colnames(persons_vmt_del1719), colnames(persons_vmt_del21))
persons_vmt_17_19_21<-rbind(persons_vmt_del1719[, common_cols], persons_vmt_del21[, common_cols])
```


```{r}
table(persons_vmt_17_19_21$survey_year)

persons_vmt_17_19_21%>%group_by(survey_year)%>%summarize(mean_vmt=mean(vmt_day))
```




# https://data.library.virginia.edu/interpreting-log-transformations-in-a-linear-model/




```{r}
vmt_model_best_fit_21<-lm(ln_vmt_day ~ employment + inc100k + vehicle_count_simple + 
    gender_grp + numworkers + numchildren + numadults + grad_school + 
    student + license + telecommute_freq_simple + Kitsap_home + commute_freq+
    transit_ben + flextime_ben + compressed_ben + rent_own + 
     log(1 + jobs_transit/10000) + log(1 + 
    pharmacy) + log(1 + park) +workplace + 
    log(1 + pharmacy)+ survey_year_factor  , data = persons_vmt_17_19_21)

output<-stargazer(vmt_model_best_fit_21, type='text', out='vmt_model_best_21.txt')

```


```{r}
library(broom)
tidy_vmt<-tidy(vmt_model_best_fit_21)
write.csv(tidy_vmt, 'vmt_model.csv')

```

```{r}
library(jtools)
plot_coeff<-plot_summs(vmt_model_best_fit_21)
```

```{r}
vmt_model_small_fit_21<-lm(ln_vmt_day ~ employment + inc100k + vehicle_count_simple +  numworkers + numadults +  license + telecommute_freq_simple + Kitsap_home + commute_freq+transit_ben + flextime_ben + compressed_ben + rent_own + log(1 + jobs_transit/10000) + log(1 + pharmacy) +
     log(1 + jobs_auto/10000) +workplace + log(1 + pharmacy)+ survey_year_factor  , data = persons_vmt_17_19_21)


```

```{r}
tidy_vmt<-tidy(vmt_model_small_fit_21)
write.csv(tidy_vmt, 'vmt_small_model.csv')

```

```{r}
library(jtools)
plot_coeff<-plot_summs(vmt_model_small_fit_21)
plot_coeff
```


```{r}
vmt_model__small_interest_21<-lm(ln_vmt_day ~ employment+vehicle_count_simple+license+commute_freq+telecommute_freq_simple +transit_ben + compressed_ben + flextime_ben + 
 delivery_pkgs_all+  survey_year_factor+ log(1 + jobs_auto/10000) + 
    log(1 + jobs_transit/10000)  , data = persons_vmt_17_19_21)

output<-stargazer(vmt_model__small_interest_21, type='text', out='vmt_model_var_intest.txt')
summ(vmt_model__small_interest_21)
plot_summs(vmt_model__small_interest_21)
```
```{r}
vmt_model_telecommute<-lm(ln_vmt_day ~telecommute_freq_simple* commute_freq+survey_year_factor+hhgroup  , data = persons_vmt_17_19_21)

output<-stargazer(vmt_model_telecommute, type='text', out='vmt_model_telecommute.txt')
outputs2<-summ(vmt_model_telecommute)
write.csv(outputs2, 'vmt_model_telecommute.csv')
```
```{r}
vmt_model_telecommute<-lm(ln_vmt_day ~ workplace+ survey_year_factor  , data = persons_vmt_17_19_21)

output<-stargazer(vmt_model_telecommute, type='text', out='vmt_model_telecommute.txt')
outputs2<-summ(vmt_model_telecommute)
write.csv(outputs2, 'vmt_model_telecommute.csv')
```