

```{r}

driving_trip<-trip %>% dplyr::filter(mode_characterization %in% c('Drive HOV2', 'Drive SOV', 'Drive HOV3+')) %>%
  filter(!is.na(travelers_total) | !is.na(distance_miles)| 
          !(travelers_total=='Missing Response'))%>% # remove missing data
  mutate(travelers_total_num=as.numeric(substring(travelers_total,1,1)))%>%
  mutate(travelers_total_num=if_else(is.na(travelers_total_num), 1,travelers_total_num))%>%
  mutate(travelers_total_num=
            ifelse(travelers_total_num>=5, 7, travelers_total_num)) # have to make some assumption for 5+
           


```

# this will account for the adjustments on trips as well.

```{r}
driving_trip<-left_join(driving_trip, hh, by='hh_id')
driving_trip<-driving_trip%>%mutate(weighted_vmt=distance_miles*trip_weight/travelers_total_num)%>%
  mutate(weighted_vmt=ifelse(is.na(weighted_vmt), 0, weighted_vmt))%>%
  mutate(non_adj_vmt=(distance_miles/travelers_total_num))%>%
  mutate(unweighted_vmt=(distance_miles*trip_weight)/(travelers_total_num*hh_weight))%>%
  mutate(unweighted_vmt=ifelse(is.na(unweighted_vmt), 0, unweighted_vmt))%>%
  filter(distance_miles<200)

```

```{r}
driving_day<-driving_trip%>%group_by(day_id)%>%summarize(total_vmt=sum(weighted_vmt), vmt_est_day=sum(unweighted_vmt))
```


```{r}
all_days<-left_join(day,driving_day, by='day_id' )%>%mutate(total_vmt=if_else(is.na(total_vmt), 0, total_vmt))%>%mutate(vmt=if_else(is.na(vmt_est_day), 0, vmt_est_day))%>%filter(day_weight!=0)
```


```{r}
hh_person<-merge(hh, person, by ='hh_id')
```


```{r}
all_days_person<-merge(hh_person, all_days, by ='person_id')%>%filter(vmt<200)
```

```{r}
summary(all_days_person$vmt)
```



```{r}
all_days_person<-all_days_person%>%mutate(ln_vmt=log(vmt+1))
```


```{r}
model<-lm(ln_vmt ~survey_year+hhincome_broad+home_county+work_county+race_category_2023_c+workplace+telecommute_freq+gender,
          data=all_days_person)
summary(model)

```

```{r}
hhincome_broad+race_category+workplace+ age+industry, 
```



