---
title: "changes-checks"
author: "suzanne"
date: "2025-01-23"
output: html_document
---
```{r}
library(psrc.travelsurvey)
library(data.table)
library(dplyr)
library(psrcplot)
library(ggplot2)

# Specify which variables to retrieve
vars <- c("hhsize", "hhincome_broad", "employment", "mode_acc", "origin_purpose", "dest_purpose", "mode_class", "workplace", "telecommute_freq", "mode_characterization")

# Retrieve the data
hts_data <- get_psrc_hts(survey_vars = vars)
```


# mode choice, mode choice income, transit access mode
```{r}
hts_data <- hts_data %>% 
  hts_bin_hhsize()%>%
  hts_bin_income()%>%
  hts_bin_worker()%>%
  hts_bin_mode()%>%
  hts_bin_telecommute_trichotomy()%>%
  hts_bin_transit_mode_acc()
  

```
#careful here- filter 1. to transit trips 2. to transit trips with an access mode    
```{r}
transit_trips<-hts_data$trip%>%filter(mode_class=='Transit')%>%mutate(survey_year=as.integer(survey_year))
hts_data$trip<-transit_trips%>%filter(!is.na(mode_acc))
mode_access<- psrc_hts_stat(hts_data, "trip", c("mode_acc"))%>%mutate(survey_year=as.integer(survey_year))
  

```
        
                          
```{r}
static<-static_column_chart(mode_access, y='prop', x='survey_year', fill='mode_acc', pos='stack' )
static
```
```{r}
transit_trips<-hts_data$trip%>%filter(mode_class=='Transit')%>%mutate(survey_year=as.integer(survey_year))
hts_data$trip<-transit_trips%>%filter(!is.na(mode_acc))
mode_access<- psrc_hts_stat(hts_data, "trip", c("transit_mode_acc"))%>%mutate(survey_year=as.integer(survey_year))
  

```
