---
title: "hhs_trip_rates_hhgroup"
author: "suzanne"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install package
# remotes::install_github('RSGInc/travelSurveyTools', force = TRUE)

library(data.table)
library(stringr)
library(travelSurveyTools)
library(ggplot2)
```
## Read in data

```{r load_data, message=FALSE}

# load in data delivered to RSG 02/01/24 cleaned, unweighted
dt_dir = "J:/Projects/Surveys/HHTravel/Survey2023/Data/data_unweighted_cleaned_to_rsg_020124"

codebook_dir = 'J:/Projects/Surveys/HHTravel/Survey2023/Data/codebook/PSRC_Combined_Codebook_2023_groupings.xlsx'

files = Sys.glob(file.path(dt_dir, "*.csv"))

hts_data = lapply(files, function(fl) {
  
  tbl_name = stringr::str_match(basename(fl), "(.*?).csv")[, 2]
  
  message("Reading ", basename(fl))

    fread(fl)
})

# Assign lowercase names to the list elements
names(hts_data) <- tolower(sapply(files, function(f) stringr::str_match(basename(f), "(.*?).csv")[, 2]))

# order list for data prep
ordered_list = c("household", "person", "day", "trip", "vehicle")
hts_data = hts_data[match(ordered_list, names(hts_data))]

# rename the household data frame
names(hts_data)[1] = 'hh'

# read in the codebook
variable_list = setDT(readxl::read_xlsx(codebook_dir, sheet = 'variable_list_2023'))

value_labels = suppressWarnings(setDT(readxl::read_xlsx(codebook_dir, sheet = 'value_labels_2023')))

# add needed columns to variable list
variable_list[, shared_name := ifelse(
        grepl('--', description_2023),
        sub('_[^_]*$', '', variable), variable)
    ]

variable_list[, is_checkbox := ifelse(grepl('--', description_2023), 1, 0)]

# rename columns in variable_list for data prep
setnames(variable_list, c(
  'hh_final', 
  'person_final',
  'vehicle_final', 
  'day_final', 
  'trip_final', 
  'location_final'),
  c('hh', 'person', 'vehicle', 'day', 'trip', 'location'))

setnames(variable_list, 'data_type_2023', 'data_type')

setnames(variable_list, 'description_2023', 'description')

```

## Households by Sample Group


```{r hh_summaries, message=FALSE}
# hhgroup
prepped_hhgroup = hts_prep_data(summarize_var = 'hhgroup',
                                    summarize_by = NULL,
                                    variables_dt = variable_list,
                                    data = hts_data,
                                    id_cols = c('hhid', 'person_id', 'day_id', 'tripid', 'vehid'),
                                    weighted = FALSE)
  
hhgroup_summary<- hts_summary(prepped_dt = prepped_hhgroup$cat,
                               summarize_var = 'hhgroup',
                               summarize_by = NULL,
                               id_cols = c('hhid', 'person_id', 'day_id', 'tripid', 'vehid'),
                               weighted = FALSE)



# use factorize_df so that final summary includes labels instead of values
sample_group<-factorize_df(df = hhgroup_summary$summary$unwtd,
                              vals_df = value_labels,
                              value_label_colname = 'final_label')
```
```{r}
# hhgroup
prepped_hhgroup = hts_prep_data(summarize_var = 'hhgroup',
                                    summarize_by = NULL,
                                    variables_dt = variable_list,
                                    data = hts_data,
                                    id_cols = c('hhid', 'person_id', 'day_id', 'tripid', 'vehid'),
                                    weighted = FALSE)
  
hhgroup_summary<- hts_summary(prepped_dt = prepped_hhgroup$cat,
                               summarize_var = 'hhgroup',
                               summarize_by = NULL,
                               id_cols = c('hhid', 'person_id', 'day_id', 'tripid', 'vehid'),
                               weighted = FALSE)



# use factorize_df so that final summary includes labels instead of values
sample_group<-factorize_df(df = hhgroup_summary$summary$unwtd,
                              vals_df = value_labels,
                              value_label_colname = 'final_label')
```

```{r}
# create small function to not have to keep writing hts_prep_data and hts_summary calls for each variable
summarize_trip_var = function(summarize_var, summarize_by){
  
  prepped_dt = hts_prep_data(summarize_var = summarize_var,
                             summarize_by = summarize_by,
                             variables_dt = variable_list,
                             data = hts_data,
                             id_cols = c('hhid', 'person_id', 'day_id', 'tripid', 'vehid'),
                             weighted = FALSE,
                             missing_values = c(995, NULL))

  if(summarize_var %in% c('mode_type', 'dest_purpose_cat')){
    cat_summary = hts_summary(prepped_dt = prepped_dt$cat,
                              summarize_var = summarize_var,
                              summarize_by = summarize_by,
                              id_cols = c('hhid', 'person_id', 'day_id', 'tripid', 'vehid'),
                              weighted = FALSE)
  } else{
    cat_summary = hts_summary(prepped_dt = prepped_dt$num,
                              summarize_var = summarize_var,
                              summarize_by = summarize_by,
                              id_cols = c('hhid', 'person_id', 'day_id', 'tripid', 'vehid'),
                              weighted = FALSE,
                              summarize_vartype = 'numeric')
  }
  
  return(cat_summary)

}

```

```{r}
mode_type_summary = factorize_df(df = summarize_trip_var('mode_type', NULL)$summary$unwtd[mode_type != 'NULL'],
                              vals_df = value_labels,
                              value_label_colname = 'final_label')
```

