---
title: "Travel Survey Unweighted Summary"
author: "suzanne"
date: "2023-01-29"
output:
  html_document: default
  pdf_document: default
---

These summaries are a quick quality control check on the unweighted survey data. We will compare across 2017, 2019, 2021, and 2023 where feasible. The purpose is to identify major problems that need to be fixed in the data, not to fully validate the data since it's not weighted yet.

```{r include=FALSE, message=FALSE, warning=FALSE}
library(DBI)
library(dplyr)
library(data.table)
library(ggplot2)
library(tidyr)
library(janitor)
library(scales)
source('unweighted-summary-functions.R')

```

```{r }
library(data.table) # general data manipulation
library(srvyr)      # survey statistics
library(dplyr)      # helpers for srvyr (mutate, group_by, and %>% pipe), 
                    # plus function near(), used in qa/qc checks 
library(stringr)    # string helper functions
library(flextable)  # formatted tables
library(ggplot2)    # plotting
library(scales)     # ggplot2 helpers
library(plotly)     # interactive plots
library(rstudioapi) # for setting working directory
library(psrcelmer)
library(tidyr)
library(stringr)

# Point to where the 2023 codebook lives:
codebook_path = 'J:/Projects/Surveys/HHTravel/Survey2023/Data/codebook/PSRC_Combined_Codebook_2023_groupings.xlsx'

# Read Data  ===================================================================



hh_rulesy<-get_table(db_name = "hhts_cleaning", "HHSurvey", "Household")
person_rulesy<-get_table(db_name = "hhts_cleaning", "HHSurvey", "Person")
day_rulesy<-get_table(db_name = "hhts_cleaning", "HHSurvey", "Day")
trip_rulesy<<-get_table(db_name = "hhts_cleaning", "HHSurvey", "Trip")

## Codebook -------------------------------------------------------------------- 

variables = readxl::read_xlsx(
  codebook_path,
  sheet = 'variable_list_2023'
)

values =  readxl::read_xlsx(
  codebook_path,
  sheet = 'value_labels_2023'
)

setDT(variables)
setDT(values)
```
```{r}

hh_group<- lookup_names(hh_rulesy, '2023', hhid, 'hhgroup')%>%group_by(hhgroup)%>%count()
hh_3_group<-hh_group%>%mutate(source_group=word(hhgroup, 2, sep='Diary completed via'))
hh_source<-hh_3_group%>%group_by(source_group)%>%summarise(total=sum(n))
```


```{r}
persons<-left_join(person_rulesy, hh_rulesy, by= 'hhid')
person_group<- lookup_names(persons, '2023', hhid, 'hhgroup')%>%group_by(hhgroup)%>%count()
person_3_group<-person_group%>%mutate(source_group=word(hhgroup, 2, sep='Diary completed via'))
person_source<-person_3_group%>%group_by(source_group)%>%summarise(total=sum(n))
```


```{r}
days<-left_join(day_rulesy, hh_rulesy, by= 'hhid')
day_group<- lookup_names(days, '2023', hhid, 'hhgroup')%>%group_by(hhgroup)%>%count()
day_3_group<-day_group%>%mutate(source_group=word(hhgroup, 2, sep='Diary completed via'))
day_source<-day_3_group%>%group_by(source_group)%>%summarise(total=sum(n))
```

```{r}
trips<-left_join(trip_rulesy, hh_rulesy, by= 'hhid')
trip_group<- lookup_names(trips, '2023', hhid, 'hhgroup')%>%group_by(hhgroup)%>%count()
trip_3_group<-trip_group%>%mutate(source_group=word(hhgroup, 2, sep='Diary completed via'))
trip_source<-trip_3_group%>%group_by(source_group)%>%summarise(total=sum(n))
```

```{r}
hh_person<-merge(hh_source, person_source, by='source_group')
person_days<-merge(hh_person, day_source, by= 'source_group')
person_trips<-merge(person_days, trip_source, by= 'source_group')

person_trips%>%rename(households=total.x, persons=total.y, days=total.x.1, trips=total.y.1)

```




