---
title: "2017-2019-2021 travel survey summaries for checking weights"
author: "suzanne"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
source('travel_survey_analysis_functions.R')

```

```{r}

```

## read in dataset including 2017,2019,2021

```{r hh, include = FALSE}
sql.hh.query<-paste("SELECT survey_year, hh_race_category, household_id, hhincome_detailed, hhincome_broad, car_share, res_factors_30min, res_factors_afford, res_factors_transit, res_factors_walk, vehicle_count, hhsize, numchildren, numadults, prev_res_factors_housing_cost,
hh_wt_combined, ABS_hh_weight FROM HHSurvey.v_households")

hhs<-read.dt(sql.hh.query, 'sqlquery')
head(hhs)
```

```{r person, include = FALSE}
```

```{r person, include = FALSE}
sql.person.query<-paste("SELECT survey_year, race_category,employment, workplace, commute_freq, commute_dur, commute_mode, mode_freq_1, mode_freq_2, mode_freq_3, wbt_bikemore_1, telecommute_freq, hh_wt_combined, ABS_adult_weight, ABS_mainrespondent_weight, OP_respondent_weight, combined_adult_weight, combined_respondent_weight FROM HHSurvey.v_persons")

persons<-read.dt(sql.person.query, 'sqlquery')

head(persons)
```

```{r trip, include = FALSE}
sql.trip.query <- paste("SELECT race_category, person_dim_id, hhincome_broad, rent_own, gender,  dest_purpose_cat, mode_simple, mode_1, trip_path_distance, travelers_hh, age_category,google_duration, trip_wt_combined, trip_weight_update_2021, combined_adult_trip_weight,abs_adult_trip_weight FROM HHSurvey.v_trips")
trips <- read.dt(sql.trip.query, 'sqlquery')
head(trips)
```

```{r}
hh_2017_2019<-hhs %>% drop_na(all_of('hh_wt_combined'))

cross_table_2017_2019<-cross_tab_categorical(hh_2017_2019,'hhincome_detailed', 'res_factors_30min', 'hh_wt_combined')

cross_table_2017_2019
simple_summary_one_var(hh_2017_2019,'res_factors_30min', 'hh_wt_combined')
```

## housing variable checks

```{r}
hh_2021<-hhs %>% drop_na(all_of('ABS_hh_weight'))

cross_table_2021<-cross_tab_categorical(hh_2021,'hhincome_detailed', 'res_factors_30min', 'ABS_hh_weight')

cross_table_2021
```

```{r}
simple_summary_one_var(hh_2021,'res_factors_30min', 'ABS_hh_weight')
```

```{r}
hh_2017_2019<-hhs %>% drop_na(all_of('hh_wt_combined'))

cross_table_2017_2019<-cross_tab_categorical(hh_2017_2019,'hhincome_broad', 'res_factors_afford', 'hh_wt_combined')

cross_table_2017_2019
```

```{r}
hh_2021<-hhs %>% drop_na(all_of('ABS_hh_weight'))

cross_table_2021<-cross_tab_categorical(hh_2021,'hhincome_broad', 'res_factors_afford', 'ABS_hh_weight')

cross_table_2021
```

```{r}
hh_2017_2019<-hhs %>% drop_na(all_of('hh_wt_combined'))

cross_table_2017_2019<-cross_tab_categorical(hh_2017_2019,'vehicle_count', 'res_factors_transit', 'hh_wt_combined')

cross_table_2017_2019

```

```{r}
hh_2021<-hhs %>% drop_na(all_of('ABS_hh_weight'))

cross_table_2021<-cross_tab_categorical(hh_2021,'vehicle_count', 'res_factors_transit', 'ABS_hh_weight')

cross_table_2021

```

## person variable checks

```{r}
persons_2017_2019<-persons %>% drop_na(all_of('hh_wt_combined')) %>% filter(!telecommute_freq %in% c("NA", "Not applicable", "Missing: Skip logic" ))%>% drop_na(all_of('telecommute_freq'))

cross_table_2017_2019<-cross_tab_categorical(persons_2017_2019,'race_category', 'telecommute_freq', 'hh_wt_combined')

cross_table_2017_2019
write.table(cross_table_2017_2019, "clipboard", sep="\t", row.names=FALSE)
simple_summary_one_var(persons_2017_2019,'telecommute_freq', 'hh_wt_combined')
```

```{r}
persons_2021<-persons %>% drop_na(all_of('combined_adult_weight'))%>% filter(!telecommute_freq %in% c("NA", "Not applicable", "Missing: Skip Logic" ))

cross_table_2021<-cross_tab_categorical(persons_2021,'race_category', 'telecommute_freq', 'combined_adult_weight')

cross_table_2021

write.table(cross_table_2021, "clipboard", sep="\t", row.names=FALSE)

simple_summary_one_var(persons_2021,'telecommute_freq', 'combined_adult_weight')
```

```{r}
```

```{r}
persons_2017_2019<-persons %>% drop_na(all_of('hh_wt_combined')) %>% filter(!commute_freq %in% c("NA", "Not applicable", "Missing: Skip logic" ))%>% drop_na(all_of('commute_freq'))


simple_summary_one_var(persons_2017_2019,'commute_freq', 'hh_wt_combined')
```

```{r}
persons_2021<-persons %>% drop_na(all_of('combined_adult_weight')) %>% filter(!commute_freq %in% c("NA", "Not applicable", "Missing: Skip Logic" ))%>% drop_na(all_of('commute_freq'))


simple_summary_one_var(persons_2021,'commute_freq', 'combined_adult_weight')
```

```{r}
```

```{r}
persons_2017_2019<-persons %>% drop_na(all_of('hh_wt_combined')) %>% filter(!mode_freq_1 %in% c("NA", "Not applicable", "Missing: Skip logic", "Missing: Non-response" ))%>% drop_na(all_of('mode_freq_1'))


simple_summary_one_var(persons_2017_2019,'mode_freq_1', 'hh_wt_combined')
write.table(simple_summary_one_var(persons_2017_2019,'mode_freq_1', 'hh_wt_combined'), "clipboard", sep="\t", row.names=FALSE)

```

```{r}
persons_2021<-persons %>% drop_na(all_of('combined_adult_weight')) %>% filter(!mode_freq_1 %in% c("NA", "Not applicable", "Missing: Skip Logic", "Missing: Non-reponse" ))%>% drop_na(all_of('combined_adult_weight'))


simple_summary_one_var(persons_2021,'mode_freq_1', 'combined_adult_weight')
write.table(simple_summary_one_var(persons_2021,'mode_freq_1', 'combined_adult_weight'), "clipboard", sep="\t", row.names=FALSE)
```

```{r}
persons_2017_2019<-persons %>% drop_na(all_of('hh_wt_combined')) %>% filter(!mode_freq_3 %in% c("NA", "Not applicable", "Missing: Skip logic", "Missing: Non-response" ))%>% drop_na(all_of('mode_freq_3'))


simple_summary_one_var(persons_2017_2019,'mode_freq_3', 'hh_wt_combined')
write.table(simple_summary_one_var(persons_2017_2019,'mode_freq_3', 'hh_wt_combined'), "clipboard", sep="\t", row.names=FALSE)

```

```{r}
persons_2021<-persons %>% drop_na(all_of('combined_adult_weight')) %>% filter(!mode_freq_3 %in% c("NA", "Not applicable", "Missing: Skip Logic", "Missing: Non-reponse" ))%>% drop_na(all_of('combined_adult_weight'))


simple_summary_one_var(persons_2021,'mode_freq_3', 'combined_adult_weight')
write.table(simple_summary_one_var(persons_2021,'mode_freq_3', 'combined_adult_weight'), "clipboard", sep="\t", row.names=FALSE)
```

## trip variable checks

```{r}
trips_2017_2019<-trips%>% drop_na(all_of('trip_wt_combined')) %>% filter(age_category!= 'Under 18 years' )


trip_mode_2017_2019<-simple_summary_one_var(trips_2017_2019,'mode_1', 'trip_wt_combined')
write.table(simple_summary_one_var(trips_2017_2019,'mode_1', 'trip_wt_combined'), "clipboard", sep="\t", row.names=FALSE)
```

```{r}
trips_2021<-trips%>% drop_na(all_of('combined_adult_trip_weight')) %>% filter(age_category!= 'Under 18 years' )


trip_mode_2021<-simple_summary_one_var(trips_2021,'mode_1', 'combined_adult_trip_weight')
write.table(simple_summary_one_var(trips_2021,'mode_1', 'combined_adult_trip_weight'), "clipboard", sep="\t", row.names=FALSE)
```

```{r}
trip_mode<-left_join(trip_mode_2017_2019, trip_mode_2021, by='mode_1', suffix=c('.2017_2019', '.2021'))
trip_mode
write.table(trip_mode, "clipboard", sep="\t", row.names=FALSE)
```

```{r}

trips_2017_2019<-trips%>% drop_na(all_of('trip_wt_combined')) %>% filter(age_category!= 'Under 18 years' )


trip_mode_2017_2019<-simple_summary_one_var(trips_2017_2019,'mode_simple', 'trip_wt_combined')
write.table(simple_summary_one_var(trips_2017_2019,'mode_simple', 'trip_wt_combined'), "clipboard", sep="\t", row.names=FALSE)

```

```{r}
trips_2021<-trips%>% drop_na(all_of('combined_adult_trip_weight')) %>% filter(age_category!= 'Under 18 years' )


trip_mode_2021<-simple_summary_one_var(trips_2021,'mode_simple', 'combined_adult_trip_weight')
write.table(simple_summary_one_var(trips_2021,'mode_simple', 'combined_adult_trip_weight'), "clipboard", sep="\t", row.names=FALSE)
```

```{r}
trip_mode<-left_join(trip_mode_2017_2019, trip_mode_2021, by='mode_simple', suffix=c('.2017_2019', '.2021'))
trip_mode
write.table(trip_mode, "clipboard", sep="\t", row.names=FALSE)
```

```{r}

trips_2017_2019<-trips%>% drop_na(all_of('trip_wt_combined')) %>% filter(age_category!= 'Under 18 years' )


trip_destpurp_2017_2019<-simple_summary_one_var(trips_2017_2019,'dest_purpose_cat', 'trip_wt_combined')
write.table(simple_summary_one_var(trips_2017_2019,'dest_purpose_cat', 'trip_wt_combined'), "clipboard", sep="\t", row.names=FALSE)

```

```{r}
trips_2021<-trips%>% drop_na(all_of('combined_adult_trip_weight')) %>% filter(age_category!= 'Under 18 years' )


trip_purpose_2021<-simple_summary_one_var(trips_2021,'dest_purpose_cat', 'combined_adult_trip_weight')

```

```{r}
trip_purpose<-left_join(trip_destpurp_2017_2019, trip_purpose_2021, by='dest_purpose_cat', suffix=c('.2017_2019', '.2021'))
trip_purpose
write.table(trip_mode, "clipboard", sep="\t", row.names=FALSE)
```

```{r}
trips_2017_2019<-trips%>% drop_na(all_of('trip_wt_combined')) %>% filter(age_category!= 'Under 18 years' ) %>% filter(trip_path_distance<200)

trips_2017_2019_dist_purp_mode<- trips_2017_2019 %>% group_by(mode_simple, dest_purpose_cat)%>%summarise(mean_dist=weighted.mean(x=trip_path_distance, w=trip_wt_combined))
trips_2017_2019_dist_purp_mode

```

```{r}
trips_2021<-trips%>% drop_na(all_of('combined_adult_trip_weight')) %>% filter(age_category!= 'Under 18 years' ) %>% filter(trip_path_distance<200)

trips_2021_dist_purp_mode<- trips_2021%>% group_by(mode_simple, dest_purpose_cat)%>%summarise(mean_dist=weighted.mean(x=trip_path_distance, w=combined_adult_trip_weight))
trips_2021_dist_purp_mode
```

```{r}
trips_dist_mode<- left_join(trips_2017_2019_dist_purp_mode,trips_2021_dist_purp_mode,by =c('mode_simple', 'dest_purpose_cat'),suffix=c('.2017_2019', '.2021'))
trips_dist_mode

write.table(trips_dist_mode, "clipboard", sep="\t", row.names=FALSE)

```
``

```{r}
trips_2017_2019<-trips%>% drop_na(all_of('trip_wt_combined')) %>% filter(age_category!= 'Under 18 years' ) %>% filter(google_duration<200)

trips_2017_2019_time_purp_mode<- trips_2017_2019 %>% group_by(mode_simple, dest_purpose_cat)%>%summarise(mean_time=weighted.mean(x=google_duration, w=trip_wt_combined))
trips_2017_2019_time_purp_mode

```


```{r}
trips_2021<-trips%>% drop_na(all_of('combined_adult_trip_weight')) %>% filter(age_category!= 'Under 18 years' ) %>% filter(google_duration<200)

trips_2021_time_purp_mode<- trips_2021%>% group_by(mode_simple, dest_purpose_cat)%>%summarise(mean_time=weighted.mean(x=google_duration, w=combined_adult_trip_weight))
trips_2021_time_purp_mode
```

```{r}
trips_time_mode<- left_join(trips_2017_2019_time_purp_mode,trips_2021_time_purp_mode,by =c('mode_simple', 'dest_purpose_cat'),suffix=c('.2017_2019', '.2021'))
trips_time_mode

write.table(trips_time_mode, "clipboard", sep="\t", row.names=FALSE)

```
```
