project:
  type: book
  output-dir: "HTS-summary-notebook"

book:
  title: "2025 HTS Summary"
  repo-url: https://github.com/psrc/travel-studies/tree/master/2025
  search: false
  sidebar:
    logo: PSRClogo2016path.png

  chapters:
    - index.qmd # this is a required file for Quarto Book
    # - Analysis/Topsheet/topsheet_summary.qmd
    - part: "<b>Care Giving</b>"
      chapters:
        - Analysis/care-giving/care-giving.qmd
        - Analysis/care-giving/care-giving-mode-income.qmd
        - Analysis/care-giving/care-giving-gender.qmd
        - Analysis/care-giving/care-giving-licensing.qmd
        - Analysis/care-giving/care-giving-hhstructure.qmd
        - Analysis/care-giving/care-giving-race.qmd
    - part: "<b>Delivery</b>"
      chapters:
        - Analysis/Delivery/delivery_analysis.qmd
        - Analysis/Delivery/delivery_landuse.qmd
    - part: "<b>Special Needs</b>"
      chapters:
        - Analysis/special-needs/section_index.qmd
        - Analysis/special-needs/paired-tradeoff-analysis.qmd  
    - Analysis/Transit/transit.qmd
    - Analysis/walk-bike/walk_bike_summary.qmd


format:
  html:
    mainfont: Poppins
    theme: [cosmo, custom.scss]  # custom formatting
    echo: false
    code-tools: true
    df-print: kable
    fig-asp: .7
    fig-width: 4

execute:
  freeze: auto  # re-render only when source changes


toc: true
warnings: false
comments:  # enable commenting
  hypothesis: true
