project:
  output-dir: "HTS-summary-report"

book:
  title: "2025 HTS Summary Report"
  chapters:
    - index.qmd # this is a required file for Quarto Book
    - SummaryReport/walk-bike.qmd
    - SummaryReport/Telework.qmd
    - SummaryReport/Delivery.qmd