---
title: "All Locations"
date: today
---

```{r}
#| include: false

source("functions.R")
tables <- readRDS("df_loc.RDS")

df_trip_loc <- tables[[1]]
df_person_loc <- tables[[2]]
df_hh_loc <- tables[[3]]
```

## Home Location

:::{.panel-tabset}

### County
```{r}
CreateTableOne(data = df_hh_loc,
               vars = c("home_county"),
               includeNA = TRUE)
```

### City
```{r}
CreateTableOne(data = df_hh_loc,
               vars = c("home_city"),
               includeNA = TRUE)
```

### Center
```{r}
CreateTableOne(data = df_hh_loc,
               vars = c("home_center"),
               includeNA = TRUE)
```

### Regional Geography
```{r}
CreateTableOne(data = df_hh_loc,
               vars = c("home_rg"),
               includeNA = TRUE)
```

:::

## Person Work Location

:::{.panel-tabset}

### County
```{r}
CreateTableOne(data = df_person_loc,
               vars = c("work_county"),
               includeNA = TRUE)
```

### City
```{r}
CreateTableOne(data = df_person_loc,
               vars = c("work_city"),
               includeNA = TRUE)
```

### Center
```{r}
CreateTableOne(data = df_person_loc,
               vars = c("work_center"),
               includeNA = TRUE)
```

### Regional Geography
```{r}
CreateTableOne(data = df_person_loc,
               vars = c("work_rg"),
               includeNA = TRUE)
```

:::

## Person School Location

:::{.panel-tabset}

### County
```{r}
CreateTableOne(data = df_person_loc,
               vars = c("school_county"),
               includeNA = TRUE)
```

### City
```{r}
CreateTableOne(data = df_person_loc,
               vars = c("school_city"),
               includeNA = TRUE)
```

### Center
```{r}
CreateTableOne(data = df_person_loc,
               vars = c("school_center"),
               includeNA = TRUE)
```

### Regional Geography
```{r}
CreateTableOne(data = df_person_loc,
               vars = c("school_rg"),
               includeNA = TRUE)
```

:::

## Trip Destination

:::{.panel-tabset}

### County
```{r}
CreateTableOne(data = df_trip_loc,
               vars = c("dest_county"),
               includeNA = TRUE)
```

### City
```{r}
CreateTableOne(data = df_trip_loc,
               vars = c("dest_city"),
               includeNA = TRUE)
```

### Center
```{r}
CreateTableOne(data = df_trip_loc,
               vars = c("dest_center"),
               includeNA = TRUE)
```

### Regional Geography
```{r}
CreateTableOne(data = df_trip_loc,
               vars = c("dest_rg"),
               includeNA = TRUE)
```

:::

## Trip Origin

:::{.panel-tabset}

### County
```{r}
CreateTableOne(data = df_trip_loc,
               vars = c("origin_county"),
               includeNA = TRUE)
```

### City
```{r}
CreateTableOne(data = df_trip_loc,
               vars = c("origin_city"),
               includeNA = TRUE)
```

### Center
```{r}
CreateTableOne(data = df_trip_loc,
               vars = c("origin_center"),
               includeNA = TRUE)
```

### Regional Geography
```{r}
CreateTableOne(data = df_trip_loc,
               vars = c("origin_rg"),
               includeNA = TRUE)
```

:::


