---
title: "VMT research: Literature review"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    df_print: kable
    highlight: tango
bibliography: lit_reference.bib 
date: today
---

## factors that may explain the variance in VMT

1. **household and person socio-economic and demographic characteristics**: household size, number of children, number of workers, and household income
2. **residential built environment attributes**: land use density, population and employment density, parking availability and pricing, distance from residence to work centers, and multimodal accessibility (to destinations)
3. **residential self-selection (i.e., lifestyle preference) effects**: capture the notion that individuals may choose to locate (live and work) in built environments that are consistent with their attitudes (e.g., environmental sensitivity) and lifestyle preferences (e.g., car-free lifestyle).
4. **human social and spatial dependency effects**: the socio-spatial dependence effect. Household VMT may be shaped by social interaction and spatial dependency effects, capturing influences engendered by people’s interactions and geographic proximity
5. **policy intervention**: Congestion Charge, Parking & Traffic Control, Limited Traffic Zone, Workplace Parking Charge, and employer-based trip reduction (Mobility Services for Commuters, telecommuting)

    
source from [@singh2018quantifying; @hong2014built; kuss2022dozen]


## Key things to address

1. Self-selection: individuals selecting themselves into preferred choices rather than being randomly distributed [@hong2014built]
    - This causes bias when estimating a regression model to establish behavioral relationships
    - solutions:
        a. employing a rich set of socio-economic factors (built-environment measures may become insignificant or inconsequential)
        b. longitudinal research design: following the same households that moved over time (Krizek, K.J.: Residential relocation and changes in urban travel: does neighborhood-scale urban form matter. J. Am. Plan. Assoc. 69(3), 265–281 (2003b))
        c. questions related to travelers’ preferences for transportation modes and residential locations
        d. classified households’ residential locations into four types (urban, inner-ring suburbs, suburbs, and exurbs) based on the distance between the residential location and city center
        
2. Spatial autocorrelation: observations at nearby locations tend to have similar characteristics, and hence the assumption of independence of observations is no longer met.


## Existing methods

### [@hong2014built]

1. model: Bayesian hierarchical models with built-environment factors measured at different geographic scales. 
    - Spatial random effects based on a conditional autoregressive specification are incorporated in the hierarchical model framework to account for spatial contiguity among Traffic Analysis Zones.
  
2. separate models for work and non-work tours 

3. data: PSRC 2006 Household Activity Survey and built environment variables (densities of residential,
nonresidential land uses and four-way intersection, an entropy measure of land use mix, and distance from CBD)


