---
title: "VMT research: Literature review"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    df_print: kable
    highlight: tango
bibliography: lit_reference.bib 
date: "2023-06-21"
---

```{r, echo=FALSE}
colorize <- function(x) {
  sprintf("<span style='background: %s;'>%s</span>", "#ffffbf",
      x)
}
# notebooks/validation/auto_ownership
# summarize/exploratory/bike summary
```


# why are we looking into reducing VMT? 

- household VMT because it constitutes
more than 75% of total VMT in the United States (AASHTO, 2013) [@singh2018quantifying]
- Reduce emission: reducing car use has amongst the highest potential to reduce per capita emissions [@kuss2022dozen]
- Promote equity amidst limited urban space [@kuss2022dozen]
- Increases in VMT are associated with higher levels of congestion and delay, energy consumption and greenhouse gas emissions, and roadway crashes (Sacramento Area Council of Governments, 2016) – adversely affecting human health, quality of life, and community resiliency and sustainability (Levy et al., 2010). [@singh2018quantifying]

# factors that influence household VMT

- density, land use diversity, and pedestrian-oriented designs reduce trip rates, and encourage nonmotorized
mode use [@singh2018quantifying]
- relocating to high accessibility neighborhood decreases household VMT

# possible approaches: seeking ways to reduce vehicle miles of travel without inhibiting household and business activity engagement
- **Transition management**: an instrumental, action-oriented
governance framework aiming to introduce a **long-term perspective in policymaking, engage participation and interaction between multiple stakeholders**, apply a learning philosophy (learning-by-doing and doing-by-learning), inspire new initiatives, and enable actors to address specific challenges which impede the transition process [@kuss2022dozen]

# what do we need to go towards lower VMT?
- gap remains, however, in understanding the processes and policies that cities can adopt to reduce their reliance on cars


# Notes for papers {.tabset}
## Quantifying the relative contribution of factors to household vehicle miles of travel

[@singh2018quantifying]

- household VMT/ New York metropolitan region
- purpose: 
    - to provide a comprehensive understanding and quantification of the relative effects of various factors on household vehicle miles of travel
    - to develop targeted policies that more effectively reduce vehicular travel
    
- data: 2010–2011 Regional Household Travel Survey (RHTS) of the New York Metropolitan Transportation Council (NYMTC)
- method: a joint model of residential location (density) choice and household VMT – accounting for residential self-selection and socio-spatial dependency effects
    
- four factors that may explain the variance in household VMT, including 
    1. **household and person socio-economic and demographic characteristics**: household size, number of children, number of workers, and household income
    2. **residential built environment attributes**: land use density, population and employment density, parking availability and pricing, distance from residence to work centers, and multimodal accessibility (to destinations)
    3. **residential self-selection (i.e., lifestyle preference) effects**: capture the notion that individuals may choose to locate (live and work) in built environments that are consistent with their attitudes (e.g., environmental sensitivity) and lifestyle preferences (e.g., car-free lifestyle).
    4. ~~**human social and spatial dependency effects**~~: the socio-spatial dependence effect. Household VMT may be shaped by social interaction and spatial dependency effects, capturing influences engendered by people’s interactions and geographic proximity

- finding: suggests that household socioeconomic and demographic characteristics play a significant and large role (much larger than built environment and self-selection) in shaping household VMT
  `r emo::ji("fire")` what does this finding imply for policy? household socioeconomic and demographic characteristics aren't something that we can change


## How do local actions affect VMT? A critical review of the empirical evidence

[@salon2012local]

- This paper provides an assessment of the state of the evidence on the effectiveness of these strategies in reducing VMT

### Challenges of estimating the effect of local actions on VMT
1. the relationship between these actions and VMT is often indirect
    * In many of the cases where the factors are more directly affected by policy actions (e.g. road pricing and transit service), the literature focuses on the effect of the action on other travel indicators (e.g. mode split or traffic volume) that are the direct target of these actions, while estimating the effect on VMT is more complicated.

2. data on VMT is rarely collected in a way that facilitates estimating the effect of a particular action
    * travel diary survey data: the distances traveled are calculated for the reported trip origins and destinations along the road network using algorithms to identify the most likely route.
    * regional travel demand forecasting models: calibrated using a combination of travel diary survey data and Highway Performance Monitoring System
traffic counts.

3. robust research designs are extremely difficult to implement in this area.

### How much do local actions affect VMT? The evidence
1. Land use planning: the relationship between VMT and residential density, the mix of land uses, regional accessibility and jobs-housing balance, and road network connectivity within a neighborhood
    - areas with a better balance between housing and jobs will have lower VMT because commutes will be shorter
    - most common land use variable: residential density (correlated with land use factors and factors such as transit service and parking prices)
    
2. Road and parking pricing: the cost of car use, and pricing strategies are repeatedly suggested by transport planners and economists as a way to reduce the negative externalities of driving.

3. Public transportation: (1) fares, (2) service frequency, (3)
service miles or hours, and (4) distance to the nearest transit station

4. Non-motorized transportation: the impact of pedestrian and bicycle infrastructure and educational programs on the amount of walking and bicycling that people engage in

5. Incentives and information

## A dozen effective interventions to reduce car use in European cities: Lessons learned from a meta-analysis and transition management

[@kuss2022dozen]

- identified 12 intervention types combining different measures and policy instruments that were effective in reducing car use in European cities. The most effective:
  - Congestion Charge, 
  - Parking & Traffic Control, and 
  - Limited Traffic Zone.
- recommendations:
  - Parking and Traffic Control,
  - **Workplace Parking Charge**, and 
  - **Mobility Services for Commuters**

### Interventions
1. Charging & Pricing: charge for cars crossing the border of a defined charging zone, with `r colorize("revenues used for infrastructure or public transport investments")`, as well as parking fees for workplace parking, combined with either a cash-out scheme for local with investments in the local public transport system employers
2. Access limitations
3. Parking & Traffic Control: parking space removal, traffic route alteration, introduction of car-free streets, as well as the extension of pedestrian-friendly infrastructure and bicycle lanes
4. Mobility Services: services for commuters to local workplaces and university students to provide **free public transport passes**, a private shuttle bus, and marketing and awareness-raising measures
5. Car Sharing
6. Travel Planning: combining personalized planning and advising with improved infrastructure, public transport discounts, and awareness-raising
7. Gamification

### intervention effectiveness




## Can we reduce car use and, if so, how? A review of available evidence

[@graham2011can]

- Conclusion: overall the evidence base for the effectiveness of any type of intervention to reduce car use is weak.

### Car-use reduction initiatives can be broadly characterised as structural or psychological
- **Structural interventions**: modification of the physical and/or legislative structures that regulate travel behaviour in order to decrease the attractiveness and opportunities for car travel and/or offer incentives for use of non-car transport
- **Psychological interventions**: designed to change perceptions, beliefs and attitudes and, thereby, motivate voluntary
change in transportation choices


# identify factors that influence per-person VMT
- list of useful papers: [@zhang2012built]



# list of literature to review

- Brownstone, D., Golob, T.F., 2009. The impact of residential density on vehicle usage and energy consumption. J. Urban Econ. 65 (1), 91–98.
- Cervero, R., Murakami, J., 2010. Effects of built environments on vehicle miles traveled: evidence from 370 US urbanized areas. Environ. Plan. A 42 (2), 400–418.
- Travel behavior of immigrants: An analysis of the 2001 National Household Transportation Survey

# Reference
