---
title: "commute_subsidy_with_new_package"
author: "suzanne"
date: "2024-11-1"
output: html_document
---


```{r}
library(psrc.travelsurvey)
library(dplyr)
library(psrcplot)
library(travelSurveyTools)
library(tidyr)
library(stringr)
library(data.table)


hts_data <- get_psrc_hts(survey_vars = c('commute_subsidy_1', 'hhincome_detailed', 'workplace'))
```

```{r pressure, echo=FALSE}
 cb_path = str_glue("J:/Projects/Surveys/HHTravel/Survey2023/Data/data_published/PSRC_Codebook_2023_v1.xlsx")
 
 variable_list = readxl::read_xlsx(cb_path, sheet = 'variable_list')
 value_labels = readxl::read_xlsx(cb_path, sheet = 'value_labels')
 
 setDT(variable_list)
 setDT(value_labels)
```

```{r}

summarize_weighted <- function(hts_data, summarize_var, summarize_by, id_cols, wt_cols,wtname,summarize_vartype='categorical'){
  
  
  prepped_dt <- hts_prep_variable(summarize_var = summarize_var,
                                  summarize_by = summarize_by,
                                  data = hts_data,
                                  id_cols=id_cols,
                                  wt_cols=wt_cols,
                                  weighted=TRUE,
                                  remove_missing=TRUE)

  
  if(summarize_vartype=='categorical'){
      summary<-hts_summary(prepped_dt = prepped_dt$cat,
                       summarize_var = summarize_var,
                       summarize_by = summarize_by,
                       summarize_vartype = summarize_vartype,
                       id_cols= id_cols,
                       wtname=wtname,
                       weighted=TRUE,
                       se=TRUE)
  }else{
    summary<-hts_summary(prepped_dt = prepped_dt$num,
                         summarize_var = summarize_var,
                         summarize_by = summarize_by,
                         summarize_vartype = summarize_vartype,
                         id_cols= id_cols,
                         wtname=wtname,
                         weighted=TRUE,
                         se=TRUE)
    
  }
  
  
  return(summary)
}
```

```{r}
workers<-hts_data$person%>%filter(!workplace %in% c('Missing: Skip logic', "Missing: Skip Logic"))%>%drop_na(workplace)
hh_23<-hts_data$hh%>%filter(survey_year=='2023')
person_23<-workers%>%filter(survey_year=='2023')
worker_list<-list(hh=hh_23, person=person_23)

```

```{r}
variables_dt<-variable_list%>%mutate(is_checkbox=0, shared_name=variable)

variable_list<-variable_list%>%mutate(is_checkbox=0, shared_name=variable)

```

```{r}
variables_list<-variables_dt
old_code_approach<- summarize_weighted(hts_data= worker_list,
                               summarize_var = 'commute_subsidy_1',
                               summarize_by = 'hhincome_detailed',
                               id_cols=c('hh_id', 'person_id'),
                               wt_cols=c('hh_weight', 'person_weight'),
                               wtname= 'person_weight')
```



```{r}
new_approach<- psrc_hts_stat(worker_list, "person", c('commute_subsidy_1','hhincome_detailed'), incl_na=TRUE)
```
```{r}
variable_list%>%filter(variable=='commute_subsidy_1')
```


```{r}
worker_list$person%>%group_by(commute_subsidy_1)%>%summarize(workers=sum(person_weight))
```



