---
title: "same-sex-hh-data"
author: "suzanne"
date: "2022-11-29"
output: html_document
---

```{r setup, include=FALSE}
library(psrc.travelsurvey)
library(dplyr)
library(tidyr)
```



```{r }
get_vars<-c('relationship', 'gender', 'final_cnty', 'vehicle_count',  "hhincome_broad",  'hhincome_detailed', "age", "age_category", 'final_home_is_rgc', 'race_category', 'race_eth_broad', 'person_id', 'household_id')
```


Get the data from Elmer.
 
```{r}
person_data_17_19<- get_hhts("2017_2019", "p", vars=get_vars)
person_data_21<- get_hhts("2021", "p", vars=get_vars)
```

```{r}
gender_relationship_hhid_17_19<-person_data_17_19%>%filter(relationship %in% c('Self','Spouse or partner'))%>%count(gender, household_id)%>%filter(n>1)

```


```{r}
gender_relationship_hhid_21<-person_data_21%>%filter(relationship %in% c('Self','Spouse or partner'))%>%count(gender, household_id)%>%filter(n>1)

```

```{r}
hh_vars_17_19<-c('household_id', 'prev_res_factors_displaced','numadults')
hh_vars_21<-c('household_id', 'prev_res_factors_displaced', 'numadults')

```

```{r}
hh_data_17_19<- get_hhts("2017_2019", "h", vars=hh_vars_17_19)%>%filter(numadults>1)
hh_data_21<- get_hhts("2021", "h", vars=hh_vars_21)%>%filter(numadults>1)

```

```{r}
hh_data_17_19_same_sex<- merge(gender_relationship_hhid_17_19,hh_data_17_19, by.x='household_id', by.y='household_id', all.y=TRUE)%>%mutate(same_sex_hh=ifelse(is.na(n),"Not Same Sex Coupled", 'Same Sex Coupled'))%>%filter(same_sex_hh=='Same Sex Coupled')

hh_data_17_19_not_same_sex<- merge(gender_relationship_hhid_17_19,hh_data_17_19, by.x='household_id', by.y='household_id', all.y=TRUE)%>%mutate(same_sex_hh=ifelse(is.na(n),"Not Same Sex Coupled", 'Same Sex Coupled'))%>%filter(same_sex_hh=='Not Same Sex Coupled')

i <- sapply(hh_data_17_19_same_sex, is.factor)
hh_data_17_19_same_sex$same_sex_hh <- as.character(hh_data_17_19_same_sex$same_sex_hh)
```


```{r}
hh_data_21_same_sex<- merge(gender_relationship_hhid_21,hh_data_21, by.x='household_id', by.y='household_id', all.y=TRUE)%>%mutate(same_sex_hh=ifelse(is.na(n),"Not Same Sex Coupled", 'Same Sex Coupled'))
```

```{r}
hh_summs_2017_2019_same_sex <- hhts_count(
  hh_data_17_19_same_sex,
  group_vars = c('prev_res_factors_displaced'),
  spec_wgt = 'hh_weight_2017_2019',
  incl_na = TRUE
) #%>% drop_na(c('same_sex_hh', 'prev_res_factors_displaced')) %>% filter(prev_res_factors_displaced !=
                                                                     #'Total')
hh_summs_2017_2019_not_same_sex <- hhts_count(
  hh_data_17_19_not_same_sex,
  group_vars = c('prev_res_factors_displaced'),
  spec_wgt = 'hh_weight_2017_2019',
  incl_na = TRUE
)

```
MOEs are too big