---
title: "Transportation Operator Committee HHTS 2021 notes"
output:
  html_document:
    df_print: paged
---

https://www.psrc.org/committee/transportation-operators-committee

July 27 meeting

We are gathering materials information that could be useful to the transportation operators committee


```{r }
library(psrc.travelsurvey)
library(dplyr)
library(stringr)
library(ggplot2)
library(psrcplot)
library(forcats)
library(odbc)
library(DBI)
library(tidyr)
library(tidycensus)
library(psrcslides)
library(officer)
library(DBI)
install_psrc_fonts()
```


```{r}
mode_vars<-c('mode_1', 'mode_simple')
other_vars<-c('sample_county', 'vehicle_count',  "hhincome_broad",  'hhincome_detailed', 'final_home_is_rgc', 'dest_purpose_cat', 'origin_purpose_cat', 'trip_path_distance', 'household_id', 'hhsize', 'lifecycle')
all_vars<-c(mode_vars, other_vars)
household_vars=c('vehicle_count',  "hhincome_broad",  'hhincome_detailed', 'final_home_is_rgc', 'hhsize', 'household_id', 'lifecycle')
```


```{r}
trip_data_17<- get_hhts("2017", "t", vars=all_vars)
```

```{r}
trip_data_19<- get_hhts("2019", "t", vars=all_vars)
```

```{r}
trip_data_21<- get_hhts("2021", "t", vars=all_vars)
```

```{r}
household_data_17<- get_hhts("2017", "h", vars=household_vars)
```

```{r}
household_data_19<- get_hhts("2019", "h", vars=household_vars)
```




```{r}
household_data_21<- get_hhts("2021", "h", vars=household_vars)
```


```{r}
 elmer_connect<-DBI::dbConnect(odbc::odbc(),
                 driver = "ODBC Driver 17 for SQL Server",
                 server = "AWS-PROD-SQL\\Sockeye",
                 database = "Elmer",
                 trusted_connection = "yes",
                 port = 1433)
  


```

 
 
 
```{r}
trip_grouping <-function(trip_data){

trip_data<-trip_data%>%mutate(NoVehicles=ifelse(vehicle_count=='0 (no vehicles)', 'No Vehicles', "Has Vehicles")) %>%mutate(hhincome_100= case_when(
    hhincome_broad=="Under $25,000" ~ "Under $75,000",
    hhincome_broad=="$25,000-$49,999" ~ "Under $75,000",
    hhincome_broad=="$50,000-$74,999" ~ "Under $75,000",
    hhincome_broad=='$75,000-$99,999' ~ '$75,000 or more',
    hhincome_broad=='$100,000-$199,999' ~ '$75,000 or more',
                                 hhincome_broad=='$200,000 or more' ~ '$75,000 or more',
                                 TRUE~hhincome_broad))%>%
  mutate(simple_purpose=ifelse(dest_purpose_cat=='Home', origin_purpose_cat, dest_purpose_cat))%>%
  mutate(simple_purpose=case_when(simple_purpose=='Work'~ 'Work/School',
                                  simple_purpose=='School'~ 'Work/School',
                                  simple_purpose=='Work-related'~ 'Work/School',
                                  simple_purpose=='Shop'~ 'Shop',
                                  simple_purpose=='Escort'~ 'Errands',
                                  simple_purpose=='Errand/Other'~ 'Errands',
                                  simple_purpose=='Change mode'~ 'Errands',
                                  simple_purpose=='Social/Recreation' ~ 'Social/Recreation/Meal',
                                  simple_purpose=='Meal' ~ 'Social/Recreation/Meal',
                                  simple_purpose=='Meal' ~ 'Social/Recreation/Meal',
                                  simple_purpose=='Home' ~'Errands',
                                  is.na(simple_purpose) ~ 'Errands',
                                  TRUE ~ simple_purpose))%>%mutate(hhsize= case_when(hhsize == "1 person" ~ '1 person', 
                                  hhsize == "2 people"  ~ '2 people', 
                                   hhsize == "3 people" ~ '3 people',
                                   hhsize == "4 people" | 
                                  hhsize == "5 people" | 
                                  hhsize == "6 people" | 
                                  hhsize == "7 people" |
                                  hhsize == "8 people" | 
                                  hhsize == "12 people" ~ "4+ people"))
 


trip_data$hhincome_100_f=factor(trip_data$hhincome_100,levels=c("Under $75,000","$75,000 or more"))
trip_data

}

simple_groupings<-c('race_eth_broad'='Race/Ethnicity','hhincome_100_f'='Household Income','NoVehicles'= 'Household Vehicles', 'sample_county' ='Home County', 'final_home_is_rgc'='Home in Regional Growth Center',  'hhsize' ='Household Size', 'lifecycle' = 'Lifecycle'  )
```












```{r}
household_grouping<-function(household_data){
household_data<-household_data%>%mutate(NoVehicles=ifelse(vehicle_count=='0 (no vehicles)', 'No Vehicles', "Has Vehicles")) %>%mutate(hhincome_100= case_when(
    hhincome_broad=="Under $25,000" ~ "Under $75,000",
    hhincome_broad=="$25,000-$49,999" ~ "Under $75,000",
    hhincome_broad=="$50,000-$74,999" ~ "Under $75,000",
    hhincome_broad=='$75,000-$99,999' ~ '$75,000 or more',
    hhincome_broad=='$100,000-$199,999' ~ '$75,000 or more',
                                 hhincome_broad=='$200,000 or more' ~ '$75,000 or more',
                                 TRUE~hhincome_broad))%>%mutate(hhsize= case_when(hhsize == "1 person" ~ '1 person', 
                                  hhsize == "2 people"  ~ '2 people', 
                                   hhsize == "3 people" ~ '3 people',
                                   hhsize == "4 people" | 
                                  hhsize == "5 people" | 
                                  hhsize == "6 people" | 
                                  hhsize == "7 people" |
                                  hhsize == "8 people" | 
                                  hhsize == "12 people" ~ "4+ people"))

household_data$hhincome_100_f=factor(household_data$hhincome_100,levels=c("Under $75,000","$75,000 or more"))
household_data
}


simple_groupings<-c('hhincome_100_f'='Household Income','NoVehicles'= 'Household Vehicles', 'final_home_is_rgc'='Home in Regional Growth Center', 'hhsize' ='Household Size', 'lifecycle' ='Lifecycle' )
```

```{r}
trip_data_17<-trip_grouping(trip_data_17)
trip_data_19<-trip_grouping(trip_data_19)
trip_data_21<-trip_grouping(trip_data_21)

household_data_17<-household_grouping(household_data_17)
household_data_19<-household_grouping(household_data_19)
household_data_21<-household_grouping(household_data_21)
```

```{r include=TRUE}
shop_trips_per_hh_by_var<-function(trip_data, household_data, trip_weight, hh_weight, cat_name){

shop_trips<-trip_data%>%filter(simple_purpose=='Shop')
print(shop_trips)
trip_summs <- hhts_count(shop_trips,
                                        group_vars=c(cat_name),
                                        spec_wgt=trip_weight)

print(trip_summs)
  
hh_summs <- hhts_count(household_data,
                                        group_vars=c(cat_name),
                                        spec_wgt=hh_weight)

print(hh_summs)
 trips_households<- merge(trip_summs, hh_summs, by=cat_name, suffixes=c('_trips','_household' ))%>%mutate(trips_per_household=count_trips/count_household,moe_trips_household=moe_ratio(count_trips, count_household, count_moe_trips, count_moe_household))

}

```

Trips per household
```{r }
for(i in seq(1, length(simple_groupings))){
  g <- simple_groupings[i]
  # cat_name <- eval(names(g))
  cat_name <- names(g)

 
 shop_trips_hh_17<-shop_trips_per_hh_by_var(trip_data_17, household_data_17,'trip_weight_2017_v2021', 'hh_weight_2017_v2021', cat_name )
 
  shop_trips_hh_19<-shop_trips_per_hh_by_var(trip_data_19, household_data_19,'trip_weight_2019_v2021', 'hh_weight_2019_v2021', cat_name)
  
   shop_trips_hh_21<-shop_trips_per_hh_by_var(trip_data_21, household_data_21,'trip_weight_2021_ABS_Panel_adult', 'hh_weight_2021_ABS', cat_name)
   
   
 shop_trips_households_long<- bind_rows(shop_trips_hh_17, shop_trips_hh_19, shop_trips_hh_21) %>%mutate(survey_trips = str_replace_all(survey_trips, "_", ""))%>%filter(!!rlang::sym(cat_name)!='Total')%>%drop_na(cat_name)

print(shop_trips_households_long)

 shop_trips_households_long_total<- bind_rows(shop_trips_hh_17, shop_trips_hh_19, shop_trips_hh_21) %>%mutate(survey_trips = str_replace_all(survey_trips, "_", ""))%>%filter(!!rlang::sym(cat_name)=='Total')

  
   p<-create_column_chart(t= shop_trips_households_long , x=cat_name, y='trips_per_household', f='survey_trips', moe='moe_trips_household', est='number', color = 'psrc_light', interactive=FALSE) + 
  xlab('Household Characteristic') + ylab('Shopping Trips per Household')+theme(axis.title.x = element_text(size=25,color="#4C4C4C"))+theme(axis.text.x = element_text(size=25,color="#4C4C4C"))+theme(axis.title.y = element_text(size=25,color="#4C4C4C"))+theme(axis.text.y.left =   element_text(size=35,color="#4C4C4C"))+theme(legend.text=element_text(size=25))
   
    p1<-create_column_chart(t= shop_trips_households_long_total , x=cat_name, y='trips_per_household', f='survey_trips', moe='moe_trips_household', est='number', color = 'psrc_light', interactive=FALSE) + 
  xlab('All Households') + ylab('Shopping Trips per Household')+theme(axis.title.x = element_text(size=25,color="#4C4C4C"))+theme(axis.text.x = element_text(size=25,color="#4C4C4C"))+theme(axis.title.y = element_text(size=25,color="#4C4C4C"))+theme(axis.text.y.left =   element_text(size=35,color="#4C4C4C"))+theme(legend.text=element_text(size=25))
  

  print(p)
  print(p1)
  

  
}
```

```{r }
for(i in seq(1, length(simple_groupings))){
  g <- simple_groupings[i]
  # cat_name <- eval(names(g))
  cat_name <- names(g)
 
 shop_trips_hh_17<-shop_trips_per_hh_by_var(trip_data_17, household_data_17,'trip_weight_2017_v2021', 'hh_weight_2017_v2021', cat_name )
 
  shop_trips_hh_19<-shop_trips_per_hh_by_var(trip_data_19, household_data_19,'trip_weight_2019_v2021', 'hh_weight_2019_v2021', cat_name)
  
   shop_trips_hh_21<-shop_trips_per_hh_by_var(trip_data_21, household_data_21,'trip_weight_2021_ABS_Panel_adult', 'hh_weight_2021_ABS', cat_name)
   
   
 shop_trips_households_long<- bind_rows(shop_trips_hh_17, shop_trips_hh_19, shop_trips_hh_21) %>%mutate(survey_trips = str_replace_all(survey_trips, "_", ""))%>%filter(!!rlang::sym(cat_name)!='Total')%>%drop_na(cat_name)

print(shop_trips_households_long)

 shop_trips_households_long_total<- bind_rows(shop_trips_hh_17, shop_trips_hh_19, shop_trips_hh_21) %>%mutate(survey_trips = str_replace_all(survey_trips, "_", ""))%>%filter(!!rlang::sym(cat_name)=='Total')

  
   p<-create.line.chart(t= shop_trips_households_long , w.x=cat_name, w.y='trips_per_household', w.g='survey_trips', est='number', w.color = 'psrc_light', x.type='percent') + 
  xlab('Household Characteristic') + ylab('Shopping Trips per Household')+theme(axis.title.x = element_text(size=25,color="#4C4C4C"))+theme(axis.text.x = element_text(size=25,color="#4C4C4C"))+theme(axis.title.y = element_text(size=25,color="#4C4C4C"))+theme(axis.text.y.left =   element_text(size=35,color="#4C4C4C"))+theme(legend.text=element_text(size=25))
   
    p1<-create.line.chart(t= shop_trips_households_long_total , w.x=cat_name, w.y='trips_per_household', w.g='survey_trips', est='number', w.color = 'psrc_light',x.type='percent') + 
  xlab('All Households') + ylab('Shopping Trips per Household')+theme(axis.title.x = element_text(size=25,color="#4C4C4C"))+theme(axis.text.x = element_text(size=25,color="#4C4C4C"))+theme(axis.title.y = element_text(size=25,color="#4C4C4C"))+theme(axis.text.y.left =   element_text(size=35,color="#4C4C4C"))+theme(legend.text=element_text(size=25))
  

  print(p)
  print(p1)
  

  
}
```
