---
title: "employmentstatusfullyathome"
author: "suzanne"
date: "2024-04-19"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(stringr)
library(travelSurveyTools)
library(psrcelmer)
library(dplyr)
library(psrcplot)
library(tidyverse)
library(forcats)
source('survey-23-preprocess.R')
```


```{r }
hh<- get_query(sql= "select  household_id as hh_id, hhincome_broad,survey_year, hh_weight
                from HHSurvey.v_households_labels")


person<- get_query(sql= "select household_id as hh_id,race_category,
person_id, workplace, employment, telecommute_freq, survey_year, person_weight, gender, age,hours_work, industry,office_available, commute_freq 
                from HHSurvey.v_persons_labels")
                
day<- get_query(sql= "select person_id, day_id, household_id as hh_id, telework_time, day_weight , survey_year from HHSurvey.v_days_labels")

trip<- get_query(sql= "select trip_id, household_id as hh_id, day_id,
person_id, mode_1, dest_purpose, survey_year, trip_weight 
                from HHSurvey.v_trips_labels")
setDT(hh)
setDT(person)
setDT(day)
setDT(trip)
```
#race_category needs to be added to the codebook

# to do: add Seattle, Bellevue geographies

## Read in Codebook
```{r pressure, echo=FALSE}
cb_path = str_glue("J:/Projects/Surveys/HHTravel/Survey2023/Data/codebook/PSRC_Combined_Codebook_2023_packagable.xlsx")

variable_list = readxl::read_xlsx(cb_path, sheet = 'variable_list')
value_labels = readxl::read_xlsx(cb_path, sheet = 'value_labels')

setDT(variable_list)
setDT(value_labels)
```

## Set IDs as characters
TO DO: functionalize convert all ids to characters, or store as characters upfront
```{r}

hh[, hh_id:=as.character(hh_id)]
person[, hh_id:=as.character(hh_id)]
day[, hh_id:=as.character(hh_id)]
trip[, hh_id := as.character(hh_id)]

person[, person_id := as.character(person_id)]
day[, person_id := as.character(person_id)]
trip[, person_id := as.character(person_id)]

day[, day_id := as.character(day_id)]
trip[, day_id := as.character(day_id)]

trip[, trip_id := as.character(trip_id)]
hh <- hh%>%mutate(survey_year=as.character(survey_year))
person <- person%>%mutate(survey_year=as.character(survey_year))
day <- day%>%mutate(survey_year=as.character(survey_year))
trip <- trip%>%mutate(survey_year=as.character(survey_year))
```

```{r}
person_23<-person%>%filter(survey_year=='2023')
person_23_list<-list(person=person_23)
```

```{r}


emp_workplace <- summarize_weighted(hts_data= person_23_list,
                               summarize_var = 'employment',
                               summarize_by = 'workplace',
                               id_cols=c('person_id'),
                               wt_cols=c('person_weight'),
                               wtname= 'person_weight'
                               )

```

```{r}
emp_workplace_sum<-emp_workplace$summary$wtd%>%pivot_wider(id_cols=workplace, names_from=employment, values_from=est )
```


```{r}


emp_workplace <- summarize_weighted(hts_data= person_23_list,
                               summarize_var = 'employment',
                               summarize_by = 'hours_work',
                               id_cols=c('person_id'),
                               wt_cols=c('person_weight'),
                               wtname= 'person_weight'
                               )

```

```{r}
emp_workplace_sum<-emp_workplace$summary$wtd%>%pivot_wider(id_cols=hours_work, names_from=employment, values_from=est )
```
