---
title: "freightdelivery_rmd"
author: "suzanne"
date: "2022-09-14"
output: html_document
---

# This analysis is looking at food, grocery, package, and work/service deliveries from 2017, 2019, 2017/2019, and 2021
# by household. 

# How many days did people receive deliveries?
# Did the number of deliveries change by year? by race? by income? by lifecycle?

```{r setup, include=FALSE}

# how many days did people receive deliveries?
# did the number of deliveries change by year? by race? by income?

# .libPaths()
# .libloc <- "C:/Users/MGrzybowski/AppData/Local/R/win-library/4.2"
# remove.packages("rlang")
# install.packages("rlang")

# r start

library(tidyverse)
library(data.table)
library(leaflet)
library(shiny)
library(tidytext)
library(dplyr)
library(readr)
library(ggplot2)
library(ggiraph)
library(magrittr)

# additional packages

library(usethis)
library(installr)
library(sf)
library(forcats)
library(tidyr)
library(summarytools)
library(sp)
library(gridExtra)
library(ggpubr)

# packages that are from github that host functions for pulling data (do the install in R Gui, not RStudio)

#devtools::install_github("psrc/psrc.travelsurvey", force = TRUE)
#devtools::install_github("psrc/psrccensus", force = TRUE)
#devtools::install_github("psrc/psrcplot", force = TRUE)
#devtools::install_github("psrc/psrctrends", force = TRUE)

# run these after installing github changes through R Gui

library(psrc.travelsurvey)
library(psrccensus)
library(psrcplot)
library(psrctrends)

# for Elmer connection

library(odbc)
library(DBI)

elmer_connect <- function(){
  DBI::dbConnect(odbc::odbc(),
                 driver = "ODBC Driver 17 for SQL Server",
                 server = "AWS-PROD-SQL\\Sockeye",
                 database = "Elmer",
                 trusted_connection = "yes",
                 port = 1433)
}

elmer_connection <- elmer_connect()

# views and global variables for days and households (** the days table has been updated to include hh variables)
# surveys a,b,c, and d will be used in functions later in code

deliveries <- dbReadTable(elmer_connection, SQL("HHSurvey.v_days"))
household_info <- dbReadTable(elmer_connection, SQL("HHSurvey.v_households"))

survey_a <- list(survey = '2017_2019', label = '2017/2019')
survey_b <- list(survey = '2021', label = '2021')
survey_c <- list(survey = '2017', label = '2017')
survey_d <- list(survey = '2019', label = '2019')

# look at variable names and which years they were collected/documented

# hhts_varsearch("delivery")
# hhts_varsearch("traveldate")
# hhts_varsearch("race")
# hhts_varsearch('income')
# hhts_varsearch('age')
# hhts_varsearch('county')
# hhts_varsearch('home')
# hhts_varsearch('race')

# names(deliveries)
# head(household_info)

# unique(household_info$lifecycle)
# unique(deliveries$delivery_work_freq)

install_psrc_fonts()

# create variables that would like to group by for analysis of deliveries by household

delivery_type <- c("household_id", "delivery_food_freq", "delivery_grocery_freq", "delivery_pkgs_freq","delivery_work_freq", "deliver_package", 'deliver_work', 'deliver_grocery', 'deliver_food')
days <- c("dayofweek", "typical_day")
hh_data <- c('lifecycle', 'hhincome_broad', 'hhincome_detailed', 'hhincome_dichot', 'race_category_alone_multi', 'race_eth_broad', 'race_eth_poc', 'race_eth_apoc', 'hh_race_category', 'seattle_home', 'final_home_rgcnum', 'final_home_uvnum', 'final_home_is_rgc','pernum')

```

```{r, visualization functions}
# function combining the delivery and household functions into one and ordering income by levels

smp_delivery_combo <- function(data, year) {
  ## rewriting labels of responses to be more concise
  temp_table <- data %>%
    mutate(delivery_food_all= case_when((pernum==1 & is.na(delivery_food_freq) & is.na(deliver_food)) ~ 'No HH Response',
                                        # pernum == 1 removes households where multiple members answered the question
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        delivery_food_freq == "0 (none)"  ~ 'No Delivery',
                                        deliver_food=='No' ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_pkgs_all= case_when((pernum==1 & is.na(delivery_pkgs_freq) & is.na(deliver_package)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        deliver_package=='No' ~ 'No Delivery',
                                        delivery_pkgs_freq == "0 (none)"  ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_grocery_all=case_when((pernum==1 & is.na(delivery_grocery_freq) & is.na(deliver_grocery)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        delivery_grocery_freq == "0 (none)"  ~ 'No Delivery',
                                        deliver_grocery=='No' ~ 'No Delivery',
                                        TRUE ~ 'Delivery Received'))%>%
    mutate(delivery_work_all= case_when((pernum==1 & is.na(delivery_work_freq) & is.na(deliver_work)) ~ 'No HH Response',
                                        (pernum>1) ~ 'Not Person One, not the responder',
                                        deliver_work =='No' ~ 'No Delivery',
                                        delivery_work_freq == "0 (none)"  ~ 'No Delivery',
                                         TRUE ~ 'Delivery Received'))%>%
     mutate(hhincome_broad = factor(case_when(as.character(hhincome_broad) %in% c("$100,000-$199,000","$200,000 or more") ~ 
                                             "$100,000 or more", !is.na(hhincome_broad) ~ as.character(hhincome_broad)),
                                  levels=c("Under $25,000", 
                                          "$25,000-$49,999", 
                                          "$50,000-$74,999", 
                                         "$75,000-$99,999", 
                                           "$100,000 or more", 
                                           "Prefer not to answer")))%>%
     mutate(lifecycle= case_when(lifecycle == "Household size > 1, Householder age 65+" | 
                                  lifecycle == "Household size = 1, Householder age 65+"  ~ '65 years or older', 
                                   lifecycle == "Household size > 1, Householder age 35 - 64" |
                                   lifecycle == "Household size = 1, Householder age 35 - 64" ~ '35-64 years',
                                   lifecycle == "Household size > 1, Householder under age 35" |
                                   lifecycle == "Household size = 1, Householder under age 35" ~ 'Under 35 years, no kids',
                                   lifecycle == "Household includes children age 5-17" ~ 'Household has ages 5-17',
                                   lifecycle == "Household includes children under 5" ~ 'Household has ages under 5'))
  temp_table
}

```

```{r, getting survey data with pre-identified variables for households}

# -- How frequently is someone having a delivery made?? 
# -- 2017, 2019, 2017/2019, 2021

# pull datasets from two separate dataframes per year

dsurvey_17 <- get_hhts(survey = survey_c$survey, 
                        level = "d", 
                        vars = c(delivery_type, days, hh_data)) 



dsurvey_19 <- get_hhts(survey = survey_d$survey, 
                       level = "d", 
                       vars = c(delivery_type, days, hh_data)) 



dsurvey_1719 <- get_hhts(survey = survey_a$survey, 
                       level = "d", 
                       vars = c(delivery_type, days, hh_data)) 



dsurvey_21 <- get_hhts(survey = survey_b$survey, 
                       level = "d", 
                       vars = c(delivery_type, days, hh_data)) 



```

```{r, generate datasets}

delivery_17 <- smp_delivery_combo(dsurvey_17, '2017')


delivery_19 <- smp_delivery_combo(dsurvey_19, '2019')


delivery_1719 <- smp_delivery_combo(dsurvey_1719, '2017/2019')


delivery_21 <- smp_delivery_combo(dsurvey_21, '2021')

```

```{r, rename datasets as "joined_df_deliveries_year"}

joined_df_deliveries_17 <-delivery_17

joined_df_deliveries_19 <- delivery_19

joined_df_deliveries_1719 <- delivery_1719

joined_df_deliveries_21 <- delivery_21

```

```{r, sum checks to verify population numbers, eval = FALSE}

# Sums should match the number of people in the region
# In 2021, this represents the number of adults, because didn't observe children's days

sum(joined_df_deliveries_17$day_weight_2017_v2021)
sum(joined_df_deliveries_19$day_weight_2019_v2021)
sum(joined_df_deliveries_21$person_weight_2021_ABS_panel_adult)

```
It looks like the day weight for 2017_2019 should be halved. That may have been an oversight.
```{r, sum checks to verify household numbers, eval = FALSE}
joined_df_deliveries_1719$day_weight_2017_2019_v2021<-joined_df_deliveries_1719$day_weight_2017_2019_v2021/2
sum(joined_df_deliveries_1719$day_weight_2017_2019_v2021)
dsurvey_17%>%filter(pernum==1)%>%summarize(hh_day=sum(day_weight_2017_v2021))
joined_df_deliveries_17%>%filter(pernum==1)%>%summarize(hh_day=sum(day_weight_2017_v2021))
```

```{r, removing duplicate household member responses}
joined_df_deliveries_17<<-joined_df_deliveries_17%>%filter(pernum==1)
joined_df_deliveries_19<-joined_df_deliveries_19%>%filter(pernum==1)
joined_df_deliveries_1719<-joined_df_deliveries_1719%>%filter(pernum==1)
joined_df_deliveries_21<-joined_df_deliveries_21%>%filter(pernum==1)
```

```{r, sum checks to verify households for the individual years with their new weights, eval = FALSE}
sum(joined_df_deliveries_17$day_weight_2017_v2021)
sum(joined_df_deliveries_19$day_weight_2019_v2021)
sum(joined_df_deliveries_1719$day_weight_2017_2019_v2021)
sum(joined_df_deliveries_21$hh_weight_2021_ABS) #this weight matches the closest to the annual household count
# sum(joined_df_deliveries_21$person_weight_2021_ABS_panel_adult)
# sum(joined_df_deliveries_21$person_weight_2021_ABS_panel_respondent)
```

```{r, removing true non-responses}
joined_df_deliveries_17<-joined_df_deliveries_17%>%filter(delivery_food_all!='No HH Response')
joined_df_deliveries_19<-joined_df_deliveries_19%>%filter(delivery_food_all!='No HH Response')
joined_df_deliveries_1719<-joined_df_deliveries_1719%>%filter(delivery_food_all!='No HH Response')
joined_df_deliveries_21<-joined_df_deliveries_21%>%filter(delivery_food_all!='No HH Response')
```

```{r, food deliveries by year alone}

count_food_17 <- hhts_count(joined_df_deliveries_17, group_vars = "delivery_food_all",
                                     spec_wgt = "day_weight_2017_v2021")%>%
  filter(delivery_food_all== "Delivery Received")


count_food_19 <- hhts_count(joined_df_deliveries_19, group_vars = "delivery_food_all",
                               spec_wgt = "day_weight_2019_v2021")%>%
  filter(delivery_food_all == "Delivery Received")


count_food_21 <- hhts_count(joined_df_deliveries_21, group_vars = "delivery_food_all",
                               spec_wgt = "hh_weight_2021_ABS") %>%
  filter(delivery_food_all == "Delivery Received")


# merge data frames for combined 2017/2019 and 2021
# write csv

food_freq_separate <- rbind(count_food_17, count_food_19, count_food_21)


write.csv(food_freq_separate, 'delivery_by_freq_food2.csv')

# create plot

food_c <-create_column_chart(t=food_freq_separate, x='delivery_food_all', y='share', f='survey', moe='share_moe', 
                          est ='percent', color = 'psrc_light')+
  xlab(as.character('Food')) + ylab('Share of Households Receiving These Types of Deliveries')+
  theme(axis.text.x = element_text(size=14,color="#4C4C4C"))+ 
  theme(axis.title.x = element_text(size=20,color="#4C4C4C"))+
  theme(axis.title.y = element_text(size=8,color="#4C4C4C"))

print(food_c)

```

```{r, package deliveries by year alone}

count_pkgs_17 <- hhts_count(joined_df_deliveries_17, group_vars = "delivery_pkgs_all",
                                     spec_wgt = "day_weight_2017_v2021")%>%
  filter(delivery_pkgs_all== "Delivery Received")


count_pkgs_19 <- hhts_count(joined_df_deliveries_19, group_vars = "delivery_pkgs_all",
                               spec_wgt = "day_weight_2019_v2021")%>%
  filter(delivery_pkgs_all == "Delivery Received")


count_pkgs_21 <- hhts_count(joined_df_deliveries_21, group_vars = "delivery_pkgs_all",
                               spec_wgt = "hh_weight_2021_ABS") %>%
  filter(delivery_pkgs_all == "Delivery Received")


# merge data frames for combined 2017/2019 and 2021
# write csv

pkgs_freq_separate <- rbind(count_pkgs_17, count_pkgs_19, count_pkgs_21)


write.csv(pkgs_freq_separate, 'delivery_by_freq_pkgs2.csv')

# create plot

pkgs_c <-create_column_chart(t=pkgs_freq_separate, x='delivery_pkgs_all', y='share', f='survey', moe='share_moe', 
                          est ='percent', color = 'psrc_light')+
  xlab(as.character('Packages')) + ylab('Share of Households Receiving These Types of Deliveries')+
  theme(axis.text.x = element_text(size=14,color="#4C4C4C"))+ 
  theme(axis.title.x = element_text(size=20,color="#4C4C4C"))+
  theme(axis.title.y = element_text(size=8,color="#4C4C4C"))

print(pkgs_c)

```

```{r, grocery deliveries by year alone}

count_grocery_17 <- hhts_count(joined_df_deliveries_17, group_vars = "delivery_grocery_all",
                                     spec_wgt = "day_weight_2017_v2021")%>%
  filter(delivery_grocery_all== "Delivery Received")


count_grocery_19 <- hhts_count(joined_df_deliveries_19, group_vars = "delivery_grocery_all",
                               spec_wgt = "day_weight_2019_v2021")%>%
  filter(delivery_grocery_all == "Delivery Received")


count_grocery_21 <- hhts_count(joined_df_deliveries_21, group_vars = "delivery_grocery_all",
                               spec_wgt = "hh_weight_2021_ABS") %>%
  filter(delivery_grocery_all == "Delivery Received")


# merge data frames for combined 2017/2019 and 2021
# write csv

grocery_freq_separate <- rbind(count_grocery_17, count_grocery_19, count_grocery_21)


write.csv(grocery_freq_separate, 'delivery_by_freq_grocery2.csv')

# create plot

grocery_c<-create_column_chart(t=grocery_freq_separate, x='delivery_grocery_all', y='share', f='survey', moe='share_moe', 
                          est ='percent', color = 'psrc_light')+
  xlab(as.character('Grocery')) + ylab('Share of Households Receiving These Types of Deliveries')+
  theme(axis.text.x = element_text(size=14,color="#4C4C4C"))+ 
  theme(axis.title.x = element_text(size=20,color="#4C4C4C"))+
  theme(axis.title.y = element_text(size=8,color="#4C4C4C"))

print(grocery_c)

```

```{r, work/service deliveries by year alone}
count_work_17 <- hhts_count(joined_df_deliveries_17, group_vars = "delivery_work_all",
                                     spec_wgt = "day_weight_2017_v2021")%>%
  filter(delivery_work_all== "Delivery Received")


count_work_19 <- hhts_count(joined_df_deliveries_19, group_vars = "delivery_work_all",
                               spec_wgt = "day_weight_2019_v2021")%>%
  filter(delivery_work_all == "Delivery Received")


count_work_21 <- hhts_count(joined_df_deliveries_21, group_vars = "delivery_work_all",
                               spec_wgt = "hh_weight_2021_ABS") %>%
  filter(delivery_work_all == "Delivery Received")


# merge data frames for combined 2017/2019 and 2021
# write csv

work_freq_separate <- rbind(count_work_17, count_work_19, count_work_21)


write.csv(work_freq_separate, 'delivery_by_freq_work2.csv')

# create plot

work_c<-create_column_chart(t=work_freq_separate, x='delivery_work_all', y='share', f='survey', moe='share_moe', 
                          est='percent', color = 'psrc_light')+
  xlab(as.character('Work/Service')) + ylab('Share of Households Receiving These Types of Deliveries')+
  theme(axis.text.x = element_text(size=14,color="#4C4C4C"))+ 
  theme(axis.title.x = element_text(size=20,color="#4C4C4C"))+
  theme(axis.title.y = element_text(size=8,color="#4C4C4C"))


print(work_c)
```

```{r, facet wrap charts for all deliveries}
# pull from Mary's T:\2022September\Mary\EquityTracker\Transportation\HCTaccess_2020_5y_Elmer_CSV.Rmd code

# rename column names so that can bind dfs
# change response type from Delivery Received to delivery_type (i.e., food, grocery, pkgs, work)

food_freq_separate$delivery_type = c("food/meal", "food/meal", "food/meal")

grocery_freq_separate$delivery_type = c("grocery", "grocery", "grocery")

pkgs_freq_separate$delivery_type = c("packages", "packages", "packages")

work_freq_separate$delivery_type = c("work/service", "work/service", "work/service")


# bind all dataframes together 

all_deliveries_freq_17_21 <- rbind(food_freq_separate, grocery_freq_separate, pkgs_freq_separate, work_freq_separate, fill = TRUE)
                                   
# remove unnecessary columns

all_deliveries_freq_17_21_new <- all_deliveries_freq_17_21[, -c(2, 9, 10, 11)]

# create facet bar chart

deliveries_facet1<- create_facet_bar_chart(t= all_deliveries_freq_17_21_new,
                                                  w.x="survey", w.y="share",
                                                  f="survey", g="delivery_type",
                                                  w.color="blues_inc",
                                                  est.type ="percent",
                                                  w.interactive="no",
                                                  w.dec=2,
                                                  w.scales="fixed",
                                                  w.facet=2,
                                                  w.title="Home Deliveries or Services",
                                                  w.sub.title="Share of Households on Average Weekday")

deliveries_facet1

deliveries_facet_test<- create_column_chart(t= all_deliveries_freq_17_21_new,
                                                  x="delivery_type", y="share",
                                                  f="survey",
                                            moe = "share_moe",
                                                  color="psrc_light",
                                                  est ="percent",
                                                  interactive="no",
                                                  dec=1,
                                                  title="Home Deliveries or Services",
                                                  subtitle="Share of Households on Average Weekday",
                                         source = "regional household travel survey")

deliveries_facet_test
```

```{r, count and share function, eval = FALSE}
# -- this chunk is essentially what was performed above so not necessary, see eval = FALSE


# crosstabs for income and food delivery by share and count (across years)
test2 <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('delivery_food_all', 'hhincome_broad')) %>% 
  filter(hhincome_broad != 'Total')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs
all_food_freq_17_21 <- bind_rows(count_food_17, count_food_19, count_food_21) %>%
  mutate(period = as.factor(survey))

table(all_food_freq_17_21$delivery_food_all, all_food_freq_17_21$period)


# plotting count and share

count_and_share_plot <- function(dt, grp_var, num_var, legend_name, tbl_name){
 
   fill_group <- dt[[grp_var]]
   x_axis_grp <- dt[[num_var]]
  
  count_plot <- ggplot(dt,
                       aes(x=x_axis_grp,
                           y=count,
                           fill = survey)) +
    geom_bar(stat="identity",
             position="dodge2") +
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Number") +
    scale_y_continuous(labels = scales::comma) +
    geom_errorbar(aes(ymin=count-count_moe, ymax=count+count_moe),
                  position = position_dodge2(width = 0.9, preserve = "single", padding = .5))
         
  share_plot <- ggplot(dt,
                       aes(x=x_axis_grp,
                           y=share,
                           fill = survey)) +
    geom_bar(stat="identity",
             position="dodge2") +
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share") +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  position = position_dodge2(width = 0.9, preserve = "single", padding = .5))
  
  trips <- ggarrange(count_plot, share_plot, 
                     # ncol = 2, nrow = 1,
                     common.legend = TRUE,
                     legend = "right")
  
  annotate_figure(trips, top = text_grob(tbl_name, 
                                         color = "blue", face = "bold", size = 14))
}

count_and_share_plot(all_food_freq_17_21,
                     "survey",
                     "delivery_food_all",
                     "Number of Deliveries per Household",
                     "Number vs Share of Trips by Destination")
```

```{r, create data frames to run crosstabs for income and food deliveries}
# crosstabs for income and food delivery by share and count (across years)

food_income_17 <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('hhincome_broad', 'delivery_food_all')) %>% 
  filter(hhincome_broad != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

food_income_19 <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('hhincome_broad', 'delivery_food_all')) %>% 
  filter(hhincome_broad != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

food_income_21 <- hhts_count(joined_df_deliveries_21, spec_wgt = 'hh_weight_2021_ABS', 
                    group_vars = c('hhincome_broad', 'delivery_food_all')) %>% 
  filter(hhincome_broad != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs

all_food_freq_17_21 <- bind_rows(food_income_17, food_income_19, food_income_21) %>%
  mutate(period = as.factor(survey))

sum(food_income_17$count)
sum(food_income_19$count)
sum(food_income_21$count)

table(all_food_freq_17_21$delivery_food_all, all_food_freq_17_21$period)
```

```{r, data visualization function for crosstabs}
# plot by year and by category

share_plot_by_year <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_freq_17_21[[grp_var]]
  x_axis_grp <- all_food_freq_17_21[[grp_var2]]
  
  ggplot(all_food_freq_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~period)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_year2 <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_freq_17_21[[grp_var]]
  x_axis_grp <- all_food_freq_17_21[[grp_var2]]
  
  ggplot(all_food_freq_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_food_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_cat <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_freq_17_21[[grp_var]]
  # facet_group <- all_commute_17_21[[grp_var2]]
  
  ggplot(all_food_freq_17_21, aes(x=period,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~all_food_freq_17_21[[grp_var2]])+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
}

count_plot_by_cat <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_freq_17_21[[grp_var]]
  # facet_group <- all_commute_17_21[[grp_var2]]
  
  ggplot(all_food_freq_17_21, aes(x=period,
                                       y=count,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~all_food_freq_17_21[[grp_var2]])+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Count",
         fill = legend_name) +
    scale_y_continuous(labels = scales::comma) +
    geom_errorbar(aes(ymin=count-count_moe, ymax=count+count_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
}
```

```{r, crosstabs for food deliveries and income broad, eval = FALSE}
# comparative charts/plots
# share_plot_by_year <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name)
share_plot_by_year(food_income_17, food_income_19, food_income_21,
                   'hhincome_broad', 'delivery_food_all', 
                   'Food Deliveries to Households by Income')

share_plot_by_year2(food_income_17, food_income_19, food_income_21,
                   'survey', 'hhincome_broad',  
                    'Food Deliveries by Year')

share_plot_by_cat(food_income_17, food_income_19, food_income_21, 
                  'hhincome_broad', 'delivery_food_all',
                  'Income Categories')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")

count_plot_by_cat(food_income_17, food_income_19, food_income_21, 
                  'hhincome_broad', 'delivery_food_all',
                  'Income Categories')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")

```

```{r, crosstabs for food deliveries and income dichotomies, share_plot_by_year2 is favored plot}

# crosstabs for income and food delivery by share and count (across years)

food_income_17_dichot <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('hhincome_dichot', 'delivery_food_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')%>%
  mutate(hhincome_dichot = fct_relevel(hhincome_dichot,
            "Under $75,000", "$75,000+", "Prefer not to answer"))

hhts_varsearch('hhincome_dichot')

food_income_19_dichot <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('hhincome_dichot', 'delivery_food_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

food_income_21_dichot <- hhts_count(joined_df_deliveries_21, spec_wgt = 'hh_weight_2021_ABS', 
                    group_vars = c('hhincome_dichot', 'delivery_food_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs

all_food_income_dichot_17_21 <- bind_rows(food_income_17_dichot, food_income_19_dichot, food_income_21_dichot) %>%
  mutate(period = as.factor(survey))

# plot by year and by category

share_plot_by_year_a <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_income_dichot_17_21[[grp_var]]
  x_axis_grp <- all_food_income_dichot_17_21[[grp_var2]]
  
  ggplot(all_food_income_dichot_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~period)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_year2_a <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_income_dichot_17_21[[grp_var]]
  x_axis_grp <- all_food_income_dichot_17_21[[grp_var2]]
  
  ggplot(all_food_income_dichot_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_food_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_cat_a <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_income_dichot_17_21[[grp_var2]]
  # facet_group <- all_commute_17_21[[grp_var2]]
  
  ggplot(all_food_income_dichot_17_21, aes(x=period,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~all_food_income_dichot_17_21[[grp_var]])+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
}

count_plot_by_cat_a <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_income_dichot_17_21[[grp_var2]]
  # facet_group <- all_commute_17_21[[grp_var2]]
  
  ggplot(all_food_income_dichot_17_21, aes(x=period,
                                       y=count,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~all_food_income_dichot_17_21[[grp_var]])+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Count",
         fill = legend_name) +
    scale_y_continuous(labels = scales::comma) +
    geom_errorbar(aes(ymin=count-count_moe, ymax=count+count_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
}

# create crosstab tables

share_plot_by_year_a(food_income_17_dichot, food_income_19_dichot, food_income_21_dichot,
                   'hhincome_dichot', 'delivery_food_all', 
                   'Food Deliveries to Households by Income')

share_plot_by_year2_a(food_income_17_dichot, food_income_19_dichot, food_income_21_dichot,
                   'survey', 'hhincome_dichot',  
                    'Food Deliveries by Year')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")

share_plot_by_cat_a(food_income_17_dichot, food_income_19_dichot, food_income_21_dichot, 
                  'hhincome_dichot', 'delivery_food_all',
                  'Income Categories')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")

count_plot_by_cat_a(food_income_17_dichot, food_income_19_dichot, food_income_21_dichot, 
                  'delivery_food_all','hhincome_dichot', 
                  'Income Categories')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")

```

```{r, crosstabs for grocery deliveries and income dichotomies, share_plot_by_year2 is favored plot}

# crosstabs for income and grocery delivery by share and count (across years)

grocery_income_17_dichot <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('hhincome_dichot', 'delivery_grocery_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_grocery_all != 'Total')%>%
  filter(delivery_grocery_all != 'No Delivery')%>%
  mutate(hhincome_dichot = fct_relevel(hhincome_dichot,
            "Under $75,000", "$75,000+", "Prefer not to answer"))

grocery_income_19_dichot <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('hhincome_dichot', 'delivery_grocery_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_grocery_all != 'Total')%>%
  filter(delivery_grocery_all != 'No Delivery')

grocery_income_1719_dichot <- hhts_count(joined_df_deliveries_1719, spec_wgt = 'day_weight_2017_2019_v2021', 
                    group_vars = c('hhincome_dichot', 'delivery_grocery_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_grocery_all != 'Total')%>%
  filter(delivery_grocery_all != 'No Delivery')%>%
  mutate(hhincome_dichot = fct_relevel(hhincome_dichot,
            "Under $75,000", "$75,000+", "Prefer not to answer"))%>%
  mutate(survey = case_when(survey == "2017_2019" ~ "2019/2019"))

grocery_income_21_dichot <- hhts_count(joined_df_deliveries_21, spec_wgt = 'hh_weight_2021_ABS', 
                    group_vars = c('hhincome_dichot', 'delivery_grocery_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_grocery_all != 'Total')%>%
  filter(delivery_grocery_all != 'No Delivery')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs

all_grocery_income_dichot_17_21 <- bind_rows(grocery_income_17_dichot, grocery_income_19_dichot, grocery_income_21_dichot) %>%
  mutate(period = as.factor(survey))

# plot by year and by category

share_plot_by_year2_b <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_grocery_income_dichot_17_21[[grp_var]]
  x_axis_grp <- all_grocery_income_dichot_17_21[[grp_var2]]
  
  ggplot(all_grocery_income_dichot_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_grocery_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

# create crosstab tables

share_plot_by_year2_b(grocery_income_17_dichot, grocery_income_19_dichot, grocery_income_21_dichot,
                   'survey', 'hhincome_dichot',  
                    'Grocery Deliveries by Year')+
  scale_fill_discrete_psrc("psrc_light")

groceries_test<- create_column_chart(t= all_grocery_income_dichot_17_21,
                                                  x="hhincome_dichot", y="share",
                                                  f="survey",
                                            moe = "share_moe",
                                                  color="psrc_pairs",
                                                  est ="percent",
                                                  interactive="no",
                                                  dec=1,
                                                  title="Grocery Deliveries",
                                                  subtitle="(i.e., Amazon Fresh, Safeway Online, Instacart)",
                                         source = "PSRC Regional Household Travel Survey")

groceries_test

```

```{r, crosstabs for package deliveries and income dichotomies, share_plot_by_year2 is favored plot}

# crosstabs for income and package delivery by share and count (across years)

pkg_income_17_dichot <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('hhincome_dichot', 'delivery_pkgs_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_pkgs_all != 'Total')%>%
  filter(delivery_pkgs_all != 'No Delivery')%>%
  mutate(hhincome_dichot = fct_relevel(hhincome_dichot,
            "Under $75,000", "$75,000+", "Prefer not to answer"))

pkg_income_19_dichot <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('hhincome_dichot', 'delivery_pkgs_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_pkgs_all != 'Total')%>%
  filter(delivery_pkgs_all != 'No Delivery')

pkg_income_1719_dichot <- hhts_count(joined_df_deliveries_1719, spec_wgt = 'day_weight_2017_2019_v2021', 
                    group_vars = c('hhincome_dichot', 'delivery_pkgs_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_pkgs_all != 'Total')%>%
  filter(delivery_pkgs_all != 'No Delivery')%>%
  mutate(hhincome_dichot = fct_relevel(hhincome_dichot,
            "Under $75,000", "$75,000+", "Prefer not to answer"))%>%
  mutate(survey = case_when(survey == "2017_2019" ~ "2019/2019"))

pkg_income_21_dichot <- hhts_count(joined_df_deliveries_21, spec_wgt = 'hh_weight_2021_ABS', 
                    group_vars = c('hhincome_dichot', 'delivery_pkgs_all')) %>% 
  filter(hhincome_dichot != 'Total')%>%
  filter(hhincome_dichot != 'Prefer not to answer') %>%
  filter(delivery_pkgs_all != 'Total')%>%
  filter(delivery_pkgs_all != 'No Delivery')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs

all_pkgs_income_dichot_17_21 <- bind_rows(pkg_income_1719_dichot, pkg_income_21_dichot) %>%
  mutate(period = as.factor(survey))

# plot by year and by category

share_plot_by_year2_c <- function(dt1, dt2, grp_var, grp_var2, legend_name){
  
  fill_group <- all_pkgs_income_dichot_17_21[[grp_var]]
  x_axis_grp <- all_pkgs_income_dichot_17_21[[grp_var2]]
  
  ggplot(all_pkgs_income_dichot_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_pkgs_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

# create crosstab tables

share_plot_by_year2_c(pkgs_income_1719_dichot, pkgs_income_21_dichot,
                   'survey', 'hhincome_dichot',  
                    'Package Deliveries by Year')+
  scale_fill_discrete_psrc("psrc_light")

pkgs_test<- create_column_chart(t= all_pkgs_income_dichot_17_21,
                                                  x="hhincome_dichot", y="share",
                                                  f="survey",
                                            moe = "share_moe",
                                                  color="psrc_light",
                                                  est ="percent",
                                                  interactive="no",
                                                  dec=1,
                                                  title="Package Deliveries",
                                                  subtitle="(i.e., FedEx, UPS, USPS)",
                                         source = "PSRC Regional Household Travel Survey")

pkgs_test

```

```{r, crosstabs for food deliveries and lifecycle stages - by year3 code includes combined 17/19, but can revert back to disaggregated if desired}

# crosstabs for lifecycle and food delivery by share and count (across years)

food_lifecycle_17 <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('delivery_food_all', 'lifecycle')) %>% 
  filter(lifecycle != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

food_lifecycle_19 <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('delivery_food_all', 'lifecycle')) %>% 
  filter(lifecycle != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

food_lifecycle_1719 <- hhts_count(joined_df_deliveries_1719, spec_wgt = 'day_weight_2017_2019_v2021', 
                    group_vars = c('delivery_food_all', 'lifecycle')) %>% 
  filter(lifecycle != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

food_lifecycle_21 <- hhts_count(joined_df_deliveries_21, spec_wgt = 'person_weight_2021_ABS_panel_adult', 
                    group_vars = c('delivery_food_all', 'lifecycle')) %>% 
  filter(lifecycle != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')


# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs
all_food_lifecycle_17_21 <- bind_rows(food_lifecycle_17, food_lifecycle_19, food_lifecycle_1719, food_lifecycle_21) %>%
  mutate(period = as.factor(survey))

table(all_food_lifecycle_17_21$delivery_food_all, all_food_lifecycle_17_21$period)

all_food_lifecycle_1719_21 <- bind_rows(food_lifecycle_1719, food_lifecycle_21) %>%
  mutate(period = as.factor(survey))

# plot by year and by category

share_plot_by_year_lifecycle <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_lifecycle_17_21[[grp_var]]
  x_axis_grp <- all_food_lifecycle_17_21[[grp_var2]]
  
  ggplot(all_food_lifecycle_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~period)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_year2_lifecycle <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_lifecycle_17_21[[grp_var]]
  x_axis_grp <- all_food_lifecycle_17_21[[grp_var2]]
  
  ggplot(all_food_lifecycle_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_food_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_year3_lifecycle <- function(dt1, dt2, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_lifecycle_1719_21[[grp_var]]
  x_axis_grp <- all_food_lifecycle_1719_21[[grp_var2]]
  
  ggplot(all_food_lifecycle_1719_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_food_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_cat_lifecycle <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_lifecycle_17_21[[grp_var]]
  # facet_group <- all_commute_17_21[[grp_var2]]
  
  ggplot(all_food_lifecycle_17_21, aes(x=period,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~all_food_lifecycle_17_21[[grp_var2]])+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
}

count_plot_by_cat_lifecycle <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_lifecycle_17_21[[grp_var]]
  # facet_group <- all_commute_17_21[[grp_var2]]
  
  ggplot(all_food_lifecycle_17_21, aes(x=period,
                                       y=count,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~all_food_lifecycle_17_21[[grp_var2]])+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Count",
         fill = legend_name) +
    scale_y_continuous(labels = scales::comma) +
    geom_errorbar(aes(ymin=count-count_moe, ymax=count+count_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
}

# comparative charts/plots
# share_plot_by_year <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name)
share_plot_by_year_lifecycle(food_lifecycle_17, food_lifecycle_19, food_lifecycle_21,
                   'lifecycle', 'delivery_food_all', 
                   'Food Deliveries to Households by Lifecycle')


share_plot_by_year2_lifecycle(food_lifecycle_17, food_lifecycle_19, food_lifecycle_21,
                   'survey', 'lifecycle',  
                    'Food Deliveries by Year')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")


share_plot_by_year3_lifecycle(food_lifecycle_1719, food_lifecycle_21,
                   'survey', 'lifecycle',  
                    'Food Deliveries by Year')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")


share_plot_by_cat_lifecycle(food_lifecycle_17, food_lifecycle_19, food_lifecycle_21, 
                  'lifecycle', 'delivery_food_all',
                  'Age')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")

```

```{r, food deliveries and rgc location/destination}

# location variables : 'seattle_home', 'final_home_rgcnum', 'final_home_uvnum', 'final_home_is_rgc'

food_rgc_17 <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('final_home_is_rgc', 'delivery_food_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

food_rgc_19 <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('final_home_is_rgc', 'delivery_food_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

food_rgc_21 <- hhts_count(joined_df_deliveries_21, spec_wgt = 'person_weight_2021_ABS_panel_adult', 
                    group_vars = c('final_home_is_rgc', 'delivery_food_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_food_all != 'Total')%>%
  filter(delivery_food_all != 'No Delivery')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs
all_food_rgc_17_21 <- bind_rows(food_rgc_17, food_rgc_19, food_rgc_21) %>%
  mutate(period = as.factor(survey))

table(all_food_rgc_17_21$delivery_food_all, all_food_rgc_17_21$period)

# plot by year and by category

share_plot_by_year_rgc<- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_rgc_17_21[[grp_var]]
  x_axis_grp <- all_food_rgc_17_21[[grp_var2]]
  
  ggplot(all_food_rgc_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~period)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_year2_rgc <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_rgc_17_21[[grp_var]]
  x_axis_grp <- all_food_rgc_17_21[[grp_var2]]
  
  ggplot(all_food_rgc_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_food_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

share_plot_by_cat_rgc<- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_rgc_17_21[[grp_var]]
  # facet_group <- all_commute_17_21[[grp_var2]]
  
  ggplot(all_food_rgc_17_21, aes(x=period,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~all_food_rgc_17_21[[grp_var2]])+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
}

count_plot_by_cat_rgc <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_food_rgc_17_21[[grp_var]]
  # facet_group <- all_commute_17_21[[grp_var2]]
  
  ggplot(all_food_rgc_17_21, aes(x=period,
                                       y=count,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~all_food_rgc_17_21[[grp_var2]])+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Count",
         fill = legend_name) +
    scale_y_continuous(labels = scales::comma) +
    geom_errorbar(aes(ymin=count-count_moe, ymax=count+count_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
}

# comparative charts/plots
# share_plot_by_year <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name)
share_plot_by_year_rgc(food_rgc_17, food_rgc_19, food_rgc_21,
                   'final_home_is_rgc', 'delivery_food_all', 
                   'Food Deliveries to Households by RGC location')


share_plot_by_year2_rgc(food_rgc_17, food_rgc_19, food_rgc_21,
                   'final_home_is_rgc', 'survey',  
                    'Food Deliveries by Year')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")

share_plot_by_cat_rgc(food_rgc_17, food_rgc_19, food_rgc_21, 
                  'final_home_is_rgc', 'delivery_food_all',
                  'Location')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")

#ppsrc plot style

food_rgc_plot<- create_column_chart(t= all_food_rgc_17_21,
                                                  x="final_home_is_rgc", y="share",
                                                  f="survey",
                                                  moe = "share_moe",
                                                  color="psrc_pairs",
                                                  est ="percent",
                                                  interactive="no",
                                                  dec=1,
                                                  title="Food/Meal Deliveries by Household Location",
                                                  subtitle="Share of Households on Average Weekday",
                                                  source = "PSRC Regional Household Travel Survey")

food_rgc_plot
```

```{r, grocery deliveries and rgc location/destination}

# location variables : 'seattle_home', 'final_home_rgcnum', 'final_home_uvnum', 'final_home_is_rgc'

grocery_rgc_17 <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('final_home_is_rgc', 'delivery_grocery_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_grocery_all != 'Total')%>%
  filter(delivery_grocery_all != 'No Delivery')

grocery_rgc_19 <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('final_home_is_rgc', 'delivery_grocery_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_grocery_all != 'Total')%>%
  filter(delivery_grocery_all != 'No Delivery')

grocery_rgc_21 <- hhts_count(joined_df_deliveries_21, spec_wgt = 'person_weight_2021_ABS_panel_adult', 
                    group_vars = c('final_home_is_rgc', 'delivery_grocery_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_grocery_all != 'Total')%>%
  filter(delivery_grocery_all != 'No Delivery')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs
all_grocery_rgc_17_21 <- bind_rows(grocery_rgc_17, grocery_rgc_19, grocery_rgc_21) %>%
  mutate(period = as.factor(survey))

table(all_grocery_rgc_17_21$delivery_grocery_all, all_grocery_rgc_17_21$period)

# plot by year and by category

share_plot_by_year2_rgc_groc <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_grocery_rgc_17_21[[grp_var]]
  x_axis_grp <- all_grocery_rgc_17_21[[grp_var2]]
  
  ggplot(all_grocery_rgc_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_grocery_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

# comparative charts/plots
# share_plot_by_year <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name)

share_plot_by_year2_rgc_groc(grocery_rgc_17, grocery_rgc_19, grocery_rgc_21,
                   'final_home_is_rgc', 'survey',  
                    'Grocery Deliveries by RGC')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")



# with psrcplot style

grocery_rgc_plot<- create_column_chart(t= all_grocery_rgc_17_21,
                                                  x="final_home_is_rgc", y="share",
                                                  f="survey",
                                            moe = "share_moe",
                                                  color="psrc_pairs",
                                                  est ="percent",
                                                  interactive="no",
                                                  dec=1,
                                                  title="Grocery Deliveries by Household Location",
                                                  subtitle="Share of Households on Average Weekday",
                                         source = "PSRC Regional Household Travel Survey")

grocery_rgc_plot
```

```{r, package deliveries and rgc location/destination}

# location variables : 'seattle_home', 'final_home_rgcnum', 'final_home_uvnum', 'final_home_is_rgc'

pkg_rgc_17 <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('final_home_is_rgc', 'delivery_pkgs_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_pkgs_all != 'Total')%>%
  filter(delivery_pkgs_all != 'No Delivery')

pkg_rgc_19 <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('final_home_is_rgc', 'delivery_pkgs_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_pkgs_all != 'Total')%>%
  filter(delivery_pkgs_all != 'No Delivery')

pkg_rgc_21 <- hhts_count(joined_df_deliveries_21, spec_wgt = 'person_weight_2021_ABS_panel_adult', 
                    group_vars = c('final_home_is_rgc', 'delivery_pkgs_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_pkgs_all != 'Total')%>%
  filter(delivery_pkgs_all != 'No Delivery')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs
all_pkg_rgc_17_21 <- bind_rows(pkg_rgc_17, pkg_rgc_19, pkg_rgc_21) %>%
  mutate(period = as.factor(survey))

table(all_pkg_rgc_17_21$delivery_pkgs_all, all_pkg_rgc_17_21$period)

# plot by year and by category

share_plot_by_year2_rgc_pkgs <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_pkg_rgc_17_21[[grp_var]]
  x_axis_grp <- all_pkg_rgc_17_21[[grp_var2]]
  
  ggplot(all_pkg_rgc_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_pkgs_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

# comparative charts/plots
# share_plot_by_year <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name)

share_plot_by_year2_rgc_pkgs(pkg_rgc_17, pkg_rgc_19, pkg_rgc_21,
                   'final_home_is_rgc', 'survey',  
                    'Package Deliveries by RGC')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")



# with psrcplot style

pkg_rgc_plot<- create_column_chart(t= all_pkg_rgc_17_21,
                                                  x="final_home_is_rgc", y="share",
                                                  f="survey",
                                            moe = "share_moe",
                                                  color="psrc_pairs",
                                                  est ="percent",
                                                  interactive="no",
                                                  dec=1,
                                                  title="Package Deliveries by Household Location",
                                                  subtitle="Share of Households on Average Weekday",
                                         source = "PSRC Regional Household Travel Survey")

pkg_rgc_plot
```
```{r}
# location variables : 'seattle_home', 'final_home_rgcnum', 'final_home_uvnum', 'final_home_is_rgc'

work_rgc_17 <- hhts_count(joined_df_deliveries_17, spec_wgt = 'day_weight_2017_v2021', 
                    group_vars = c('final_home_is_rgc', 'delivery_work_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_work_all != 'Total')%>%
  filter(delivery_work_all != 'No Delivery')

work_rgc_19 <- hhts_count(joined_df_deliveries_19, spec_wgt = 'day_weight_2019_v2021', 
                    group_vars = c('final_home_is_rgc', 'delivery_work_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_work_all != 'Total')%>%
  filter(delivery_work_all != 'No Delivery')

work_rgc_21 <- hhts_count(joined_df_deliveries_21, spec_wgt = 'person_weight_2021_ABS_panel_adult', 
                    group_vars = c('final_home_is_rgc', 'delivery_work_all')) %>% 
  filter(final_home_is_rgc != 'Total')%>%
  filter(delivery_work_all != 'Total')%>%
  filter(delivery_work_all != 'No Delivery')

# merge dfs for 2017, 2017/2019, and 2021 - alternate approach for crosstabs
all_work_rgc_17_21 <- bind_rows(work_rgc_17, work_rgc_19, work_rgc_21) %>%
  mutate(period = as.factor(survey))

table(all_work_rgc_17_21$delivery_work_all, all_work_rgc_17_21$period)

# plot by year and by category

share_plot_by_year2_rgc_work <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name){
  
  fill_group <- all_work_rgc_17_21[[grp_var]]
  x_axis_grp <- all_work_rgc_17_21[[grp_var2]]
  
  ggplot(all_work_rgc_17_21, aes(x=x_axis_grp,
                                       y=share,
                                       fill=fill_group)) +
    geom_bar(stat="identity",
             position="dodge2") +
    facet_wrap(~delivery_work_all)+
    theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1),
          axis.title.x = element_blank()) +
    labs(y = "Share",
         fill = legend_name) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe),
                  size=.5, width=.2,
                  position=position_dodge(0.9))
  
}

# comparative charts/plots
# share_plot_by_year <- function(dt1, dt2, dt3, grp_var, grp_var2, legend_name)

share_plot_by_year2_rgc_work(work_rgc_17, work_rgc_19, work_rgc_21,
                   'final_home_is_rgc', 'survey',  
                    'Package Deliveries by RGC')+
  psrc_style()+
  scale_fill_discrete_psrc("psrc_light")



# with psrcplot style

work_rgc_plot<- create_column_chart(t= all_work_rgc_17_21,
                                                  x="final_home_is_rgc", y="share",
                                                  f="survey",
                                            moe = "share_moe",
                                                  color="psrc_pairs",
                                                  est ="percent",
                                                  interactive="no",
                                                  dec=1,
                                                  title="Package Deliveries by Household Location",
                                                  subtitle="Share of Households on Average Weekday",
                                         source = "PSRC Regional Household Travel Survey")

work_rgc_plot
```

```{r, rgc facet wrap with fixed scale}

all_food_rgc_17_21$delivery_type = c("food/meal", "food/meal", "food/meal", "food/meal", "food/meal", "food/meal")

all_grocery_rgc_17_21$delivery_type = c("grocery", "grocery", "grocery", "grocery", "grocery", "grocery")

all_pkg_rgc_17_21$delivery_type = c("packages", "packages", "packages", "packages", "packages", "packages")

all_work_rgc_17_21$delivery_type = c("work/service", "work/service", "work/service", "work/service", "work/service", "work/service")

# bind all dataframes together 

all_deliveries_rgc <- rbind(all_food_rgc_17_21, all_grocery_rgc_17_21, all_pkg_rgc_17_21, all_work_rgc_17_21, fill = TRUE)
                                   
# remove unnecessary columns

all_deliveries_rgc_new <- all_deliveries_rgc[, -c(3, 11, 12, 13)]

# create facet bar chart

deliveries_rgc<- create_facet_bar_chart(t= all_deliveries_rgc_new,
                                                  w.x="final_home_is_rgc", w.y="share",
                                                  f="survey", g="delivery_type",
                                                  w.color="psrc_pairs",
                                                  est.type ="percent",
                                                  w.interactive="no",
                                                  w.dec=2,
                                                  w.scales="fixed",
                                                  w.facet=4,
                                                  w.title="Home Deliveries by RGC",
                                                  w.sub.title="Share of Households on Average Weekday")

deliveries_rgc

```
